# -*- coding: utf-8 -*-
# AUTO-GENERATED by tools/racc_to_ply.py — review FIXME
# from bnf.y.rb rule section

import re

def _json_to_sym(v):
    """JSON_string は str、Token の場合は to_sym。Ruby の String#to_sym 相当。"""
    if hasattr(v, "to_sym"):
        return v.to_sym()
    from tecslib.rubylib.symbol import Sym
    return Sym(str(v))


def _json_token_num(tok):
    """JSON_number 用: Token.val が int/float または to_i/to_f 持ちオブジェクト."""
    v = tok.val if hasattr(tok, "val") else tok
    if isinstance(v, int):
        return v
    if isinstance(v, float):
        return v
    if hasattr(v, "to_i"):
        return v.to_i()
    return int(v)


def _json_token_float(tok):
    v = tok.val if hasattr(tok, "val") else tok
    if isinstance(v, (int, float)):
        return float(v)
    if hasattr(v, "to_f"):
        return v.to_f()
    return float(v)

def p_empty(p):
    'empty :'
    pass

def p_mra_1(p):
    '''mra_1 :'''
    StructType.set_define( True )

def p_mra_2(p):
    '''mra_2 :'''
    # tag が無い場合、内部名を与える
    from tecslib.rubylib.symbol import Sym
    p[0] = StructType( Sym("TAG__{}__".format(Generator.no_struct_tag_num)) )
    Generator.no_struct_tag_num += 1
    StructType.set_define( True )

def p_mra_3(p):
    '''mra_3 :'''
    Cell.new_def()

def p_mra_4(p):
    '''mra_4 :'''
    Cell.new_def()

def p_mra_typedef_reg(p):
    '''mra_typedef_reg :'''
    # PLY は typedef の ';' 還元判定のために次トークンを先読みする。
    # その前に typedef 名を登録し TYPE_NAME 化できるようにする。
    decl_list = p[-1]
    tsql = p[-2]
    for d in decl_list:
        d.set_kind("TYPEDEF")
    Typedef.new_decl_list(tsql, decl_list)

def p_mra_typedef_reg2(p):
    '''mra_typedef_reg2 :'''
    decl_list = p[-1]
    tsql = p[-2]
    for d in decl_list:
        d.set_kind("TYPEDEF")
    Typedef.new_decl_list(tsql, decl_list)

def p_all(p):
    '''all : component_description'''
    p[0] = p[1]

def p_primary_expression_1(p):
    '''primary_expression : namespace_identifier'''
    p[0] = [ "IDENTIFIER", p[1] ]

def p_primary_expression_2(p):
    '''primary_expression : TRUE'''
    p[0] = [ "BOOL_CONSTANT", True ]

def p_primary_expression_3(p):
    '''primary_expression : FALSE'''
    p[0] = [ "BOOL_CONSTANT", False ]

def p_primary_expression_4(p):
    '''primary_expression : INTEGER_CONSTANT'''
    p[0] = [ "INTEGER_CONSTANT", p[1] ]

def p_primary_expression_5(p):
    '''primary_expression : FLOATING_CONSTANT'''
    p[0] = [ "FLOATING_CONSTANT", p[1] ]

def p_primary_expression_6(p):
    '''primary_expression : OCTAL_CONSTANT'''
    p[0] = [ "OCTAL_CONSTANT", p[1] ]

def p_primary_expression_7(p):
    '''primary_expression : HEX_CONSTANT'''
    p[0] = [ "HEX_CONSTANT", p[1] ]

def p_primary_expression_8(p):
    '''primary_expression : CHARACTER_LITERAL'''
    p[0] = [ "CHARACTER_LITERAL", p[1] ]

def p_primary_expression_9(p):
    '''primary_expression : string_literal_list'''
    p[0] = [ "STRING_LITERAL_LIST", p[1] ]

def p_primary_expression_10(p):
    '''primary_expression : "(" expression ")"'''
    p[0] = [ "PARENTHESES", p[2].get_elements() ]

def p_string_literal_list_1(p):
    '''string_literal_list : STRING_LITERAL'''
    p[0] = p[1]

def p_string_literal_list_2(p):
    '''string_literal_list : string_literal_list STRING_LITERAL'''
    # 連接した文字列を1つの文字列にまとめる
    str = "\"" + re.sub(r'\"(.*)\"', "\\1", p[1].val) + re.sub(r'\"(.*)\"', "\\1", p[2].val) + "\""
    p[0] = Token( str, p[1].file, p[1].lineno, p[1].col )

def p_postfix_expression_1(p):
    '''postfix_expression : primary_expression'''
    p[0] = p[1]

def p_postfix_expression_2(p):
    '''postfix_expression : postfix_expression "[" expression "]"'''
    p[0] = [ "OP_SUBSC", p[1], p[3] ]

def p_postfix_expression_3(p):
    '''postfix_expression : postfix_expression "." IDENTIFIER'''
    p[0] = [ "OP_DOT", p[1], p[3] ]

def p_postfix_expression_4(p):
    '''postfix_expression : postfix_expression "->" IDENTIFIER'''
    p[0] = [ "OP_REF", p[1], p[3] ]

def p_unary_expression_1(p):
    '''unary_expression : postfix_expression'''
    p[0] = p[1]

def p_unary_expression_2(p):
    '''unary_expression : unary_operator cast_expression'''
    p[0] = [ p[1], p[2] ]

def p_unary_expression_3(p):
    '''unary_expression : SIZEOF unary_expression'''
    p[0] = [ "OP_SIZEOF_EXPR", p[2] ]

def p_unary_expression_4(p):
    '''unary_expression : SIZEOF "(" type_name ")"'''
    p[0] = [ "OP_SIZEOF_TYPE", p[2] ]

def p_unary_operator_1(p):
    '''unary_operator : "&"'''
    p[0] = "OP_U_AMP"

def p_unary_operator_2(p):
    '''unary_operator : "*"'''
    p[0] = "OP_U_ASTER"

def p_unary_operator_3(p):
    '''unary_operator : "+"'''
    p[0] = "OP_U_PLUS"

def p_unary_operator_4(p):
    '''unary_operator : "-"'''
    p[0] = "OP_U_MINUS"

def p_unary_operator_5(p):
    '''unary_operator : "~"'''
    p[0] = "OP_U_TILDE"

def p_unary_operator_6(p):
    '''unary_operator : "!"'''
    p[0] = "OP_U_EXCLAM"

def p_cast_expression_1(p):
    '''cast_expression : unary_expression'''
    p[0] = p[1]

def p_cast_expression_2(p):
    '''cast_expression : "(" type_name ")" cast_expression'''
    p[0] = [ "CAST", p[2], p[4] ]

def p_multiplicative_expression_1(p):
    '''multiplicative_expression : cast_expression'''
    p[0] = p[1]

def p_multiplicative_expression_2(p):
    '''multiplicative_expression : multiplicative_expression "*" cast_expression'''
    p[0] = [ "OP_MULT", p[1], p[3] ]

def p_multiplicative_expression_3(p):
    '''multiplicative_expression : multiplicative_expression "/" cast_expression'''
    p[0] = [ "OP_DIV", p[1], p[3] ]

def p_multiplicative_expression_4(p):
    '''multiplicative_expression : multiplicative_expression "%" cast_expression'''
    p[0] = [ "OP_REMAIN", p[1], p[3] ]

def p_additive_expression_1(p):
    '''additive_expression : multiplicative_expression'''
    p[0] = p[1]

def p_additive_expression_2(p):
    '''additive_expression : additive_expression "+" multiplicative_expression'''
    p[0] = [ "OP_ADD", p[1], p[3] ]

def p_additive_expression_3(p):
    '''additive_expression : additive_expression "-" multiplicative_expression'''
    p[0] = [ "OP_SUB", p[1], p[3] ]

def p_shift_expression_1(p):
    '''shift_expression : additive_expression'''
    p[0] = p[1]

def p_shift_expression_2(p):
    '''shift_expression : shift_expression "<<" additive_expression'''
    p[0] = [ "OP_LSFT", p[1], p[3] ]

def p_shift_expression_3(p):
    '''shift_expression : shift_expression ">>" additive_expression'''
    p[0] = [ "OP_RSFT", p[1], p[3] ]

def p_relational_expression_1(p):
    '''relational_expression : shift_expression'''
    p[0] = p[1]

def p_relational_expression_2(p):
    '''relational_expression : relational_expression "<" shift_expression'''
    p[0] = [ "OP_LT", p[1], p[3] ]

def p_relational_expression_3(p):
    '''relational_expression : relational_expression ">" shift_expression'''
    p[0] = [ "OP_GT", p[1], p[3] ]

def p_relational_expression_4(p):
    '''relational_expression : relational_expression "<=" shift_expression'''
    p[0] = [ "OP_LE", p[1], p[3] ]

def p_relational_expression_5(p):
    '''relational_expression : relational_expression ">=" shift_expression'''
    p[0] = [ "OP_GE", p[1], p[3] ]

def p_equality_expression_1(p):
    '''equality_expression : relational_expression'''
    p[0] = p[1]

def p_equality_expression_2(p):
    '''equality_expression : equality_expression "==" relational_expression'''
    p[0] = [ "OP_EQ", p[1], p[3] ]

def p_equality_expression_3(p):
    '''equality_expression : equality_expression "!=" relational_expression'''
    p[0] = [ "OP_NE", p[1], p[3] ]

def p_and_expression_1(p):
    '''and_expression : equality_expression'''
    p[0] = p[1]

def p_and_expression_2(p):
    '''and_expression : and_expression "&" equality_expression'''
    p[0] = [ "OP_AND", p[1], p[3] ]

def p_exclusive_or_expression_1(p):
    '''exclusive_or_expression : and_expression'''
    p[0] = p[1]

def p_exclusive_or_expression_2(p):
    '''exclusive_or_expression : exclusive_or_expression "^" and_expression'''
    p[0] = [ "OP_EOR", p[1], p[3] ]

def p_inclusive_or_expression_1(p):
    '''inclusive_or_expression : exclusive_or_expression'''
    p[0] = p[1]

def p_inclusive_or_expression_2(p):
    '''inclusive_or_expression : inclusive_or_expression "|" exclusive_or_expression'''
    p[0] = [ "OP_OR", p[1], p[3] ]

def p_logical_and_expression_1(p):
    '''logical_and_expression : inclusive_or_expression'''
    p[0] = p[1]

def p_logical_and_expression_2(p):
    '''logical_and_expression : logical_and_expression "&&" inclusive_or_expression'''
    p[0] = [ "OP_LAND", p[1], p[3] ]

def p_logical_or_expression_1(p):
    '''logical_or_expression : logical_and_expression'''
    p[0] = p[1]

def p_logical_or_expression_2(p):
    '''logical_or_expression : logical_or_expression "||" logical_and_expression'''
    p[0] = [ "OP_LOR", p[1], p[3] ]

def p_conditional_expression_1(p):
    '''conditional_expression : logical_or_expression'''
    p[0] = p[1]

def p_conditional_expression_2(p):
    '''conditional_expression : logical_or_expression "?" expression ":" conditional_expression'''
    p[0] = [ "OP_CEX", p[1], p[3].get_elements(), p[5] ]

def p_expression(p):
    '''expression : conditional_expression'''
    p[0] = Expression( p[1] )


def p_constant_expression(p):
    '''constant_expression : conditional_expression'''
    p[0] = Expression( p[1] )









def p_declaration(p):
    '''declaration : type_specifier_qualifier_list init_declarator_list ";"'''
    for i in p[2]:
        i.set_type( p[1] )
        p[0] = p[2]

def p_declaration_specifiers_1(p):
    '''declaration_specifiers : type_specifier'''
    p[0] = p[1]

def p_declaration_specifiers_2(p):
    '''declaration_specifiers : type_qualifier type_specifier'''
    p[2].set_qualifier( p[1] )
    p[0] = p[2]

def p_init_declarator_list_1(p):
    '''init_declarator_list : init_declarator'''
    p[0] = [p[1]]

def p_init_declarator_list_2(p):
    '''init_declarator_list : init_declarator_list "," init_declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_init_declarator_1(p):
    '''init_declarator : declarator'''
    p[0] = p[1]

def p_init_declarator_2(p):
    '''init_declarator : declarator "=" initializer'''
    p[1].set_initializer( p[3] )
    p[0] = p[1]

def p_type_specifier_1(p):
    '''type_specifier : VOID'''
    p[0] = VoidType()

def p_type_specifier_2(p):
    '''type_specifier : FLOAT32_T'''
    p[0] = FloatType(32)

def p_type_specifier_3(p):
    '''type_specifier : DOUBLE64_T'''
    p[0] = FloatType(64)

def p_type_specifier_4(p):
    '''type_specifier : struct_specifier'''
    p[0] = p[1]

def p_type_specifier_5(p):
    '''type_specifier : enum_specifier'''
    p[0] = p[1]

def p_type_specifier_6(p):
    '''type_specifier : TYPE_NAME'''
    p[0] = DefinedType( p[1].val )

def p_type_specifier_7(p):
    '''type_specifier : sign_int_type'''
    p[0] = p[1]

def p_type_specifier_8(p):
    '''type_specifier : char_type'''
    p[0] = p[1]

def p_type_specifier_9(p):
    '''type_specifier : BOOL_T'''
    p[0] = BoolType()

def p_type_specifier_10(p):
    '''type_specifier : FLOAT'''
    Generator.warning( "W5002 float: obsolete type. use float32_t"  )
    p[0] = FloatType(32)

def p_type_specifier_11(p):
    '''type_specifier : DOUBLE'''
    Generator.warning( "W5003 double: obsolete type. use double64_t"  )
    p[0] = FloatType(64)

def p_type_specifier_12(p):
    '''type_specifier : DESCRIPTOR "(" namespace_identifier ")"'''
    p[0] = DescriptorType( p[3] )

def p_char_type_1(p):
    '''char_type : CHAR_T'''
    p[0] = IntType( -1 )

def p_char_type_2(p):
    '''char_type : SCHAR_T'''
    p[0] = IntType( -1 )
    p[0].set_sign( "SIGNED", True )

def p_char_type_3(p):
    '''char_type : UCHAR_T'''
    p[0] = IntType( -1 )
    p[0].set_sign( "UNSIGNED", True )

def p_int_type_1(p):
    '''int_type : CHAR'''
    # Generator.warning( "W5004 char: obsolete type. use char_t"  )
    p[0] = IntType( -11 )

def p_int_type_2(p):
    '''int_type : SHORT'''
    p[0] = IntType( -2 )

def p_int_type_3(p):
    '''int_type : INT'''
    p[0] = IntType( -3 )

def p_int_type_4(p):
    '''int_type : LONG'''
    p[0] = IntType( -4 )

def p_int_type_5(p):
    '''int_type : INT8_T'''
    p[0] = IntType( 8 )

def p_int_type_6(p):
    '''int_type : INT16_T'''
    p[0] = IntType( 16 )

def p_int_type_7(p):
    '''int_type : INT32_T'''
    p[0] = IntType( 32 )

def p_int_type_8(p):
    '''int_type : INT64_T'''
    p[0] = IntType( 64 )

def p_int_type_9(p):
    '''int_type : INT128_T'''
    p[0] = IntType( 128 )

def p_int_type_10(p):
    '''int_type : UINT8_T'''
    p[0] = IntType( 8 )
    p[0].set_sign( "UNSIGNED", True )

def p_int_type_11(p):
    '''int_type : UINT16_T'''
    p[0] = IntType( 16 )
    p[0].set_sign( "UNSIGNED", True )

def p_int_type_12(p):
    '''int_type : UINT32_T'''
    p[0] = IntType( 32 )
    p[0].set_sign( "UNSIGNED", True )

def p_int_type_13(p):
    '''int_type : UINT64_T'''
    p[0] = IntType( 64 )
    p[0].set_sign( "UNSIGNED", True )

def p_int_type_14(p):
    '''int_type : UINT128_T'''
    p[0] = IntType( 128 )
    p[0].set_sign( "UNSIGNED", True )

def p_sign_1(p):
    '''sign : SIGNED'''
    p[0] = "SIGNED"

def p_sign_2(p):
    '''sign : UNSIGNED'''
    p[0] = "UNSIGNED"

def p_sign_int_type_1(p):
    '''sign_int_type : sign int_type'''
    p[2].set_sign( p[1] )
    p[0] = p[2]

def p_sign_int_type_2(p):
    '''sign_int_type : int_type'''
    p[0] = p[1]

def p_struct_specifier_1(p):
    '''struct_specifier : STRUCT struct_tag "{" mra_1 struct_declaration_list "}"'''
    Generator.set_locale_from_token(p[6])
    StructType.end_of_parse()
    p[0] = p[2]

def p_struct_specifier_2(p):
    '''struct_specifier : STRUCT mra_2 "{" struct_declaration_list "}"'''
    Generator.set_locale_from_token(p[5])
    StructType.end_of_parse()
    p[0] = p[2]

def p_struct_specifier_3(p):
    '''struct_specifier : STRUCT struct_tag'''
    StructType.set_define( False )
    StructType.end_of_parse()
    p[0] = p[2]

def p_struct_declaration_list_1(p):
    '''struct_declaration_list : struct_declaration'''
    p[0] = p[1]

def p_struct_declaration_list_2(p):
    '''struct_declaration_list : struct_declaration_list struct_declaration'''
    p[0] = p[1]  # default racc result

def p_struct_tag(p):
    '''struct_tag : IDENTIFIER'''
    p[0] = StructType( p[1].val )

def p_struct_declaration_1(p):
    '''struct_declaration : type_specifier_qualifier_list struct_declarator_list ";"'''
    for i in p[2]:
        i.set_type( p[1] )
        i.set_kind( "MEMBER" )
        i.check()
        StructType.new_member( i )
        p[0] = p[2]

def p_struct_declaration_2(p):
    '''struct_declaration : spec_L pointer_specifier_list spec_R type_specifier_qualifier_list struct_declarator_list ";"'''
    for i in p[5]:
        i.set_type( p[4] )
        i.set_kind( "MEMBER" )
        i.set_specifier_list(p[2])
        i.check()
        StructType.new_member( i )
        p[0] = p[5]

def p_pointer_specifier_list_1(p):
    '''pointer_specifier_list : pointer_specifier'''
    p[0] = [ p[1] ]

def p_pointer_specifier_list_2(p):
    '''pointer_specifier_list : pointer_specifier_list "," pointer_specifier'''
    p[0] = p[1]
    p[0].append(p[3])

def p_pointer_specifier_1(p):
    '''pointer_specifier : STRING'''
    p[0] = ["STRING",-1]

def p_pointer_specifier_2(p):
    '''pointer_specifier : STRING "(" expression ")"'''
    p[0] = ["STRING",p[3]]

def p_pointer_specifier_3(p):
    '''pointer_specifier : SIZE_IS "(" expression ")"'''
    p[0] = ["SIZE_IS",p[3]]

def p_pointer_specifier_4(p):
    '''pointer_specifier : COUNT_IS "(" expression ")"'''
    p[0] = ["COUNT_IS",p[3]]

def p_type_specifier_qualifier_list_1(p):
    '''type_specifier_qualifier_list : type_specifier'''
    p[0] = p[1]

def p_type_specifier_qualifier_list_2(p):
    '''type_specifier_qualifier_list : type_qualifier type_specifier_qualifier_list'''
    p[2].set_qualifier( p[1] )
    p[0] = p[2]

def p_struct_declarator_list_1(p):
    '''struct_declarator_list : struct_declarator'''
    p[0] = [ p[1] ]

def p_struct_declarator_list_2(p):
    '''struct_declarator_list : struct_declarator_list "," struct_declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_struct_declarator(p):
    '''struct_declarator : declarator'''
    p[0] = p[1]

def p_enum_specifier_1(p):
    '''enum_specifier : enum_type "{" enumerator_list "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_2(p):
    '''enum_specifier : enum_type IDENTIFIER "{" enumerator_list "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_3(p):
    '''enum_specifier : enum_type IDENTIFIER'''
    p[0] = p[1]  # default racc result

def p_enum_type_1(p):
    '''enum_type : ENUM'''
    p[0] = EnumType( -1 )

def p_enum_type_2(p):
    '''enum_type : ENUM8'''
    p[0] = EnumType( 8 )

def p_enum_type_3(p):
    '''enum_type : ENUM16'''
    p[0] = EnumType( 16 )

def p_enum_type_4(p):
    '''enum_type : ENUM32'''
    p[0] = EnumType( 32 )

def p_enum_type_5(p):
    '''enum_type : ENUM64'''
    p[0] = EnumType( 64 )

def p_enum_type_6(p):
    '''enum_type : ENUM128'''
    p[0] = EnumType( 128 )

def p_enumerator_list_1(p):
    '''enumerator_list : enumerator'''
    p[0] = p[1]

def p_enumerator_list_2(p):
    '''enumerator_list : enumerator_list "," enumerator'''
    p[0] = p[1]  # default racc result

def p_enumerator_1(p):
    '''enumerator : IDENTIFIER'''
    p[0] = p[1]

def p_enumerator_2(p):
    '''enumerator : IDENTIFIER "=" constant_expression'''
    p[0] = p[1]  # default racc result

def p_type_qualifier_1(p):
    '''type_qualifier : CONST'''
    p[0] = "CONST"

def p_type_qualifier_2(p):
    '''type_qualifier : VOLATILE'''
    p[0] = "VOLATILE"

def p_declarator_1(p):
    '''declarator : pointer direct_declarator'''
    p[2].set_type( p[1] )
    p[0] = p[2]

def p_declarator_2(p):
    '''declarator : direct_declarator'''
    p[0] = p[1]

def p_direct_declarator_1(p):
    '''direct_declarator : IDENTIFIER'''
    p[0] = Decl( p[1].val )

def p_direct_declarator_2(p):
    '''direct_declarator : "(" declarator ")"'''
    p[0] = p[2]

def p_direct_declarator_3(p):
    '''direct_declarator : direct_declarator "[" constant_expression "]"'''
    p[1].set_type( ArrayType( p[3] ) )
    p[0] = p[1]

def p_direct_declarator_4(p):
    '''direct_declarator : direct_declarator "[" "]"'''
    p[1].set_type( ArrayType() )
    p[0] = p[1]

def p_direct_declarator_5(p):
    '''direct_declarator : direct_declarator "(" parameter_type_list ")"'''
    p[1].set_type( FuncType( p[3] ) )
    p[0] = p[1]

def p_direct_declarator_6(p):
    '''direct_declarator : direct_declarator "(" ")"'''
    Generator.warning( "W5010 need 'void' for no parameter"  )
    p[1].set_type( FuncType() )
    p[0] = p[1]

def p_pointer_1(p):
    '''pointer : "*"'''
    p[0] = PtrType()

def p_pointer_2(p):
    '''pointer : "*" type_qualifier'''
    p[0] = PtrType()
    p[0].set_qualifier( p[2] )

def p_pointer_3(p):
    '''pointer : "*" pointer'''
    p[2].set_type(PtrType())
    p[0] = p[2]

def p_pointer_4(p):
    '''pointer : "*" type_qualifier pointer'''
    ptrtype = PtrType()
    ptrtype.set_qualifier( p[2] )
    p[3].set_type( ptrtype )
    p[0] = p[3]

def p_parameter_type_list_1(p):
    '''parameter_type_list : parameter_list'''
    p[0] = p[1]

def p_parameter_type_list_2(p):
    '''parameter_type_list : parameter_list "," "..."'''
    p[0] = p[1]  # default racc result

def p_parameter_list_1(p):
    '''parameter_list : parameter_declaration'''
    p[0] = ParamList( p[1] )

def p_parameter_list_2(p):
    '''parameter_list : parameter_list "," parameter_declaration'''
    p[1].add_param( p[3] )
    # racc は result 未設定時に val[0] を返す。PLY では明示が必要
    p[0] = p[1]


def p_parameter_declaration_1(p):
    '''parameter_declaration : parameter_specifier_list_bracket declaration_specifiers declarator'''
    p[3].set_kind( "PARAMETER" )
    paramdecl = ParamDecl( p[3], p[2], p[1] )
    p[3].check()
    p[0] = paramdecl

def p_parameter_declaration_2(p):
    '''parameter_declaration : declaration_specifiers declarator'''
    Generator.error( "G1001 need specifier for \'$1\'" , p[2].get_name() )
    p[0] = None

def p_parameter_declaration_3(p):
    '''parameter_declaration : declaration_specifiers'''
    if not ((type(p[1]) is VoidType)):
        Generator.error( "G1002 need parameter name"  )
    p[0] = None

def p_parameter_declaration_4(p):
    '''parameter_declaration : parameter_specifier_list_bracket declaration_specifiers'''
    if not ((type(p[2]) is VoidType)):
        Generator.error( "G1003 need parameter name"  )
    p[0] = None

def p_parameter_specifier_list_bracket(p):
    '''parameter_specifier_list_bracket : spec_L parameter_specifier_list spec_R'''
    p[0] = p[2]

def p_parameter_specifier_list_1(p):
    '''parameter_specifier_list : parameter_specifier'''
    p[0] = p[1]

def p_parameter_specifier_list_2(p):
    '''parameter_specifier_list : parameter_specifier_list "," parameter_specifier'''
    p[0] = p[1] + p[3]

def p_parameter_specifier_1(p):
    '''parameter_specifier : IN'''
    p[0] = [ ["IN"]  ]

def p_parameter_specifier_2(p):
    '''parameter_specifier : OUT'''
    p[0] = [ ["OUT"] ]

def p_parameter_specifier_3(p):
    '''parameter_specifier : INOUT'''
    p[0] = [ ["INOUT"] ]

def p_parameter_specifier_4(p):
    '''parameter_specifier : SEND "(" namespace_identifier ")"'''
    p[0] = [ ["SEND",   p[3]] ]

def p_parameter_specifier_5(p):
    '''parameter_specifier : RECEIVE "(" namespace_identifier ")"'''
    p[0] = [ ["RECEIVE",p[3]] ]

def p_parameter_specifier_6(p):
    '''parameter_specifier : STRING'''
    p[0] = [ ["STRING",None] ]

def p_parameter_specifier_7(p):
    '''parameter_specifier : STRING "(" expression ")"'''
    p[0] = [ ["STRING",  p[3]] ]

def p_parameter_specifier_8(p):
    '''parameter_specifier : SIZE_IS "(" expression ")"'''
    p[0] = [ ["SIZE_IS", p[3]] ]

def p_parameter_specifier_9(p):
    '''parameter_specifier : SIZE_IS "(" expression "," constant_expression ")"'''
    p[0] = [ ["SIZE_IS",p[3]], ["MAX_IS", p[5]] ]

def p_parameter_specifier_10(p):
    '''parameter_specifier : COUNT_IS "(" expression ")"'''
    p[0] = [ ["COUNT_IS",p[3]] ]

def p_parameter_specifier_11(p):
    '''parameter_specifier : NULLABLE'''
    p[0] = [ ["NULLABLE"] ]

def p_type_name_1(p):
    '''type_name : type_specifier_qualifier_list'''
    p[0] = p[1]

def p_type_name_2(p):
    '''type_name : type_specifier_qualifier_list abstract_declarator'''
    if p[2]:
        p[2].set_type( p[1] )
        p[0] = p[2]
    else:

        p[0] = p[1]

def p_abstract_declarator_1(p):
    '''abstract_declarator : pointer'''
    p[0] = p[1]

def p_abstract_declarator_2(p):
    '''abstract_declarator : direct_abstract_declarator'''
    p[0] = p[1]

def p_abstract_declarator_3(p):
    '''abstract_declarator : pointer direct_abstract_declarator'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_1(p):
    '''direct_abstract_declarator : "(" abstract_declarator ")"'''
    p[0] = p[2]

def p_direct_abstract_declarator_2(p):
    '''direct_abstract_declarator : "[" "]"'''
    Generator.error( "G1004 impossible array type"  )
    p[0] = None

def p_direct_abstract_declarator_3(p):
    '''direct_abstract_declarator : "[" constant_expression "]"'''
    Generator.error( "G1005 impossible array type"  )
    p[0] = None

def p_direct_abstract_declarator_4(p):
    '''direct_abstract_declarator : direct_abstract_declarator "[" "]"'''
    Generator.error( "G1006 impossible array type"  )
    p[0] = None

def p_direct_abstract_declarator_5(p):
    '''direct_abstract_declarator : direct_abstract_declarator "[" constant_expression "]"'''
    Generator.error( "G1007 impossible array type"  )
    p[0] = None

def p_direct_abstract_declarator_6(p):
    '''direct_abstract_declarator : "(" ")"'''
    Generator.error( "G1008 impossible function type"  )
    p[0] = None

def p_direct_abstract_declarator_7(p):
    '''direct_abstract_declarator : "(" parameter_type_list ")"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_8(p):
    '''direct_abstract_declarator : direct_abstract_declarator "(" ")"'''
    Generator.warning( "W5011 need 'void' for no parameter"  )
    p[1].set_type( FuncType() )
    p[0] = p[1]

def p_direct_abstract_declarator_9(p):
    '''direct_abstract_declarator : direct_abstract_declarator "(" parameter_type_list ")"'''
    p[1].set_type( FuncType( p[3] ) )
    p[0] = p[1]

def p_initializer_1(p):
    '''initializer : constant_expression'''
    p[0] = p[1]

def p_initializer_2(p):
    '''initializer : "{" initializer_list "}"'''
    p[0] = p[2]

def p_initializer_3(p):
    '''initializer : "{" initializer_list "," "}"'''
    p[0] = p[2]

def p_initializer_4(p):
    '''initializer : C_EXP "(" string_literal_list ")"'''
    p[0] = C_EXP( p[3] )

def p_initializer_list_1(p):
    '''initializer_list : initializer'''
    p[0] = [ p[1] ]

def p_initializer_list_2(p):
    '''initializer_list : initializer_list "," initializer'''
    p[1].append(p[3])
    p[0] = p[1]

def p_component_description_1(p):
    '''component_description : component_description specified_statement'''
    p[0] = p[1]  # default racc result

def p_component_description_2(p):
    '''component_description : component_description tool_info'''
    p[0] = p[1]  # default racc result

def p_component_description_3(p):
    '''component_description : empty'''
    p[0] = None

def p_specified_statement_1(p):
    '''specified_statement : statement'''
    p[0] = p[1]

def p_specified_statement_2(p):
    '''specified_statement : spec_L statement_specifier_list spec_R statement'''
    obj = p[4]
    if isinstance(obj, Cell)  or  isinstance(obj, Signature)  or  isinstance(obj, Celltype)  or  isinstance(obj, CompositeCelltype):

        pass
    else:
        Generator.get_statement_specifier()
        Generator.error( "G1009 unexpected specifier"  )

def p_statement_1(p):
    '''statement : typedef'''
    p[0] = p[1]

def p_statement_2(p):
    '''statement : const_statement'''
    p[0] = p[1]

def p_statement_3(p):
    '''statement : namespace'''
    p[0] = p[1]

def p_statement_4(p):
    '''statement : signature'''
    p[0] = p[1]

def p_statement_5(p):
    '''statement : celltype'''
    p[0] = p[1]

def p_statement_6(p):
    '''statement : cell'''
    p[0] = p[1]

def p_statement_7(p):
    '''statement : composite_celltype'''
    p[0] = p[1]

def p_statement_8(p):
    '''statement : enum_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_statement_9(p):
    '''statement : struct_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_statement_10(p):
    '''statement : region'''
    p[0] = p[1]

def p_statement_11(p):
    '''statement : import'''
    p[0] = p[1]

def p_statement_12(p):
    '''statement : import_C'''
    p[0] = p[1]

def p_statement_13(p):
    '''statement : generate_statement'''
    p[0] = p[1]

def p_statement_14(p):
    '''statement : error'''
    p[0] = p[1]

def p_statement_specifier_list_1(p):
    '''statement_specifier_list : statement_specifier'''
    Generator.add_statement_specifier(p[1])

def p_statement_specifier_list_2(p):
    '''statement_specifier_list : statement_specifier_list "," statement_specifier'''
    Generator.add_statement_specifier(p[3])

def p_statement_specifier_1(p):
    '''statement_specifier : ACTIVE'''
    p[0] = ["ACTIVE"]

def p_statement_specifier_2(p):
    '''statement_specifier : ALLOCATOR "(" alloc_list ")"'''
    p[0] = [ "ALLOCATOR", p[3] ]

def p_statement_specifier_3(p):
    '''statement_specifier : CALLBACK'''
    p[0] = [ "CALLBACK" ]

def p_statement_specifier_4(p):
    '''statement_specifier : CONTEXT "(" string_literal_list ")"'''
    p[0] = [ "CONTEXT", p[3].val ]

def p_statement_specifier_5(p):
    '''statement_specifier : DEVIATE'''
    p[0] = [ "DEVIATE" ]

def p_statement_specifier_6(p):
    '''statement_specifier : GENERATE "(" plugin_name "," plugin_arg ")"'''
    p[0] = ["GENERATE", p[3].val, p[5].val]

def p_statement_specifier_7(p):
    '''statement_specifier : ID "(" constant_expression ")"'''
    p[0] = [ "ID", p[3] ]

def p_statement_specifier_8(p):
    '''statement_specifier : IDX_IS_ID'''
    p[0] = ["IDX_IS_ID"]

def p_statement_specifier_9(p):
    '''statement_specifier : PROTOTYPE'''
    p[0] = [ "PROTOTYPE" ]

def p_statement_specifier_10(p):
    '''statement_specifier : PSEUDO_ACTIVE'''
    p[0] = ["PSEUDO_ACTIVE"]

def p_statement_specifier_11(p):
    '''statement_specifier : RESTRICT "(" restrict_list ")"'''
    p[0] = [ "RESTRICT", p[3] ]

def p_statement_specifier_12(p):
    '''statement_specifier : SINGLETON'''
    p[0] = ["SINGLETON"]

def p_statement_specifier_13(p):
    '''statement_specifier : THROUGH "(" port_name "," plugin_name "," plugin_arg ")"'''
    p[0] = [ "THROUGH", p[3], p[5], p[7] ]

def p_alloc_list_1(p):
    '''alloc_list : alloc'''
    p[0] = [ p[1] ]

def p_alloc_list_2(p):
    '''alloc_list : alloc_list "," alloc'''
    p[0] = p[1]
    p[0].append(p[3])

def p_alloc_1(p):
    '''alloc : port_name "." func_name "." param_name "=" initializer'''
    p[0] = [ "NORMAL_ALLOC", p[1], None, p[3], p[5], p[7] ]

def p_alloc_2(p):
    '''alloc : port_name "[" constant_expression "]" "." func_name "." param_name "=" initializer'''
    p[0] = [ "NORMAL_ALLOC", p[1], p[3], p[6], p[8], p[10] ]

def p_restrict_list_1(p):
    '''restrict_list : restrict'''
    p[0] = [p[1]]

def p_restrict_list_2(p):
    '''restrict_list : restrict_list "," restrict'''
    p[0] = p[1]
    p[0].append(p[3])

def p_restrict_1(p):
    '''restrict : port_name "=" "{" region_name_list "}"'''
    p[0] = [ p[1].val, None, p[4] ]

def p_restrict_2(p):
    '''restrict : port_name "." func_name "=" "{" region_name_list "}"'''
    p[0] = [ p[1].val, p[3].val, p[6] ]

def p_region_name_list_1(p):
    '''region_name_list : namespace_identifier'''
    p[0] = [p[1]]

def p_region_name_list_2(p):
    '''region_name_list : region_name_list "," namespace_identifier'''
    p[0] = p[1]
    p[0].append(p[3])

def p_port_name(p):
    '''port_name : IDENTIFIER'''
    p[0] = p[1]

def p_func_name(p):
    '''func_name : IDENTIFIER'''
    p[0] = p[1]

def p_param_name(p):
    '''param_name : IDENTIFIER'''
    p[0] = p[1]

def p_class_name_1(p):
    '''class_name : IDENTIFIER'''
    p[0] = p[1]

def p_class_name_2(p):
    '''class_name : STRING_LITERAL'''
    p[0] = p[1]

def p_const_statement(p):
    '''const_statement : declaration'''
    for decl in p[1]:
        decl.set_kind( "CONSTANT" )
        Namespace.new_const_decl( decl )
        decl.check()

def p_import_C_1(p):
    '''import_C : IMPORT_C "(" STRING_LITERAL ")" ";"'''
    Generator.import_C = True
    Import_C( p[3] )
    Generator.import_C = False

def p_import_C_2(p):
    '''import_C : IMPORT_C "(" STRING_LITERAL "," STRING_LITERAL ")" ";"'''
    Generator.import_C = True
    Import_C( p[3], p[5] )
    Generator.import_C = False

def p_import_1(p):
    '''import : IMPORT "(" STRING_LITERAL ")" ";"'''
    Import( p[3] )

def p_import_2(p):
    '''import : IMPORT "(" AB_STRING_LITERAL ")" ";"'''
    Import( p[3], True )

def p_generate_statement(p):
    '''generate_statement : GENERATE "(" plugin_name "," namespace_identifier "," plugin_arg ")" ";"'''
    Generate( p[3].val, p[5], p[7] )

def p_typedef_1(p):
    '''typedef : TYPEDEF type_specifier_qualifier_list declarator_list mra_typedef_reg ";"'''
    for d in p[3]:
        d.check()

def p_typedef_2(p):
    '''typedef : TYPEDEF "[" typedef_specifier "]" type_specifier_qualifier_list declarator_list mra_typedef_reg2 ";"'''
    for d in p[6]:
        d.check()

def p_typedef_specifier_1(p):
    '''typedef_specifier : STRING'''
    p[0] = p[1]

def p_typedef_specifier_2(p):
    '''typedef_specifier : STRING "(" expression ")"'''
    p[0] = p[1]  # default racc result

def p_declarator_list_1(p):
    '''declarator_list : declarator'''
    p[0] = [ p[1] ]

def p_declarator_list_2(p):
    '''declarator_list : declarator_list "," declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_namespace(p):
    '''namespace : NAMESPACE namespace_NAME "{" statement_list "}" ";"'''
    Generator.set_locale_from_token(p[6])
    p[2].end_of_parse()

def p_namespace_NAME(p):
    '''namespace_NAME : IDENTIFIER'''
    p[0] = Namespace(p[1].val)

def p_statement_list_1(p):
    '''statement_list : specified_statement'''
    p[0] = p[1]

def p_statement_list_2(p):
    '''statement_list : statement_list specified_statement'''
    p[0] = p[1]  # default racc result

def p_namespace_identifier_1(p):
    '''namespace_identifier : namespace_name'''
    p[0] = NamespacePath( p[1].val, False )

def p_namespace_identifier_2(p):
    '''namespace_identifier : "::" namespace_name'''
    p[0] = NamespacePath( p[2].val, True )

def p_namespace_identifier_3(p):
    '''namespace_identifier : namespace_identifier "::" namespace_name'''
    p[0] = p[1].append( p[3].val )

def p_namespace_name(p):
    '''namespace_name : IDENTIFIER'''
    p[0] = p[1]

def p_signature(p):
    '''signature : SIGNATURE signature_NAME "{" function_head_list "}" ";"'''
    Generator.set_locale_from_token(p[6])
    p[0] = p[2].end_of_parse( p[4] )

def p_signature_NAME(p):
    '''signature_NAME : IDENTIFIER'''
    p[0] = Signature( p[1].val )

def p_function_head_list_1(p):
    '''function_head_list : empty'''
    p[0] = NamedList( None, "function" )

def p_function_head_list_2(p):
    '''function_head_list : function_head_list function_head'''
    p[0] = p[1].add_item( p[2] )

def p_function_head_1(p):
    '''function_head : type_specifier_qualifier_list declarator ";"'''
    # p[2]: Decl
    if p[2].is_function:
        p[0] = FuncHead( p[2], p[1], False )
        p[2].set_kind("FUNCHEAD")
        p[2].check()
    else:

        Generator.error( "G1010 Not function"  )
        p[0] = None

def p_function_head_2(p):
    '''function_head : spec_L ONEWAY spec_R type_specifier_qualifier_list declarator ";"'''
    if p[5].is_function:
        p[0] = FuncHead( p[5], p[4], True )
    else:
        Generator.error( "G1011 Not function"  )
        p[0] = None

def p_celltype(p):
    '''celltype : CELLTYPE celltype_NAME "{" celltype_statement_list "}" ";"'''
    # PLY は先読み済み。racc default reduce 時の ';' 位置に合わせる
    Generator.set_locale_from_token(p[6])
    p[2].end_of_parse()
    p[0] = p[2]

def p_celltype_NAME(p):
    '''celltype_NAME : IDENTIFIER'''
    p[0] = Celltype(p[1].val)

def p_celltype_statement_list_1(p):
    '''celltype_statement_list : specified_celltype_statement'''
    p[0] = p[1]

def p_celltype_statement_list_2(p):
    '''celltype_statement_list : celltype_statement_list specified_celltype_statement'''
    p[0] = p[1]  # default racc result

def p_specified_celltype_statement_1(p):
    '''specified_celltype_statement : celltype_statement'''
    if isinstance(p[1], Port):
        Celltype.new_port( p[1] )

def p_specified_celltype_statement_2(p):
    '''specified_celltype_statement : spec_L celltype_statement_specifier_list spec_R celltype_statement'''
    if isinstance(p[4], Port):
        p[4].set_specifier(p[2])
        Celltype.new_port( p[4] )
    else:

        Generator.error( "G1012 $1 : cannot put specifier here" , p[2] )

def p_celltype_statement_1(p):
    '''celltype_statement : port'''
    p[0] = p[1]

def p_celltype_statement_2(p):
    '''celltype_statement : attribute'''
    p[0] = p[1]

def p_celltype_statement_3(p):
    '''celltype_statement : var'''
    p[0] = p[1]

def p_celltype_statement_4(p):
    '''celltype_statement : require'''
    p[0] = p[1]

def p_celltype_statement_5(p):
    '''celltype_statement : factory'''
    p[0] = p[1]

def p_celltype_statement_specifier_list_1(p):
    '''celltype_statement_specifier_list : celltype_statement_specifier'''
    p[0] = [ p[1] ]

def p_celltype_statement_specifier_list_2(p):
    '''celltype_statement_specifier_list : celltype_statement_specifier_list "," celltype_statement_specifier'''
    p[0] = p[1]
    p[0].append(p[3])

def p_celltype_statement_specifier_1(p):
    '''celltype_statement_specifier : INLINE'''
    p[0] = [ "INLINE" ]

def p_celltype_statement_specifier_2(p):
    '''celltype_statement_specifier : ALLOCATOR "(" alloc_list2 ")"'''
    p[0] = [ "ALLOCATOR", p[3] ]

def p_celltype_statement_specifier_3(p):
    '''celltype_statement_specifier : OPTIONAL'''
    p[0] = [ "OPTIONAL" ]

def p_celltype_statement_specifier_4(p):
    '''celltype_statement_specifier : REF_DESC'''
    p[0] = [ "REF_DESC" ]

def p_celltype_statement_specifier_5(p):
    '''celltype_statement_specifier : DYNAMIC'''
    p[0] = [ "DYNAMIC" ]

def p_celltype_statement_specifier_6(p):
    '''celltype_statement_specifier : OMIT'''
    p[0] = [ "OMIT" ]

def p_alloc_list2_1(p):
    '''alloc_list2 : alloc2'''
    p[0] = [ p[1] ]

def p_alloc_list2_2(p):
    '''alloc_list2 : alloc'''
    p[0] = [ p[1] ]

def p_alloc_list2_3(p):
    '''alloc_list2 : alloc_list2 "," alloc2'''
    p[0] = p[1]
    p[0].append(p[3])

def p_alloc_list2_4(p):
    '''alloc_list2 : alloc_list2 "," alloc'''
    p[0] = p[1]
    p[0].append(p[3])

def p_alloc2_1(p):
    '''alloc2 : port_name "." func_name "=" initializer'''
    p[0] = [ "INTERNAL_ALLOC", p[1].val, p[3].val, p[5] ]

def p_alloc2_2(p):
    '''alloc2 : port_name "." func_name "<=" initializer'''
    p[0] = [ "RELAY_ALLOC", p[1].val, p[3].val, p[5] ]

def p_port_1(p):
    '''port : port_type namespace_signature_name port_name ";"'''
    p[0] = Port( p[3].val, p[2], p[1] )

def p_port_2(p):
    '''port : port_type namespace_signature_name port_name "[" "]" ";"'''
    p[0] = Port( p[3].val, p[2], p[1], "[]" )

def p_port_3(p):
    '''port : port_type namespace_signature_name port_name "[" array_size "]" ";"'''
    p[0] = Port(p[3].val, p[2], p[1], p[5])

def p_port_4(p):
    '''port : port_type namespace_signature_name port_name "<=" namespace_identifier "." IDENTIFIER ";"'''
    p[0] = Port( p[3].val, p[2], p[1], None, p[5], p[7].val )

def p_port_type_1(p):
    '''port_type : CALL'''
    p[0] = "CALL"

def p_port_type_2(p):
    '''port_type : ENTRY'''
    p[0] = "ENTRY"

def p_namespace_signature_name(p):
    '''namespace_signature_name : namespace_identifier'''
    p[0] = p[1]

def p_array_size(p):
    '''array_size : constant_expression'''
    p[0] = p[1]

def p_attribute(p):
    '''attribute : ATTRIBUTE "{" attribute_declaration_list "}" ";"'''
    p[0] = None

def p_attribute_declaration_list_1(p):
    '''attribute_declaration_list : attribute_declaration'''
    Celltype.new_attribute( p[1] )

def p_attribute_declaration_list_2(p):
    '''attribute_declaration_list : attribute_declaration_list attribute_declaration'''
    Celltype.new_attribute( p[2] )

def p_attribute_declaration_1(p):
    '''attribute_declaration : declaration'''
    for i in p[1]:
        i.set_kind( "ATTRIBUTE" )
        i.check()
        p[0] = p[1]

def p_attribute_declaration_2(p):
    '''attribute_declaration : spec_L attribute_specifier spec_R declaration'''
    for i in p[4]:
        i.set_kind( "ATTRIBUTE" )
        i.set_specifier_list( [p[2]] )
        i.check()
        p[0] = p[4]

def p_attribute_specifier_1(p):
    '''attribute_specifier : OMIT'''
    p[0] = ["OMIT"]

def p_attribute_specifier_2(p):
    '''attribute_specifier : SIZE_IS "(" expression ")"'''
    p[0] = ["SIZE_IS",p[3]]

def p_attribute_specifier_3(p):
    '''attribute_specifier : CHOICE "=" "{" choice_list "}"'''
    p[0] = ["CHOICE",p[4]]

def p_choice_list_1(p):
    '''choice_list : choice_list "," choice_element'''
    p[0] = p[1]
    p[0].append(p[3])

def p_choice_list_2(p):
    '''choice_list : choice_element'''
    p[0] = [ p[1] ]

def p_choice_element(p):
    '''choice_element : STRING_LITERAL'''
    p[0] = p[1]

def p_var(p):
    '''var : VAR "{" var_declaration_list "}" ";"'''
    p[0] = None

def p_var_declaration_list_1(p):
    '''var_declaration_list : var_declaration'''
    Celltype.new_var( p[1] )

def p_var_declaration_list_2(p):
    '''var_declaration_list : var_declaration_list var_declaration'''
    Celltype.new_var( p[2] )

def p_var_declaration_1(p):
    '''var_declaration : declaration'''
    for i in p[1]:
        i.set_kind( "VAR" )
        i.check()
    p[0] = p[1]

def p_var_declaration_2(p):
    '''var_declaration : spec_L var_specifier spec_R declaration'''
    for i in p[4]:
        i.set_kind( "VAR" )
        i.set_specifier_list( [p[2]] )
        i.check()
        p[0] = p[4]

def p_var_specifier(p):
    '''var_specifier : SIZE_IS "(" expression ")"'''
    p[0] = ["SIZE_IS",p[3]]

def p_require_1(p):
    '''require : REQUIRE namespace_identifier "." port_name ";"'''
    Celltype.new_require( p[2], p[4] )

def p_require_2(p):
    '''require : REQUIRE port_name "=" namespace_identifier "." port_name ";"'''
    Celltype.new_require( p[4], p[6], p[2].val )

def p_factory(p):
    '''factory : factory_head "{" factory_function_list "}" ";"'''
    p[0] = p[1]  # default racc result

def p_factory_head_1(p):
    '''factory_head : FACTORY'''
    Factory.set_f_celltype( False )

def p_factory_head_2(p):
    '''factory_head : CTFACTORY'''
    Factory.set_f_celltype( True )

def p_factory_function_list_1(p):
    '''factory_function_list : empty'''
    p[0] = None

def p_factory_function_list_2(p):
    '''factory_function_list : factory_function_list factory_function'''
    p[0] = p[1]  # default racc result

def p_factory_function_1(p):
    '''factory_function : factory_function_name "(" constant_expression "," constant_expression ")" ";"'''
    Factory( p[1].val, p[3], p[5], None    )

def p_factory_function_2(p):
    '''factory_function : factory_function_name "(" constant_expression "," constant_expression "," arg_list ")" ";"'''
    Factory( p[1].val, p[3], p[5], p[7] )

def p_factory_function_name(p):
    '''factory_function_name : IDENTIFIER'''
    p[0] = p[1]

def p_arg_list_1(p):
    '''arg_list : IDENTIFIER'''
    p[0] = [ [ "IDENTIFIER", p[1].val ] ]

def p_arg_list_2(p):
    '''arg_list : arg_list "," IDENTIFIER'''
    p[0] = p[1]
    p[0].append([ "IDENTIFIER", p[3].val ])

def p_arg_list_3(p):
    '''arg_list : STRING_LITERAL'''
    p[0] = [ [ "STRING_LITERAL", p[1].val ] ]

def p_arg_list_4(p):
    '''arg_list : arg_list "," STRING_LITERAL'''
    p[0] = p[1]
    p[0].append([ "STRING_LITERAL", p[3].val ])

def p_cell_1(p):
    '''cell : CELL namespace_celltype_NAME cell_NAME "{" mra_3 join_list "}" ";"'''
    Generator.set_locale_from_token(p[8])
    p[0] = Cell.end_of_parse(True)

def p_cell_2(p):
    '''cell : CELL namespace_celltype_NAME cell_NAME ";"'''
    Generator.set_locale_from_token(p[4])
    p[0] = Cell.end_of_parse(False)

def p_namespace_celltype_NAME(p):
    '''namespace_celltype_NAME : namespace_identifier'''
    p[0] = Cell(p[1])

def p_cell_NAME(p):
    '''cell_NAME : IDENTIFIER'''
    p[0] = Cell.set_name(p[1].val)

def p_join_list_1(p):
    '''join_list : empty'''
    p[0] = None

def p_join_list_2(p):
    '''join_list : join_list specified_join'''
    p[0] = p[1]  # default racc result

def p_join_list_3(p):
    '''join_list : join_list reverse_join'''
    p[0] = p[1]  # default racc result

def p_specified_join_1(p):
    '''specified_join : spec_L join_specifier_list spec_R join'''
    p[4].set_specifier_list( p[2] )

def p_specified_join_2(p):
    '''specified_join : join'''
    p[1].set_specifier_list( [] )

def p_join_specifier_list_1(p):
    '''join_specifier_list : join_specifier_list "," join_specifier'''
    p[0] = p[1]
    p[0].append(p[3])

def p_join_specifier_list_2(p):
    '''join_specifier_list : join_specifier'''
    p[0] = [p[1]]

def p_join_specifier(p):
    '''join_specifier : THROUGH "(" plugin_name "," plugin_arg ")"'''
    p[0] = [ "THROUGH", p[3], p[5] ]

def p_plugin_name(p):
    '''plugin_name : IDENTIFIER'''
    p[0] = p[1]

def p_plugin_arg(p):
    '''plugin_arg : string_literal_list'''
    p[0] = p[1]

def p_join_1(p):
    '''join : cae_name "[" "]" "=" expression ";"'''
    p[0] = Join( p[1].val,  -1, p[5] )
    Cell.new_join( p[0], True )

def p_join_2(p):
    '''join : cae_name "[" array_index "]" "=" expression ";"'''
    p[0] = Join( p[1].val, p[3], p[6] )
    Cell.new_join( p[0], True )

def p_join_3(p):
    '''join : cae_name "=" initializer ";"'''
    p[0] = Join( p[1].val, None, p[3] )
    Cell.new_join( p[0], True )

def p_join_4(p):
    '''join : cae_name "=" COMPOSITE "." IDENTIFIER ";"'''
    p[0] = Join( p[1].val, None, [ "COMPOSITE", p[5] ] )
    Cell.new_join( p[0], True )

def p_cae_name(p):
    '''cae_name : IDENTIFIER'''
    p[0] = p[1]

def p_reverse_join_1(p):
    '''reverse_join : cae_name "<=" namespace_identifier "." port_name ";"'''
    rj = ReverseJoin( p[1].val, None, p[3], p[5].val )
    Cell.new_reverse_join( rj )

def p_reverse_join_2(p):
    '''reverse_join : cae_name "<=" namespace_identifier "." port_name "[" expression "]" ";"'''
    rj = ReverseJoin( p[1].val, None, p[3], p[5].val, p[7] )
    Cell.new_reverse_join( rj )

def p_reverse_join_3(p):
    '''reverse_join : cae_name "[" array_index "]" "<=" namespace_identifier "." port_name ";"'''
    rj = ReverseJoin( p[1].val, p[3], p[6], p[8].val )
    Cell.new_reverse_join( rj )

def p_reverse_join_4(p):
    '''reverse_join : cae_name "[" array_index "]" "<=" namespace_identifier "." port_name "[" expression "]" ";"'''
    rj = ReverseJoin( p[1].val, p[3], p[6], p[8].val, p[10] )
    Cell.new_reverse_join( rj )

def p_array_index(p):
    '''array_index : constant_expression'''
    p[0] = p[1]

def p_composite_celltype(p):
    '''composite_celltype : COMPOSITE composite_celltype_NAME "{" composite_celltype_statement_list "}" ";"'''
    Generator.set_locale_from_token(p[6])
    CompositeCelltype.end_of_parse()
    p[0] = p[2]

def p_composite_celltype_NAME(p):
    '''composite_celltype_NAME : IDENTIFIER'''
    p[0] = CompositeCelltype(p[1].val)

def p_composite_celltype_statement_list_1(p):
    '''composite_celltype_statement_list : specified_composite_celltype_statement'''
    p[0] = p[1]

def p_composite_celltype_statement_list_2(p):
    '''composite_celltype_statement_list : composite_celltype_statement_list specified_composite_celltype_statement'''
    p[0] = p[1]  # default racc result

def p_specified_composite_celltype_statement_1(p):
    '''specified_composite_celltype_statement : composite_celltype_statement'''
    if isinstance(p[1], Port):
        CompositeCelltype.new_port( p[1] )

def p_specified_composite_celltype_statement_2(p):
    '''specified_composite_celltype_statement : spec_L composite_celltype_statement_specifier_list spec_R composite_celltype_statement'''
    if isinstance(p[4], Port):



        p[4].set_specifier( Generator.get_statement_specifier() )
        CompositeCelltype.new_port( p[4] )
    elif isinstance(p[4], Cell):

        pass
    else:
        Generator.get_statement_specifier()
        Generator.error( "G1013 unexpected specifier"  )

def p_composite_celltype_statement_1(p):
    '''composite_celltype_statement : composite_port'''
    p[0] = p[1]

def p_composite_celltype_statement_2(p):
    '''composite_celltype_statement : composite_attribute'''
    p[0] = p[1]

def p_composite_celltype_statement_3(p):
    '''composite_celltype_statement : internal_cell'''
    p[0] = p[1]

def p_composite_celltype_statement_4(p):
    '''composite_celltype_statement : export_join'''
    p[0] = p[1]

def p_composite_celltype_statement_specifier_list_1(p):
    '''composite_celltype_statement_specifier_list : composite_celltype_statement_specifier'''
    Generator.add_statement_specifier(p[1])
    p[0] = [ p[1] ]

def p_composite_celltype_statement_specifier_list_2(p):
    '''composite_celltype_statement_specifier_list : composite_celltype_statement_specifier_list "," composite_celltype_statement_specifier'''
    Generator.add_statement_specifier(p[3])
    p[1].append(p[3])
    p[0] = p[1]

def p_composite_celltype_statement_specifier_1(p):
    '''composite_celltype_statement_specifier : ALLOCATOR "(" alloc_list2 ")"'''
    p[0] = [ "ALLOCATOR", p[3] ]

def p_composite_celltype_statement_specifier_2(p):
    '''composite_celltype_statement_specifier : OMIT'''
    p[0] = [ "OMIT" ]

def p_composite_celltype_statement_specifier_3(p):
    '''composite_celltype_statement_specifier : OPTIONAL'''
    p[0] = [ "OPTIONAL" ]

def p_composite_celltype_statement_specifier_4(p):
    '''composite_celltype_statement_specifier : REF_DESC'''
    p[0] = [ "REF_DESC" ]

def p_composite_celltype_statement_specifier_5(p):
    '''composite_celltype_statement_specifier : DYNAMIC'''
    p[0] = [ "DYNAMIC" ]

def p_composite_port(p):
    '''composite_port : port'''
    # CompositeCelltype.new_port( p[1] )
    p[0] = p[1]

def p_composite_attribute(p):
    '''composite_attribute : ATTRIBUTE "{" composite_attribute_declaration_list "}" ";"'''
    p[0] = None

def p_composite_attribute_declaration_list_1(p):
    '''composite_attribute_declaration_list : attribute_declaration'''
    CompositeCelltype.new_attribute( p[1] )

def p_composite_attribute_declaration_list_2(p):
    '''composite_attribute_declaration_list : composite_attribute_declaration_list attribute_declaration'''
    CompositeCelltype.new_attribute( p[2] )

def p_internal_cell_1(p):
    '''internal_cell : CELL internal_namespace_celltype_NAME internal_cell_NAME "{" mra_4 internal_join_list "}" ";"'''
    Generator.set_locale_from_token(p[8])
    p[0] = Cell.end_of_parse(True)

def p_internal_cell_2(p):
    '''internal_cell : CELL internal_namespace_celltype_NAME internal_cell_NAME ";"'''
    Generator.set_locale_from_token(p[4])
    p[0] = Cell.end_of_parse(False)

def p_internal_namespace_celltype_NAME(p):
    '''internal_namespace_celltype_NAME : namespace_identifier'''
    Cell(p[1],True)

def p_internal_cell_NAME(p):
    '''internal_cell_NAME : IDENTIFIER'''
    Cell.set_name(p[1].val)

def p_internal_join_list_1(p):
    '''internal_join_list : empty'''
    p[0] = None

def p_internal_join_list_2(p):
    '''internal_join_list : internal_join_list specified_join'''
    p[0] = p[1]  # default racc result

def p_internal_join_list_3(p):
    '''internal_join_list : internal_join_list external_join'''
    p[0] = p[1]  # default racc result

def p_internal_join_list_4(p):
    '''internal_join_list : internal_join_list reverse_join'''
    p[0] = p[1]  # default racc result

def p_external_join_1(p):
    '''external_join : internal_cell_elem_name "=>" COMPOSITE "." export_name ";"'''
    Cell.external_join( p[1].val, p[5].val, True )

def p_external_join_2(p):
    '''external_join : internal_cell_elem_name "=>" export_name ";"'''
    Cell.external_join( p[1].val, p[3].val, False )

def p_export_join_1(p):
    '''export_join : export_name "=>" internal_ref_cell_name "." internal_cell_elem_name ";"'''
    CompositeCelltype.new_join( p[1].val,
    p[3].val, p[5].val, "ENTRY" )

def p_export_join_2(p):
    '''export_join : COMPOSITE "." export_name "=>" internal_ref_cell_name "." internal_cell_elem_name ";"'''
    CompositeCelltype.new_join( p[3].val,
    p[5].val, p[7].val, "ENTRY" )

def p_export_name(p):
    '''export_name : IDENTIFIER'''
    p[0] = p[1]

def p_internal_ref_cell_name(p):
    '''internal_ref_cell_name : IDENTIFIER'''
    p[0] = p[1]

def p_internal_cell_elem_name(p):
    '''internal_cell_elem_name : IDENTIFIER'''
    p[0] = p[1]

def p_region_1(p):
    '''region : spec_L region_specifier_list spec_R REGION region_NAME "{" region_statement "}" ";"'''
    Generator.set_locale_from_token(p[9])
    Region.end_of_parse()

def p_region_2(p):
    '''region : REGION region_NAME "{" region_statement "}" ";"'''
    Generator.set_locale_from_token(p[6])
    Region.end_of_parse()

def p_region_specifier_list_1(p):
    '''region_specifier_list : region_specifier'''
    p[0] = p[1]

def p_region_specifier_list_2(p):
    '''region_specifier_list : region_specifier_list "," region_specifier'''
    p[0] = p[1]  # default racc result

def p_region_specifier_1(p):
    '''region_specifier : IN_THROUGH "(" plugin_name "," plugin_arg ")"'''
    Region.new_in_through( p[3].val, p[5].val )

def p_region_specifier_2(p):
    '''region_specifier : IN_THROUGH "(" ")"'''
    Region.new_in_through()

def p_region_specifier_3(p):
    '''region_specifier : OUT_THROUGH "(" plugin_name "," plugin_arg ")"'''
    Region.new_out_through( p[3].val, p[5].val )

def p_region_specifier_4(p):
    '''region_specifier : OUT_THROUGH "(" ")"'''
    Region.new_out_through()

def p_region_specifier_5(p):
    '''region_specifier : TO_THROUGH "(" namespace_region_NAME "," plugin_name "," plugin_arg ")"'''
    Region.new_to_through( p[3], p[5].val, p[7].val )

def p_region_specifier_6(p):
    '''region_specifier : TO_THROUGH "(" namespace_region_NAME ")"'''
    Region.new_to_through( p[3], None, None )

def p_region_specifier_7(p):
    '''region_specifier : FROM_THROUGH "(" namespace_region_NAME "," plugin_name "," plugin_arg ")"'''
    Region.new_from_through( p[3], p[5].val, p[7].val )

def p_region_specifier_8(p):
    '''region_specifier : FROM_THROUGH "(" namespace_region_NAME ")"'''
    Region.new_from_through( p[3], None, None )

def p_region_specifier_9(p):
    '''region_specifier : NODE'''
    Region.set_type( "NODE" )

def p_region_specifier_10(p):
    '''region_specifier : LINKUNIT'''
    Region.set_type( "LINKUNIT" )

def p_region_specifier_11(p):
    '''region_specifier : DOMAIN "(" domain_type "," domain_name ")"'''
    Region.set_domain( p[3].val, p[5] )

def p_region_specifier_12(p):
    '''region_specifier : CLASS "(" class_type "," class_name ")"'''
    Region.set_class( p[3].val, p[5] )

def p_region_NAME(p):
    '''region_NAME : IDENTIFIER'''
    p[0] = Region( p[1].val )

def p_domain_type(p):
    '''domain_type : IDENTIFIER'''
    p[0] = p[1]

def p_domain_name(p):
    '''domain_name : STRING_LITERAL'''
    p[0] = p[1]

def p_class_type(p):
    '''class_type : IDENTIFIER'''
    p[0] = p[1]

def p_region_statement_1(p):
    '''region_statement : empty'''
    p[0] = None

def p_region_statement_2(p):
    '''region_statement : region_statement region_cell'''
    p[0] = p[1]  # default racc result

def p_region_statement_3(p):
    '''region_statement : region_statement region'''
    p[0] = p[1]  # default racc result

def p_region_cell_1(p):
    '''region_cell : cell'''
    p[0] = p[1]

def p_region_cell_2(p):
    '''region_cell : spec_L statement_specifier_list spec_R cell'''
    obj = p[4]
    if isinstance(obj, Cell):
        pass
    else:
        Generator.get_statement_specifier()
        Generator.error( "G9999 unexpected specifier"  )

def p_namespace_region_NAME(p):
    '''namespace_region_NAME : IDENTIFIER'''
    p[0] = [ p[1].val ]

def p_spec_L(p):
    '''spec_L : "["'''
    Generator.current().set_in_specifier()

def p_spec_R(p):
    '''spec_R : "]"'''
    Generator.current().unset_in_specifier()

def p_tool_info(p):
    '''tool_info : TOOL_INFO "(" "JSON_string" ")" "JSON_object"'''
    TOOL_INFO( _json_to_sym(p[3]), p[5] )

def p_JSON_object(p):
    '''JSON_object : "{" "JSON_property_list" "}"'''
    p[0] = p[2]

def p_JSON_property_list_1(p):
    '''JSON_property_list : "JSON_string" ":" "JSON_value"'''
    p[0] = {_json_to_sym(p[1]): (p[3])}

def p_JSON_property_list_2(p):
    '''JSON_property_list : "JSON_property_list" "," "JSON_string" ":" "JSON_value"'''
    p[1][ _json_to_sym(p[3]) ] = p[5]
    p[0] = p[1]

def p_JSON_value_1(p):
    '''JSON_value : "JSON_string"'''
    p[0] = p[1] if isinstance(p[1], str) else (
        p[1].val if hasattr(p[1], "val") and isinstance(p[1].val, str) else str(p[1])
    )

def p_JSON_value_2(p):
    '''JSON_value : "JSON_number"'''
    p[0] = p[1]

def p_JSON_value_3(p):
    '''JSON_value : "JSON_object"'''
    p[0] = p[1]

def p_JSON_value_4(p):
    '''JSON_value : "JSON_array"'''
    p[0] = p[1]

def p_JSON_value_5(p):
    '''JSON_value : TRUE'''
    p[0] =p[1].val

def p_JSON_value_6(p):
    '''JSON_value : FALSE'''
    p[0] =p[1].val

def p_JSON_array_1(p):
    '''JSON_array : "[" "JSON_array_list" "]"'''
    p[0] = p[2]

def p_JSON_array_2(p):
    '''JSON_array : "[" "]"'''
    p[0] = []

def p_JSON_array_list_1(p):
    '''JSON_array_list : "JSON_value"'''
    p[0] = [ p[1] ]

def p_JSON_array_list_2(p):
    '''JSON_array_list : "JSON_array_list" "," "JSON_value"'''
    p[1].append(p[3])
    p[0] = p[1]

def p_JSON_string(p):
    '''JSON_string : STRING_LITERAL'''
    p[0] = re.sub(r'\"(.*)\"', "\\1", p[1].val)

def p_JSON_number_1(p):
    '''JSON_number : INTEGER_CONSTANT'''
    p[0] = _json_token_num(p[1])

def p_JSON_number_2(p):
    '''JSON_number : FLOATING_CONSTANT'''
    p[0] = _json_token_float(p[1])

def p_JSON_number_3(p):
    '''JSON_number : "-" INTEGER_CONSTANT'''
    p[0] = - _json_token_num(p[1])

def p_JSON_number_4(p):
    '''JSON_number : "-" FLOATING_CONSTANT'''
    p[0] = - _json_token_float(p[1])

def p_JSON_number_5(p):
    '''JSON_number : "+" INTEGER_CONSTANT'''
    p[0] = _json_token_num(p[1])

def p_JSON_number_6(p):
    '''JSON_number : "+" FLOATING_CONSTANT'''
    p[0] = _json_token_float(p[1])

def p_error(p):
    pass
