# -*- coding: utf-8 -*-
# AUTO-GENERATED by tools/racc_to_ply.py — review FIXME
# from ../tecsgen/tecsgen/tecslib/core/C_parser.y.rb rule section

import re

def p_empty(p):
    'empty :'
    pass

def p_mra_1(p):
    '''mra_1 :'''
    StructType.set_define( True )

def p_mra_2(p):
    '''mra_2 :'''
    p[0] = CStructType()
    StructType.set_define( True )

def p_all(p):
    '''all : C_parser'''
    p[0] = p[1]

def p_primary_expression_1(p):
    '''primary_expression : namespace_identifier'''
    p[0] = [ "IDENTIFIER", p[1] ]

def p_primary_expression_2(p):
    '''primary_expression : INTEGER_CONSTANT'''
    p[0] = [ "INTEGER_CONSTANT", p[1] ]

def p_primary_expression_3(p):
    '''primary_expression : FLOATING_CONSTANT'''
    p[0] = [ "FLOATING_CONSTANT", p[1] ]

def p_primary_expression_4(p):
    '''primary_expression : OCTAL_CONSTANT'''
    p[0] = [ "OCTAL_CONSTANT", p[1] ]

def p_primary_expression_5(p):
    '''primary_expression : HEX_CONSTANT'''
    p[0] = [ "HEX_CONSTANT", p[1] ]

def p_primary_expression_6(p):
    '''primary_expression : CHARACTER_LITERAL'''
    p[0] = [ "CHARACTER_LITERAL", p[1] ]

def p_primary_expression_7(p):
    '''primary_expression : string_literal_list'''
    p[0] = [ "STRING_LITERAL_LIST", p[1] ]

def p_primary_expression_8(p):
    '''primary_expression : "(" expression ")"'''
    p[0] = [ "PARENTHESES", p[2].get_elements() ]

def p_string_literal_list_1(p):
    '''string_literal_list : STRING_LITERAL'''
    p[0] = [p[1]]

def p_string_literal_list_2(p):
    '''string_literal_list : string_literal_list STRING_LITERAL'''
    p[0] = p[1]
    p[0].append(p[2])

def p_postfix_expression_1(p):
    '''postfix_expression : primary_expression'''
    p[0] = p[1]

def p_postfix_expression_2(p):
    '''postfix_expression : postfix_expression "[" expression "]"'''
    p[0] = [ "OP_SUBSC", p[1], p[3] ]

def p_postfix_expression_3(p):
    '''postfix_expression : postfix_expression "(" ")"'''
    p[0] = p[1]  # default racc result

def p_postfix_expression_4(p):
    '''postfix_expression : postfix_expression "(" argument_list ")"'''
    p[0] = p[1]  # default racc result

def p_postfix_expression_5(p):
    '''postfix_expression : postfix_expression type_qualifier "(" argument_list ")"'''
    p[0] = p[1]  # default racc result

def p_postfix_expression_6(p):
    '''postfix_expression : postfix_expression "." IDENTIFIER'''
    p[0] = [ "OP_DOT", p[1], p[3] ]

def p_postfix_expression_7(p):
    '''postfix_expression : postfix_expression "->" IDENTIFIER'''
    p[0] = [ "OP_REF", p[1], p[3] ]

def p_postfix_expression_8(p):
    '''postfix_expression : postfix_expression "++"'''
    p[0] = p[1]

def p_postfix_expression_9(p):
    '''postfix_expression : postfix_expression "--"'''
    p[0] = p[1]

def p_postfix_expression_10(p):
    '''postfix_expression : "(" type_name ")" "{" initializer_list "}"'''
    p[0] = p[1]  # default racc result

def p_postfix_expression_11(p):
    '''postfix_expression : "(" type_name ")" "{" initializer_list "," "}"'''
    p[0] = p[1]  # default racc result

def p_argument_list_1(p):
    '''argument_list : assignment_expression'''
    p[0] = p[1]

def p_argument_list_2(p):
    '''argument_list : argument_list "," assignment_expression'''
    p[0] = p[1]  # default racc result

def p_unary_expression_1(p):
    '''unary_expression : postfix_expression'''
    p[0] = p[1]

def p_unary_expression_2(p):
    '''unary_expression : unary_operator cast_expression'''
    p[0] = [ p[1], p[2] ]

def p_unary_expression_3(p):
    '''unary_expression : SIZEOF unary_expression'''
    p[0] = [ "OP_SIZEOF_EXPR", p[2] ]

def p_unary_expression_4(p):
    '''unary_expression : SIZEOF "(" type_name ")"'''
    p[0] = [ "OP_SIZEOF_TYPE", p[3] ]

def p_unary_expression_5(p):
    '''unary_expression : "++" unary_expression'''
    p[0] = p[2]

def p_unary_expression_6(p):
    '''unary_expression : "--" unary_expression'''
    p[0] = p[2]

def p_unary_operator_1(p):
    '''unary_operator : "&"'''
    p[0] = "OP_U_AMP"

def p_unary_operator_2(p):
    '''unary_operator : "*"'''
    p[0] = "OP_U_ASTER"

def p_unary_operator_3(p):
    '''unary_operator : "+"'''
    p[0] = "OP_U_PLUS"

def p_unary_operator_4(p):
    '''unary_operator : "-"'''
    p[0] = "OP_U_MINUS"

def p_unary_operator_5(p):
    '''unary_operator : "~"'''
    p[0] = "OP_U_TILDE"

def p_unary_operator_6(p):
    '''unary_operator : "!"'''
    p[0] = "OP_U_EXCLAM"

def p_cast_expression_1(p):
    '''cast_expression : unary_expression'''
    p[0] = p[1]

def p_cast_expression_2(p):
    '''cast_expression : "(" type_name ")" cast_expression'''
    p[0] = [ "CAST", p[2], p[4] ]

def p_multiplicative_expression_1(p):
    '''multiplicative_expression : cast_expression'''
    p[0] = p[1]

def p_multiplicative_expression_2(p):
    '''multiplicative_expression : multiplicative_expression "*" cast_expression'''
    p[0] = [ "OP_MULT", p[1], p[3] ]

def p_multiplicative_expression_3(p):
    '''multiplicative_expression : multiplicative_expression "/" cast_expression'''
    p[0] = [ "OP_DIV", p[1], p[3] ]

def p_multiplicative_expression_4(p):
    '''multiplicative_expression : multiplicative_expression "%" cast_expression'''
    p[0] = [ "OP_REMAIN", p[1], p[3] ]

def p_additive_expression_1(p):
    '''additive_expression : multiplicative_expression'''
    p[0] = p[1]

def p_additive_expression_2(p):
    '''additive_expression : additive_expression "+" multiplicative_expression'''
    p[0] = [ "OP_ADD", p[1], p[3] ]

def p_additive_expression_3(p):
    '''additive_expression : additive_expression "-" multiplicative_expression'''
    p[0] = [ "OP_SUB", p[1], p[3] ]

def p_shift_expression_1(p):
    '''shift_expression : additive_expression'''
    p[0] = p[1]

def p_shift_expression_2(p):
    '''shift_expression : shift_expression "<<" additive_expression'''
    p[0] = [ "OP_LSFT", p[1], p[3] ]

def p_shift_expression_3(p):
    '''shift_expression : shift_expression ">>" additive_expression'''
    p[0] = [ "OP_RSFT", p[1], p[3] ]

def p_relational_expression_1(p):
    '''relational_expression : shift_expression'''
    p[0] = p[1]

def p_relational_expression_2(p):
    '''relational_expression : relational_expression "<" shift_expression'''
    p[0] = [ "OP_LT", p[1], p[3] ]

def p_relational_expression_3(p):
    '''relational_expression : relational_expression ">" shift_expression'''
    p[0] = [ "OP_GT", p[1], p[3] ]

def p_relational_expression_4(p):
    '''relational_expression : relational_expression "<=" shift_expression'''
    p[0] = [ "OP_LE", p[1], p[3] ]

def p_relational_expression_5(p):
    '''relational_expression : relational_expression ">=" shift_expression'''
    p[0] = [ "OP_GE", p[1], p[3] ]

def p_equality_expression_1(p):
    '''equality_expression : relational_expression'''
    p[0] = p[1]

def p_equality_expression_2(p):
    '''equality_expression : equality_expression "==" relational_expression'''
    p[0] = [ "OP_EQ", p[1], p[3] ]

def p_equality_expression_3(p):
    '''equality_expression : equality_expression "!=" relational_expression'''
    p[0] = [ "OP_NE", p[1], p[3] ]

def p_and_expression_1(p):
    '''and_expression : equality_expression'''
    p[0] = p[1]

def p_and_expression_2(p):
    '''and_expression : and_expression "&" equality_expression'''
    p[0] = [ "OP_AND", p[1], p[3] ]

def p_exclusive_or_expression_1(p):
    '''exclusive_or_expression : and_expression'''
    p[0] = p[1]

def p_exclusive_or_expression_2(p):
    '''exclusive_or_expression : exclusive_or_expression "^" and_expression'''
    p[0] = [ "OP_EOR", p[1], p[3] ]

def p_inclusive_or_expression_1(p):
    '''inclusive_or_expression : exclusive_or_expression'''
    p[0] = p[1]

def p_inclusive_or_expression_2(p):
    '''inclusive_or_expression : inclusive_or_expression "|" exclusive_or_expression'''
    p[0] = [ "OP_OR", p[1], p[3] ]

def p_logical_and_expression_1(p):
    '''logical_and_expression : inclusive_or_expression'''
    p[0] = p[1]

def p_logical_and_expression_2(p):
    '''logical_and_expression : logical_and_expression "&&" inclusive_or_expression'''
    p[0] = [ "OP_LAND", p[1], p[3] ]

def p_logical_or_expression_1(p):
    '''logical_or_expression : logical_and_expression'''
    p[0] = p[1]

def p_logical_or_expression_2(p):
    '''logical_or_expression : logical_or_expression "||" logical_and_expression'''
    p[0] = [ "OP_LOR", p[1], p[3] ]

def p_conditional_expression_1(p):
    '''conditional_expression : logical_or_expression'''
    p[0] = p[1]

def p_conditional_expression_2(p):
    '''conditional_expression : logical_or_expression "?" expression ":" conditional_expression'''
    p[0] = [ "OP_CEX", p[1], p[3].get_elements(), p[5] ]

def p_assignment_expression_1(p):
    '''assignment_expression : conditional_expression'''
    p[0] = p[1]

def p_assignment_expression_2(p):
    '''assignment_expression : unary_expression assignment_operator assignment_expression'''
    p[0] = p[1]  # default racc result

def p_assignment_operator_1(p):
    '''assignment_operator : "="'''
    p[0] = p[1]

def p_assignment_operator_2(p):
    '''assignment_operator : "+="'''
    p[0] = p[1]

def p_assignment_operator_3(p):
    '''assignment_operator : "-="'''
    p[0] = p[1]

def p_assignment_operator_4(p):
    '''assignment_operator : "*="'''
    p[0] = p[1]

def p_assignment_operator_5(p):
    '''assignment_operator : "/="'''
    p[0] = p[1]

def p_assignment_operator_6(p):
    '''assignment_operator : "%="'''
    p[0] = p[1]

def p_assignment_operator_7(p):
    '''assignment_operator : "<<="'''
    p[0] = p[1]

def p_assignment_operator_8(p):
    '''assignment_operator : ">>="'''
    p[0] = p[1]

def p_assignment_operator_9(p):
    '''assignment_operator : "&="'''
    p[0] = p[1]

def p_assignment_operator_10(p):
    '''assignment_operator : "|="'''
    p[0] = p[1]

def p_assignment_operator_11(p):
    '''assignment_operator : "^="'''
    p[0] = p[1]

def p_expression_1(p):
    '''expression : assignment_expression'''
    p[0] = Expression( p[1] )


def p_expression_2(p):
    '''expression : expression "," assignment_expression'''
    p[0] = Expression( p[3] )

def p_constant_expression(p):
    '''constant_expression : conditional_expression'''
    p[0] = Expression( p[1] )

    #			res = p[0].eval_const( None )







def p_declaration(p):
    '''declaration : declaration_specifiers init_declarator_list ";"'''
    p[0] = p[1]  # default racc result

def p_declaration_specifiers_1(p):
    '''declaration_specifiers : storage_class'''
    p[0] = CIntType( -3 )

def p_declaration_specifiers_2(p):
    '''declaration_specifiers : type_specifier'''
    p[0] = p[1]

def p_declaration_specifiers_3(p):
    '''declaration_specifiers : type_qualifier'''
    p[0] = CIntType( -3 )
    p[0].set_qualifier(p[1])

def p_declaration_specifiers_4(p):
    '''declaration_specifiers : storage_class declaration_specifiers'''
    p[0] = p[2]

def p_declaration_specifiers_5(p):
    '''declaration_specifiers : type_specifier declaration_specifiers'''
    p[0] = p[2].merge(p[1])

def p_declaration_specifiers_6(p):
    '''declaration_specifiers : type_qualifier declaration_specifiers'''
    p[2].set_qualifier(p[1])
    p[0] = p[2]

def p_declaration_specifiers_7(p):
    '''declaration_specifiers : function_specifier'''
    p[0] = p[1]

def p_declaration_specifiers_8(p):
    '''declaration_specifiers : function_specifier declaration_specifiers'''
    p[0] = p[1]  # default racc result

def p_init_declarator_list_1(p):
    '''init_declarator_list : init_declarator'''
    p[0] = [p[1]]

def p_init_declarator_list_2(p):
    '''init_declarator_list : init_declarator_list "," init_declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_init_declarator_1(p):
    '''init_declarator : declarator'''
    p[0] = p[1]

def p_init_declarator_2(p):
    '''init_declarator : declarator "=" initializer'''
    p[1].set_initializer( p[3] )
    p[0] = p[1]

def p_storage_class_1(p):
    '''storage_class : EXTERN'''
    p[0] = p[1]

def p_storage_class_2(p):
    '''storage_class : STATIC'''
    p[0] = p[1]

def p_storage_class_3(p):
    '''storage_class : AUTO'''
    p[0] = p[1]

def p_storage_class_4(p):
    '''storage_class : REGISTER'''
    p[0] = p[1]

def p_type_specifier_1(p):
    '''type_specifier : VOID'''
    C_parser.current().set_no_type_name(True); p[0] = CVoidType()

def p_type_specifier_2(p):
    '''type_specifier : CHAR'''
    C_parser.current().set_no_type_name(True); p[0] = CIntType(-11 )

def p_type_specifier_3(p):
    '''type_specifier : SHORT'''
    C_parser.current().set_no_type_name(True); p[0] = CIntType( -2 )

def p_type_specifier_4(p):
    '''type_specifier : INT'''
    C_parser.current().set_no_type_name(True); p[0] = CIntType( -3 )

def p_type_specifier_5(p):
    '''type_specifier : INT64'''
    C_parser.current().set_no_type_name(True); p[0] = CIntType( 64 )

def p_type_specifier_7(p):
    '''type_specifier : LONG'''
    C_parser.current().set_no_type_name(True); p[0] = CIntType( -4 )

def p_type_specifier_8(p):
    '''type_specifier : SIGNED'''
    C_parser.current().set_no_type_name(True)
    p[0] = CIntType( -3 )
    p[0].set_sign("SIGNED")

def p_type_specifier_9(p):
    '''type_specifier : UNSIGNED'''
    C_parser.current().set_no_type_name(True)
    p[0] = CIntType( -3 )
    p[0].set_sign("UNSIGNED")

def p_type_specifier_10(p):
    '''type_specifier : FLOAT'''
    C_parser.current().set_no_type_name(True); p[0] = CFloatType(-32)

def p_type_specifier_11(p):
    '''type_specifier : DOUBLE'''
    C_parser.current().set_no_type_name(True); p[0] = CFloatType(-64)

def p_type_specifier_12(p):
    '''type_specifier : BOOL'''
    C_parser.current().set_no_type_name(True); p[0] = CBoolType()

def p_type_specifier_13(p):
    '''type_specifier : struct_specifier'''
    C_parser.current().set_no_type_name(True); p[0] = p[1]

def p_type_specifier_14(p):
    '''type_specifier : union_specifier'''
    C_parser.current().set_no_type_name(True); p[0] = CVoidType()

def p_type_specifier_15(p):
    '''type_specifier : enum_specifier'''
    C_parser.current().set_no_type_name(True); p[0] = CVoidType()

def p_type_specifier_16(p):
    # TYPEOF の直後に空規則を挟む。
    # PLY は type_specifier:TYPEOF だけだと lookahead '(' を先読みしたまま還元し、
    # アクション内 next_token が '(' を取り逃す（racc では先読みしない）。
    # 空規則が default reduce になると next_token で Ruby と同じく (... ) を捨てられる。
    '''type_specifier : TYPEOF typeof_skip'''
    C_parser.current().set_no_type_name(True)
    p[0] = CVoidType()

def p_typeof_skip(p):
    '''typeof_skip :'''
    token = C_parser.current().next_token()
    if token and token[0] is not None and token[1].val == '(':
        depth = 1
        while depth > 0:
            token = C_parser.current().next_token()
            if token is None or token[0] is None:
                break
            if token[1].val == '(':
                depth += 1
            elif token[1].val == ')':
                depth -= 1

def p_type_specifier_17(p):
    '''type_specifier : TYPE_NAME'''
    C_parser.current().set_no_type_name(True); p[0] = CDefinedType( p[1].val )

def p_struct_specifier_1(p):
    '''struct_specifier : struct_term struct_tag "{" mra_1 struct_declaration_list "}"'''
    StructType.end_of_parse()
    C_parser.current().set_no_type_name(True)
    p[0] = p[2]

def p_struct_specifier_2(p):
    '''struct_specifier : struct_term mra_2 "{" struct_declaration_list "}"'''
    StructType.end_of_parse()
    C_parser.current().set_no_type_name(True)
    p[0] = p[2]

def p_struct_specifier_3(p):
    '''struct_specifier : struct_term struct_tag'''
    StructType.set_define( False )
    StructType.end_of_parse()
    C_parser.current().set_no_type_name(True)
    p[0] = p[2]

def p_struct_term(p):
    '''struct_term : STRUCT'''
    C_parser.current().set_no_type_name(True)

def p_struct_declaration_list_1(p):
    '''struct_declaration_list : struct_declaration'''
    p[0] = p[1]

def p_struct_declaration_list_2(p):
    '''struct_declaration_list : struct_declaration_list struct_declaration'''
    p[0] = p[1]  # default racc result

def p_struct_tag(p):
    '''struct_tag : IDENTIFIER'''
    p[0] = CStructType( p[1].val )
    C_parser.current().set_no_type_name(True)

def p_struct_declaration_1(p):
    '''struct_declaration : declaration_specifiers struct_declarator_list ";"'''
    for i in p[2]:
        i.set_type( p[1] )
        i.set_kind( "MEMBER" )
        i.check()
        CStructType.new_member( i )
        p[0] = p[2]

def p_struct_declaration_2(p):
    '''struct_declaration : union_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_struct_declaration_3(p):
    '''struct_declaration : struct_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_type_specifier_qualifier_list_1(p):
    '''type_specifier_qualifier_list : type_specifier'''
    p[0] = p[1]

def p_type_specifier_qualifier_list_2(p):
    '''type_specifier_qualifier_list : type_specifier type_specifier_qualifier_list'''
    p[0] = p[2].merge(p[1])

def p_type_specifier_qualifier_list_3(p):
    '''type_specifier_qualifier_list : type_qualifier'''
    p[0] = CIntType( -3 )
    p[0].set_qualifier(p[1])

def p_type_specifier_qualifier_list_4(p):
    '''type_specifier_qualifier_list : type_qualifier type_specifier_qualifier_list'''
    p[2].set_qualifier(p[1])
    p[0] = p[2]

def p_struct_declarator_list_1(p):
    '''struct_declarator_list : struct_declarator'''
    p[0] = [ p[1] ]

def p_struct_declarator_list_2(p):
    '''struct_declarator_list : struct_declarator_list "," struct_declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_struct_declarator_1(p):
    '''struct_declarator : declarator'''
    p[0] = p[1]

def p_struct_declarator_2(p):
    '''struct_declarator : declarator ":" constant_expression'''
    p[0] = p[1]  # default racc result

def p_union_specifier_1(p):
    '''union_specifier : union_term union_tag "{" union_declaration_list "}"'''
    C_parser.current().set_no_type_name(True)

def p_union_specifier_2(p):
    '''union_specifier : union_term "{" union_declaration_list "}"'''
    C_parser.current().set_no_type_name(True)

def p_union_specifier_3(p):
    '''union_specifier : union_term union_tag'''
    C_parser.current().set_no_type_name(True)

def p_union_term(p):
    '''union_term : UNION'''
    C_parser.current().set_no_type_name(True)

def p_union_declaration_list_1(p):
    '''union_declaration_list : union_declaration'''
    p[0] = p[1]

def p_union_declaration_list_2(p):
    '''union_declaration_list : union_declaration_list union_declaration'''
    p[0] = p[1]  # default racc result

def p_union_tag(p):
    '''union_tag : IDENTIFIER'''
    p[0] = p[1]

def p_union_declaration_1(p):
    '''union_declaration : declaration_specifiers union_declarator_list ";"'''
    p[0] = p[1]  # default racc result

def p_union_declaration_2(p):
    '''union_declaration : union_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_union_declaration_3(p):
    '''union_declaration : struct_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_union_declarator_list_1(p):
    '''union_declarator_list : union_declarator'''
    p[0] = p[1]

def p_union_declarator_list_2(p):
    '''union_declarator_list : union_declarator_list "," union_declarator'''
    p[0] = p[1]  # default racc result

def p_union_declarator(p):
    '''union_declarator : declarator'''
    p[0] = p[1]

def p_enum_specifier_1(p):
    '''enum_specifier : ENUM IDENTIFIER'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_2(p):
    '''enum_specifier : ENUM "{" enumerator_list "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_3(p):
    '''enum_specifier : ENUM "{" enumerator_list "," "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_4(p):
    '''enum_specifier : ENUM IDENTIFIER "{" enumerator_list "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_5(p):
    '''enum_specifier : ENUM IDENTIFIER "{" enumerator_list "," "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_6(p):
    '''enum_specifier : ENUM TYPE_NAME "{" enumerator_list "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_7(p):
    '''enum_specifier : ENUM TYPE_NAME "{" enumerator_list "," "}"'''
    p[0] = p[1]  # default racc result

def p_enum_specifier_8(p):
    '''enum_specifier : ENUM TYPE_NAME'''
    p[0] = p[1]  # default racc result

def p_enumerator_list_1(p):
    '''enumerator_list : enumerator'''
    p[0] = p[1]

def p_enumerator_list_2(p):
    '''enumerator_list : enumerator_list "," enumerator'''
    p[0] = p[1]  # default racc result

def p_enumerator_1(p):
    '''enumerator : IDENTIFIER'''
    p[0] = p[1]

def p_enumerator_2(p):
    '''enumerator : IDENTIFIER "=" constant_expression'''
    p[0] = p[1]  # default racc result

def p_type_qualifier_1(p):
    '''type_qualifier : CONST'''
    p[0] = "CONST"

def p_type_qualifier_2(p):
    '''type_qualifier : VOLATILE'''
    p[0] = "VOLATILE"

def p_function_specifier_1(p):
    '''function_specifier : __INLINE__'''
    p[0] = p[1]

def p_function_specifier_2(p):
    '''function_specifier : INLINE'''
    p[0] = p[1]

def p_function_specifier_3(p):
    '''function_specifier : __INLINE'''
    p[0] = p[1]

def p_function_specifier_4(p):
    '''function_specifier : CINLINE'''
    p[0] = p[1]

def p_declarator_1(p):
    '''declarator : pointer direct_declarator'''
    p[2].set_type( p[1] )
    p[0] = p[2]

def p_declarator_2(p):
    '''declarator : direct_declarator'''
    p[0] = p[1]

def p_declarator_3(p):
    '''declarator : pointer TYPE_NAME'''
    p[0] = Decl( p[2].val )
    p[0].set_type( p[1] )

def p_direct_declarator_1(p):
    '''direct_declarator : IDENTIFIER'''
    p[0] = Decl( p[1].val )

def p_direct_declarator_1b(p):
    '''direct_declarator : TYPE_NAME'''
    # PLY は struct/type 還元前に declarator を lookahead するため、
    # typedef 再定義名が TYPE_NAME のまま来ることがある（racc では set_no_type_name で IDENTIFIER）。
    p[0] = Decl( p[1].val )

def p_direct_declarator_2(p):
    '''direct_declarator : "(" declarator ")"'''
    p[0] = p[2]

def p_direct_declarator_3(p):
    '''direct_declarator : direct_declarator "[" constant_expression "]"'''
    p[1].set_type( CArrayType( p[3] ) )
    p[0] = p[1]

def p_direct_declarator_4(p):
    '''direct_declarator : direct_declarator "[" "]"'''
    p[1].set_type( CArrayType() )
    p[0] = p[1]

def p_direct_declarator_5(p):
    '''direct_declarator : direct_declarator "(" parameter_type_list ")"'''
    # 	Generator.warning( "W6001 need 'void' for no parameter"  )
    p[1].set_type( CFuncType() )
    p[0] = p[1]

def p_direct_declarator_6(p):
    '''direct_declarator : direct_declarator "(" ")"'''
    # 	Generator.warning( "W6002 need 'void' for no parameter"  )
    p[1].set_type( CFuncType() )
    p[0] = p[1]

def p_pointer_1(p):
    '''pointer : "*"'''
    p[0] = CPtrType()

def p_pointer_2(p):
    '''pointer : "*" type_qualifier'''
    p[0] = CPtrType()
    p[0].set_qualifier( p[2] )

def p_pointer_3(p):
    '''pointer : "*" pointer'''
    p[2].set_type(CPtrType())
    p[0] = p[2]

def p_pointer_4(p):
    '''pointer : "*" type_qualifier pointer'''
    ptrtype = CPtrType()
    ptrtype.set_qualifier( p[2] )
    p[3].set_type( ptrtype )
    p[0] = p[3]

def p_parameter_type_list_1(p):
    '''parameter_type_list : parameter_list'''
    p[0] = p[1]

def p_parameter_type_list_2(p):
    '''parameter_type_list : parameter_list "," "." "." "."'''
    p[0] = p[1]  # default racc result

def p_parameter_list_1(p):
    '''parameter_list : parameter_declaration'''
    p[0] = p[1]

def p_parameter_list_2(p):
    '''parameter_list : parameter_list "," parameter_declaration'''
    p[0] = p[1]  # default racc result

def p_parameter_declaration_1(p):
    '''parameter_declaration : declaration_specifiers declarator'''
    p[0] = p[1]  # default racc result

def p_parameter_declaration_2(p):
    '''parameter_declaration : declaration_specifiers abstract_declarator'''
    p[0] = p[1]  # default racc result

def p_parameter_declaration_3(p):
    '''parameter_declaration : declaration_specifiers'''
    p[0] = p[1]

def p_type_name_1(p):
    '''type_name : type_specifier_qualifier_list'''
    p[0] = p[1]

def p_type_name_2(p):
    '''type_name : type_specifier_qualifier_list abstract_declarator'''
    p[0] = p[1]  # default racc result

def p_abstract_declarator_1(p):
    '''abstract_declarator : pointer'''
    p[0] = p[1]

def p_abstract_declarator_2(p):
    '''abstract_declarator : direct_abstract_declarator'''
    p[0] = p[1]

def p_abstract_declarator_3(p):
    '''abstract_declarator : pointer direct_abstract_declarator'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_1(p):
    '''direct_abstract_declarator : "(" abstract_declarator ")"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_2(p):
    '''direct_abstract_declarator : "[" "]"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_3(p):
    '''direct_abstract_declarator : "[" assignment_expression "]"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_4(p):
    '''direct_abstract_declarator : direct_abstract_declarator "[" "]"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_5(p):
    '''direct_abstract_declarator : direct_abstract_declarator "[" assignment_expression "]"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_6(p):
    '''direct_abstract_declarator : "(" ")"'''
    Generator.warning( "W6003 need 'void' for no parameter"  )

def p_direct_abstract_declarator_7(p):
    '''direct_abstract_declarator : "(" parameter_type_list ")"'''
    p[0] = p[1]  # default racc result

def p_direct_abstract_declarator_8(p):
    '''direct_abstract_declarator : direct_abstract_declarator "(" ")"'''
    Generator.warning( "W6004 need 'void' for no parameter"  )

def p_direct_abstract_declarator_9(p):
    '''direct_abstract_declarator : direct_abstract_declarator "(" parameter_type_list ")"'''
    p[0] = p[1]  # default racc result

def p_initializer_1(p):
    '''initializer : assignment_expression'''
    p[0] = p[1]

def p_initializer_2(p):
    '''initializer : "{" initializer_list "}"'''
    p[0] = p[2]

def p_initializer_3(p):
    '''initializer : "{" initializer_list "," "}"'''
    p[0] = p[2]

def p_initializer_4(p):
    '''initializer : C_EXP "(" STRING_LITERAL ")"'''
    p[0] = C_EXP( p[3] )

def p_initializer_list_1(p):
    '''initializer_list : initializer'''
    p[0] = [ p[1] ]

def p_initializer_list_2(p):
    '''initializer_list : initializer_list "," initializer'''
    p[1].append(p[3])
    p[0] = p[1]

def p_C_parser_1(p):
    '''C_parser : empty'''
    p[0] = None

def p_C_parser_2(p):
    '''C_parser : C_parser extension_statement'''
    p[0] = p[1]  # default racc result

def p_extension_statement_1(p):
    '''extension_statement : statement'''
    C_parser.current().set_no_type_name(False)
    p[0] = p[1]

def p_extension_statement_2(p):
    '''extension_statement : EXTENSION statement'''
    p[0] = p[1]  # default racc result

def p_statement_1(p):
    '''statement : typedef'''
    p[0] = p[1]

def p_statement_2(p):
    '''statement : func_def'''
    p[0] = p[1]

def p_statement_3(p):
    '''statement : enum_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_statement_4(p):
    '''statement : struct_specifier ";"'''
    p[0] = p[1]  # default racc result

def p_statement_5(p):
    '''statement : declaration'''
    p[0] = p[1]

def p_statement_6(p):
    '''statement : ";"'''
    p[0] = p[1]

def p_statement_7(p):
    '''statement : error'''
    p[0] = p[1]

def p_typedef(p):
    '''typedef : TYPEDEF type_specifier_qualifier_list declarator_list ";"'''
    for i in p[3]:
        i.set_kind( "TYPEDEF" )
        Typedef.new_decl_list( p[2], p[3] )


def p_declarator_list_1(p):
    '''declarator_list : declarator'''
    p[0] = [ p[1] ]

def p_declarator_list_2(p):
    '''declarator_list : declarator_list "," declarator'''
    p[0] = p[1]
    p[0].append(p[3])

def p_func_def(p):
    '''func_def : declaration_specifiers declarator compoundstatement'''
    p[0] = p[1]  # default racc result

def p_infunc_statement_list_1(p):
    '''infunc_statement_list : empty'''
    p[0] = None

def p_infunc_statement_list_2(p):
    '''infunc_statement_list : infunc_statement_list infunc_statement'''
    p[0] = p[1]  # default racc result

def p_infunc_statement_1(p):
    '''infunc_statement : declaration'''
    p[0] = p[1]

def p_infunc_statement_2(p):
    '''infunc_statement : ifstatement'''
    p[0] = p[1]

def p_infunc_statement_3(p):
    '''infunc_statement : whilestatement'''
    p[0] = p[1]

def p_infunc_statement_4(p):
    '''infunc_statement : dowhilestatement'''
    p[0] = p[1]

def p_infunc_statement_5(p):
    '''infunc_statement : forstatement'''
    p[0] = p[1]

def p_infunc_statement_6(p):
    '''infunc_statement : switchstatement'''
    p[0] = p[1]

def p_infunc_statement_7(p):
    '''infunc_statement : labelstatement'''
    p[0] = p[1]

def p_infunc_statement_8(p):
    '''infunc_statement : compoundstatement'''
    p[0] = p[1]

def p_infunc_statement_9(p):
    '''infunc_statement : gotostatement'''
    p[0] = p[1]

def p_infunc_statement_10(p):
    '''infunc_statement : expressionstatement'''
    p[0] = p[1]

def p_infunc_statement_11(p):
    '''infunc_statement : asm_statement'''
    p[0] = p[1]

def p_labelstatement_1(p):
    '''labelstatement : IDENTIFIER ":" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_labelstatement_2(p):
    '''labelstatement : CASE constant_expression ":" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_labelstatement_3(p):
    '''labelstatement : DEFAULT ":" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_compoundstatement(p):
    '''compoundstatement : "{" infunc_statement_list "}"'''
    p[0] = p[1]  # default racc result

def p_expressionstatement_1(p):
    '''expressionstatement : ";"'''
    p[0] = p[1]

def p_expressionstatement_2(p):
    '''expressionstatement : expression ";"'''
    p[0] = p[1]  # default racc result

def p_ifstatement_1(p):
    '''ifstatement : IF "(" expression ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_ifstatement_2(p):
    '''ifstatement : IF "(" expression ")" infunc_statement ELSE infunc_statement'''
    p[0] = p[1]  # default racc result

def p_switchstatement(p):
    '''switchstatement : SWITCH "(" expression ")" compoundstatement'''
    p[0] = p[1]  # default racc result

def p_whilestatement(p):
    '''whilestatement : WHILE "(" expression ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_dowhilestatement(p):
    '''dowhilestatement : DO infunc_statement WHILE "(" expression ")" ";"'''
    p[0] = p[1]  # default racc result

def p_forstatement_1(p):
    '''forstatement : FOR "(" expressionstatement expressionstatement ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_forstatement_2(p):
    '''forstatement : FOR "(" expressionstatement expressionstatement expression ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_forstatement_3(p):
    '''forstatement : FOR "(" declaration expressionstatement ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_forstatement_4(p):
    '''forstatement : FOR "(" declaration expressionstatement expression ")" infunc_statement'''
    p[0] = p[1]  # default racc result

def p_gotostatement_1(p):
    '''gotostatement : GOTO IDENTIFIER ";"'''
    p[0] = p[1]  # default racc result

def p_gotostatement_2(p):
    '''gotostatement : CONTINUE ";"'''
    p[0] = p[1]  # default racc result

def p_gotostatement_3(p):
    '''gotostatement : BREAK ";"'''
    p[0] = p[1]  # default racc result

def p_gotostatement_4(p):
    '''gotostatement : RETURN ";"'''
    p[0] = p[1]  # default racc result

def p_gotostatement_5(p):
    '''gotostatement : RETURN expression ";"'''
    p[0] = p[1]  # default racc result

def p_namespace_identifier_1(p):
    '''namespace_identifier : IDENTIFIER'''
    p[0] = NamespacePath( p[1].val, False )

def p_namespace_identifier_2(p):
    '''namespace_identifier : "::" IDENTIFIER'''
    p[0] = NamespacePath( p[2].val, True )

def p_namespace_identifier_3(p):
    '''namespace_identifier : namespace_identifier "::" IDENTIFIER'''
    p[0] = p[1].append_bang( p[3].val )

def p_asm_statement(p):
    # TYPEOF と同様、PLY lookahead を避けるため空規則で ; まで捨てる。
    '''asm_statement : _ASM asm_skip'''
    pass

def p_asm_skip(p):
    '''asm_skip :'''
    while True:
        token = C_parser.current().next_token()
        if token is None or token[0] is None:
            break
        if token[1].val == ";":
            break

def p_error(p):
    pass
