# -*- coding: utf-8 -*-
#
#  CPP2TECSBridgePlugin.rb の Python 移植
#== C++ ⇒ TECS コンポーネントを生成するシグニチャプラグイン

from tecslib.core import globals as G
from tecslib.core.bnf import Generator
from tecslib.core.componentobj.namespace import Namespace
from tecslib.core.componentobj.namespacepath import NamespacePath
from tecslib.core.plugin import CFile
from tecslib.core.tecsgen import Makefile
from tecslib.core.types import VoidType
from tecslib.plugin.SignaturePlugin import SignaturePlugin
from tecslib.rubylib.symbol import Sym


class CPP2TECSBridgePlugin(SignaturePlugin):

    CPPNamespace = Sym("nCPP")

    instances = {}        # signature => [ CPP2TECSBridgePlugin instances ]
    b_written = False     # .cpp, .hpp 出力済み
    celltypes = {}

    def __init__(self, signature, option):
        super().__init__(signature, option)

        def _each_param(func_decl, param_decl):
            direction = param_decl.get_direction()
            if direction in (Sym("INOUT"), Sym("OUT"), Sym("SEND"), Sym("RECEIVE")):
                Generator.error("{} parameter cannot be used in Ruby Bridge".format(
                    str(direction).lower()))

        signature.each_param(_each_param)

        self.celltype_name = "t{}".format(self.signature.get_name())
        self.class_name = "C{}".format(self.signature.get_name())

        if signature in CPP2TECSBridgePlugin.instances:
            CPP2TECSBridgePlugin.instances[signature].append(self)
        else:
            CPP2TECSBridgePlugin.instances[signature] = [self]

        if CPP2TECSBridgePlugin.celltypes.get(self.celltype_name) is None:
            CPP2TECSBridgePlugin.celltypes[self.celltype_name] = [self]
            print("  CPP2TECSBridgePlugin: [signature] {} => [celltype] nCPP::{} => [class] {}".format(
                self.signature.get_namespace_path(), self.celltype_name, self.class_name))

            Makefile.add_var("LD", "g++", "default Linker by CPP2TECSBridgePlugin")
            Makefile.add_obj("$(_TECS_OBJ_DIR){}.o".format(self.class_name))
            Makefile.add_line("""

### added by CPP2TECSBridgePlugin (C++ -> TECS Bridge) ###

CPPC = g++
CPPFLAGS = $(CFLAGS)

# vpath for C++
vpath %.cpp $(SRC_DIR) $(GEN_DIR)

# generic target for C++
$(_TECS_OBJ_DIR){class_name}.o : {class_name}.cpp
\t$(CPPC) -c $(CPPFLAGS) -o $@ $<

### end by CPP2TECSBridgePlugin ###
""".format(class_name=self.class_name))
        else:
            CPP2TECSBridgePlugin.celltypes[self.celltype_name].append(self)

    def gen_cdl_file(self, file):
        file.print("""namespace {} {{
  /// C++ => TECS bridge celltype ///
  [idx_is_id]
  celltype {} {{
    call {} cTECS;
  }};
}};
""".format(self.CPPNamespace, self.celltype_name, self.signature.get_name()))

    def gen_postamble(self, file, b_singleton, ct_name, global_ct_name):
        nsp0 = NamespacePath(self.CPPNamespace, True)
        nsp = nsp0.append(Sym(str(ct_name)))
        ct = Namespace.find(nsp)
        self.gen_cpp(ct)
        self.gen_hpp(ct)
        if CPP2TECSBridgePlugin.b_written is False:
            CPP2TECSBridgePlugin.b_written = True
            for signature, instances in CPP2TECSBridgePlugin.instances.items():
                nsp = nsp0.append(Sym(str(instances[0].get_celltype_name())))
                ct = Namespace.find(nsp)

    def gen_cpp(self, ct):
        file = CFile.open("{}/{}.cpp".format(G.gen, self.class_name), "w")

        file.print("""/* This file is generated by CPP2TECSBridgePlugin */

#include  <stdlib.h>
#include  <memory.h>
#include  "t_stddef.h"
#include  "{}_{}_tecsgen.h"
#include  "{}.hpp"

""".format(self.CPPNamespace, self.celltype_name, self.class_name))

        for cell in ct.get_cell_list():
            if cell.is_generate():
                file.print('char    CELL_{}[] = "{}";\n'.format(cell.get_name(), cell.get_name()))

        file.print("""struct tagName2ID { char *name; ID id; } Name2ID[] = {
""")
        for cell in ct.get_cell_list():
            if cell.is_generate():
                file.print("    {{ CELL_{}, {} }},\n".format(cell.get_name(), cell.get_id()))

        file.print("""    {{ (char*)0, 0 }}
}};

{class_name} *
{class_name}::join( const char *CellName )
{{
    int   i;
    for( i = 0; Name2ID[i].name; i++ )
        if( strcmp( CellName, Name2ID[i].name ) == 0 )
             break;

    if( ! Name2ID[i].name )
        return NULL;

\t{class_name} *cell = new {class_name}( Name2ID[i].id, Name2ID[i].name );
\treturn cell;
}}

{class_name}::{class_name}( ID id, const char *CellName )
{{
    m_id = id;
    m_CellName = CellName;
}}

""".format(class_name=self.class_name))

        for fh in self.signature.get_function_head_array():
            fd = fh.get_declarator()
            ft = fd.get_type()
            ret_type = ft.get_type()

            file.printf("%s\n%s::%s(",
                        ft.get_type_str(),
                        self.class_name,
                        fd.get_name())
            delim = ""
            for p in ft.get_paramlist().get_items():
                pd = p.get_declarator()
                file.printf("%s %s %s%s",
                            delim,
                            pd.get_type().get_type_str(),
                            pd.get_name(),
                            pd.get_type().get_type_str_post())
                delim = ", "
            file.print(" )\n{\n")

            if isinstance(ret_type.get_original_type(), VoidType):
                retval = ""
                retnul = ""
            elif ret_type.get_type_str() == "ER" or ret_type.get_type_str() == "ER_UINT":
                file.printf("    %s    retval%s;\n",
                            ft.get_type().get_type_str(), ft.get_type().get_type_str_post())
                retval = "retval = "
                retnul = "E_ID"
            else:
                file.printf("    %s    retval%s;\n",
                            ft.get_type().get_type_str(), ft.get_type().get_type_str_post())
                retval = "retval = "
                retnul = "0"

            file.print("""    if( ! VALID_IDX( m_id ) )
         return {retnul};
    CELLCB *p_cellcb = (CELLCB*)GET_CELLCB( m_id );
""".format(retnul=retnul))

            file.printf("    %scTECS_%s( ", retval, fd.get_name())
            delim = ""
            for p in ft.get_paramlist().get_items():
                pd = p.get_declarator()
                file.printf("%s%s", delim, pd.get_name())
                delim = ", "
            file.print(" );\n")
            if not isinstance(ret_type.get_original_type(), VoidType):
                file.print("    return    retval;\n")
            file.print("}\n\n")

        file.close()

    def gen_hpp(self, ct):
        file = CFile.open("{}/{}.hpp".format(G.gen, self.class_name), "w")
        file.print("/* This file is generated by CPP2TECSBridgePlugin */\n\n")
        self.gen_class(file)
        file.close()

    def gen_class(self, file):
        file.print("""class {class_name} {{
public:
    /*
     * join:  join to TECS cell.
     *
     * If CellName not found, NULL is returned.
     *
     * In 'join',  new {class_name}( ) is called.
     * So you have to delete after using the joined instance.
     */
    static {class_name} *join( const char *CellName );
""".format(class_name=self.class_name))

        for fh in self.signature.get_function_head_array():
            fd = fh.get_declarator()
            ft = fd.get_type()

            file.printf("    %s %s(",
                        ft.get_type_str(),
                        fd.get_name())
            delim = ""
            for p in ft.get_paramlist().get_items():
                pd = p.get_declarator()
                file.printf("%s %s %s%s",
                            delim,
                            pd.get_type().get_type_str(),
                            pd.get_name(),
                            pd.get_type().get_type_str_post())
                delim = ", "
            file.print(" );\n")

        file.print("""

private:
    {class_name}( ID id, const char *CellName );
    {class_name}();

    ID          m_id;
    const char  *m_CellName;
}};

""".format(class_name=self.class_name))

    def get_celltype_name(self):
        return self.celltype_name
