# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2021 by TOPPERS Project TECS WG
#
#   このファイルは tecsgen (Ruby 版) の tecslib/core/componentobj/cell.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．

import copy
import re

from tecslib.core import globals as G
from tecslib.core.plugin_module import PluginModule
from tecslib.core.syntaxobj.node import NSBDNode
from tecslib.core.toplevel import dbgPrint, print_exception
from tecslib.rubylib.rb import to_s
from tecslib.rubylib.symbol import Sym


class Cell(NSBDNode, PluginModule):  # < Nestable
# @name:: Symbol : composite celltype の内側のインスタンスでは外のセル
# @global_name:: Symbol : C で使える名前（namespace を含む）
# @local_name:: str : cell celltype name { ... } の name
# @celltype:: Celltype | CompositeCelltype
# @join_list:: NamedList
# @reverse_join_list:: NamedList
# @b_defined:: definition flag (false if only prototype )
# @b_prototype:: bool:  prototype specified in current parsing cell. (@b_defined is used to determine whether definition done)
# @b_duplicate:: bool:  definition duplicate
# @b_checked::   bool:  set_definition_join が済んでいる場合 true
# @require_joined_list:: {cp_name=>true}:  set_require_join が済んでいる呼び口は true
# @f_ref:: refercenced from others
# @entry_array_max_subscript:: { @port=>Integer } : 受け口配列の配列添数の最大値（添数無し受け口配列対応）
# @plugin::     Plugin: avialble if cell is generated by plugin generated cdl code.
# @referenced_port_list:: { Port => Integer } : 受け口の参照数
#                                               すべての意味解析(through, composite展開)が終わった後に設定する
#                                               逆require ポートに対して複数の結合がないかチェックする
# @generate:: [ Symbol, String, Plugin ]  = [ PluginName, option, Plugin ] Plugin は生成後に追加される (generate指定子)
# @generate_list:: [ [ Symbol, String, Plugin ], ... ]   generate 指定と generate 文で追加された generate の両方
# @b_post_code_generated:: Bool: true if generated in tmp_plugin_post_code.cdl
#
# composite のためインスタンス変数
# @in_composite:: bool : true if in composite celltype
# @compositecelltypejoin_list:: NamedList : item= CompositeCelltypeJoin ( if @in_composite )
# @f_cloned:: bool : true if cloned (instantiate of composite consist cell)
# @my_clone:: Cell : Composite cell で in_composite = true の場合のみ有効（直前の clone を一時記憶）
# @cell_list:: Cell[local_name] : Composite cell で clone した後のリスト cell_list
# @cell_list2:: [ Cell ] : Composite cell で clone した後のリスト cell_list
#                          @cell_list2 は composite 内での出現順
#
# region のためのインスタンス変数
# @region:: Region (属するregion)
#
# allocator のためのインスタンス変数
# @alloc_list::  [ [ NORMAL_ALLOC, ep_name, func_name, param_name, expr ], ... ]
#   受け口側のアロケータへの結合を記憶。以下のメソッドで追加される
#      set_specifier … cell 定義時にアロケータ指定されている場合
#      create_relay_allocator_join … リレーアロケータの場合
#
# ID のためのインスタンス変数（optimize.rb にて設定）
# @id:: Integer : コード生成直前に設定  (プロトタイプ宣言の場合は -1 のまま放置)
# @id_specified::Integer : 指定された id
#
# restrict のためのインスタンス変数
# @restrict_list::{ entry_name => { func_name, [ region_path_str, ... ] } }
# @restrict_list2::{ entry_name => { func_name, [ domain_root_region, ... ] } }
# @b_restrict_referenced::Bool: restrict_list が参照れた
#
# 受け口 through のためのインスタンス変数
# @ep_through_list [ [ep_name, PluginName, "option"], ... ]
#
# Cell クラスは、以下のものを扱う
# 1)普通のセル
# 2)composite セルタイプのセル
# 3)composite セルタイプの内側のセル (@in_composite)   # composite の内側の composite セルタイプのセルもある
#
# 2) は CellOfComposite クラスとして分けたほうがよいかもしれない
#    expand (composite セルの展開) は CellOfComposite にのみ必要なメソッドである
#    get_real_cell, get_real_port など @celltype.instance_of?( CompositeCelltype ) の判定がなくすっきりする
#    ただ、分離しても、メンテナンスすべき範囲が切り離されてしまい、忘れやすくなる問題とのトレードオフかも
#
# 3) は CellInCompoiste クラスとして分けたほうがよいかもしれない
#    @in_composite で判定している処理を切り離せる (上記 2) よりも分離は容易ではない)
#    clone_for_composite は CellInCompoiste にのみ必要なメソッドである
#    ただし、clone 後に Cell, CellOfComposite に変化する必要があるので、clone ではなく new する実装に変更する必要がある

    nest_stack_index = -1
    nest_stack = []
    current_object = None

    # 定義されたすべてのセル（出現順. namespace に影響されない）
    cell_list = []     # composite の内部のセルを含まない
    cell_list2 = []    # composite の内部のセルを含む (元のセルを含む)
                       # 意味解析後 make_cell_list2 にて設定される

    @classmethod
    def push(cls):
        cls.nest_stack_index += 1
        if cls.nest_stack_index >= len(cls.nest_stack):
            cls.nest_stack.append(None)
        cls.nest_stack[cls.nest_stack_index] = cls.current_object
        cls.current_object = None

    @classmethod
    def pop(cls):
        cls.current_object = cls.nest_stack[cls.nest_stack_index]
        cls.nest_stack_index -= 1
        if cls.nest_stack_index < -1:
            raise Exception("TooManyRestore")

    def __init__(self, ct_path, in_composite=False):
        from tecslib.core.bnf import Generator
        from tecslib.core.componentobj.celltype import Celltype
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype
        from tecslib.core.componentobj.namespace import Namespace
        from tecslib.core.componentobj.region import Region
        from tecslib.core.syntaxobj.namedlist import NamedList

        super().__init__()
        self.region = Region.get_current()

        # celltype のplugin/存在をチェック
        self.celltype = None
        object = Namespace.find(ct_path)    #1
        if object is None:
            # mikan celltype の名前が不完全 "::ct1ct2" になる
            self.cdl_error("S1027 \'$1\' celltype not found", ct_path.get_path_str())
        elif type(object) is not Celltype and type(object) is not CompositeCelltype:
            # mikan celltype の名前が不完全
            self.cdl_error("S1028 \'$1\' not celltype", ct_path.get_path_str())
        else:
            self.celltype = object

        self.in_composite = in_composite
        if self.in_composite:
            self.compositecelltypejoin_list = NamedList(None, "in cell ''")
            self.plugin = None
        else:
            self.compositecelltypejoin_list = None
            self.plugin = Generator.get_plugin()

        Cell.current_object = self
        self.b_defined = False
        self.b_prototype = False
        self.f_ref = False
        self.f_cloned = False
        self.my_clone = None
        self.alloc_list = []
        self.id = -1
        self.id_specified = None
        self.b_duplicate = False
        self.b_checked = False
        self.require_joined_list = {}
        self.entry_array_max_subscript = {}
        self.referenced_port_list = {}
        self.restrict_list = {}
        self.restrict_list2 = {}
        self.b_restrict_referenced = False
        self.b_post_code_generated = False
        self.ep_through_list = []
        self._generate = None
        self.generate_list = []

        self.cell_list = {}
        self.cell_list2 = []

    @classmethod
    def set_name(cls, name):
        cls.current_object.set_name_inst(name)

    def set_name_inst(self, name):
        from tecslib.core.bnf import Generator, Token
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype
        from tecslib.core.componentobj.namespace import Namespace
        from tecslib.core.componentobj.namespacepath import NamespacePath
        from tecslib.core.expression import Expression
        from tecslib.core.syntaxobj.namedlist import NamedList

        # Cell.__init__ は celltype 名還元時。PLY の _last_token_locale 下では
        # その時点の current_locale が celltype 側になる。racc では cell 名が
        # lookahead として locale に入るため、ここで cell 名位置に合わせる。
        loc = Generator.current_locale()
        if loc is not None:
            self.locale = loc

        self.name = name
        self.local_name = name
        if to_s(Namespace.get_global_name()) != "":
            self.global_name = Sym("{}_{}".format(Namespace.get_global_name(), name))
        else:
            self.global_name = name

        cell_prev = None
        # この時点ではプロトタイプか、定義か分らないが、自己参照のために登録
        # set_f_def で再度登録しなおす
        # Celltype への登録は、end_of_parse で行う
        if self.in_composite:
            cell_prev = CompositeCelltype.find_in_current(name)
            if cell_prev is None:
                CompositeCelltype.new_cell_in_composite(self)
        else:
            # cell_prev = Namespace.find( [ name ] )   # 親まで捜しにいく
            cell_prev = Namespace.get_current().find_inst(name)
            if cell_prev is None:
                Namespace.new_cell(self)
                self.set_namespace_path()  # @NamespacePath の設定

        if cell_prev:
            if type(cell_prev) is not Cell:
                self.cdl_error("S1029 $1 mismatch with previous one", name)
                # celltype が一致しているか ?
            elif self.get_celltype() != cell_prev.get_celltype():
                self.cdl_error("S1030 $1: celltype mismatch with previous one", name)
            else:
                # region が一致しているか?
                if cell_prev.get_region() is not self.region:
                    self.cdl_error("S1031 $1 region \'$2\' mismatch  with previous one \'$3\'",
                                   name, self.region.get_name(), cell_prev.get_region().get_name())

                Cell.current_object = cell_prev
                # この時点では、まだプロトタイプ宣言か定義か分らない
                # 以前が定義であって、今回も定義の場合、重複エラーである

        self.join_list = NamedList(None, "in cell '{}'".format(self.name))
        self.reverse_join_list = None

        # debug
        dbgPrint("Cell new_cell: {} {} {}\n".format(self.global_name, self.in_composite, self))

        # 内部アロケータを @alloc_list に追加
        if type(self.celltype) is CompositeCelltype:
            for cell, cp_internal_name, port_name, fd_name, par_name, ext_alloc_ent in \
                    self.celltype.get_internal_allocator_list():
                nsp = NamespacePath(self.name, False)
                rhs = Expression(["OP_DOT", ["IDENTIFIER", nsp],
                                  Token(Sym(str(ext_alloc_ent)), None, None, None)])  #1 構文解析段階なので locale 不要

                self.alloc_list.append(["NORMAL_ALLOC", port_name, None, fd_name, par_name, rhs])
# print "add alloc_list: #{port_name}.#{fd_name}.#{par_name}=#{rhs.to_s}\n"

    #=== Cell# cell の定義
    # 本体(join)の定義の直前に呼び出される
    @classmethod
    def new_def(cls):
        cls.current_object.new_def_inst()

    #=== Cell# cell の定義
    # 本体(join)の定義の直前に呼び出される
    # このメソッドは cell tCelltype Cell { };  '{', '}' の部分がある場合に呼出される
    def new_def_inst(self):
        from tecslib.core.bnf import Generator
        from tecslib.core.syntaxobj.namedlist import NamedList

        self.set_specifier_list(Generator.get_statement_specifier())

        # prototype 指定子ないか
        if not self.b_prototype:
            # 二重定義のチェック
            if self.b_defined is True:
                self.cdl_error("S1032 $1: duplicate cell", self.name)
                dbgPrint("previous: {}: line {} '{}' defined here\n".format(
                    self.prev_locale[0], self.prev_locale[1], self.name))

                # セルの重複定義エラーの処置
                # 前の定義は捨てる
                self.join_list = NamedList(None, "in cell '{}'".format(self.name))

            self.b_defined = True
            self.prev_locale = self.locale

    #===  Cell# 新しい結合をチェック
    # STAGE:   P
    #
    #join::  Join : 新しい結合
    #b_regular:: bool : 通常の場所 (bnf.y.rb)からならば true, それ以外(allocator, require) では false
    def new_join_inst(self, join, b_regular=False):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype
        from tecslib.core.componentobj.join import Join
        from tecslib.core.expression import Expression
        from tecslib.core.syntaxobj.decl import Decl

        join.set_owner(self)

        # composite の新文法対応．
        # composite の中のセルで、attribute の定義である場合
        # cell 内の attr_ext = composite.attr; 構文を処理
        if self.in_composite:
            if self.celltype:
                if type(self.celltype.find(join.get_name())) is Decl:  # mikan a::b で指定されていたものがエラーにならないかも
                    rhs = join.get_rhs()
                    if type(rhs) is Expression:
                        ele = rhs.get_elements()
                        if ele[0] == "IDENTIFIER":    #  attr = attr_ext （右辺単項）か？ #1
                            if CompositeCelltype.has_attribute(ele[1].get_name()):    # mikan a::b.ePort がエラーにならないかも
                                ident = ele[1].get_name()   # 右辺は attribute．
                            else:
                                # 右辺は attribute にないのであれば、定数のはず
                                # 定数は下へ渡す (cell の join にする)
                                ident = None
                        else:
                            if join.get_rhs().eval_const2(None) is None:   # 定数式ではないか？
                                # 右辺が、単一のシンボルでない場合、現状は扱えない
                                self.cdl_error("S1033 rhs expression is not supported. Only attribute is permitted on current version.")
                                return
                            else:
                                # 定数は下へ渡す (cell の join にする)
                                ident = None

                        if ident:
                            # attr = attr; のような参照はエラー (a = composite.a とする必要がある)
                            if self.celltype.find(ident):
                                self.cdl_error("S1034 $1 : cannot refer to $2\'s attribute here. Use \'composite.$3\' to refer to composite celltype\'s",
                                               ident, self.celltype.get_name(), ident)
                    elif type(rhs) is list:
                        if rhs[0] == "COMPOSITE":   # 右辺は composite.attr の形式
                            # Ruby: rhs[1].to_sym （Token → Symbol）
                            ident = rhs[1].to_sym() if hasattr(rhs[1], "to_sym") else Sym(rhs[1])
                        else:
                            ident = None    # 右辺は { 10, -10 } の形式
                    else:
                        ident = None      # 右辺は C_EXP の形式

                    # ident が見つかった（右辺は単一の ident）
                    if ident:
                        # composite の旧文法の構文処理へ渡す．セル外の attr_ext = Cell.attr; 構文の処理に渡す
                        #                        export_name, internal_cell_name, internal_cell_elem_name
                        decl = CompositeCelltype.new_join(ident, self.name, join.get_name(), "ATTRIBUTE")  # mikan a::b.ePort がエラーにならないかも
                        if type(decl) is not Decl:
                            return
                        ini = decl.get_initializer()
                        if ini is None:
                            return
                        # 以下の旧文法実装に渡す．
                        # 旧文法では cell に初期値を与えることで、composite で属性の初期値を指定することができた
                        # attribute で指定された初期値を cell の属性として処理させる
                        join.change_rhs(ini)
                    else:
                        # ident がない．定数式
                        pass
                else:
                    # celltype の属性として、この join の名前がない
                    # 以下の join.set_definition の中でエラーとなる
                    pass
            else:
                return    # celltype がない．すでにエラー
        elif type(join.get_rhs()) is list:
            rhs = join.get_rhs()
            if rhs[0] == "COMPOSITE":
                # composite の中でないのに attr = composite.attr が使われた
                self.cdl_error("S1035 composite : cannot specify out of composite celltype definition")
                return

        # 以下 composite 文法変更前からある処理

        # 既に左辺が同じ名前の初期化が存在するか？
        j = self.join_list.get_item(join.get_name())   # mikan NamespacePath がパスを持っている
        if type(j) is Join:    # mikan ここでは j が Join or Nil 以外は、ないはず

            # debug
            dbgPrint("add_array_member: {} port: {} rhs: {}, {} {}\n".format(
                self.name, j.get_port_name(), j.get_rhs(), join.get_port_name(), join.get_rhs()))
            # 呼び口配列（であると仮定して）要素を追加
            j.add_array_member(join)

        else:
            dbgPrint("new_join: cell={} add_item={}\n".format(self.name, join.get_name()))
            # join
            self.join_list.add_item(join)

        # if get_owner then   # error S1030 発生時 get_owner が見つからなくて例外になる
        #   dbgPrint "Cell#new_join: #{get_owner.get_name}.#{@name}\n"
        # else
        #   dbgPrint "Cell#new_join: \"owner not fund\".#{@name}\n"
        # end
        if not self.in_composite:
            if join.get_cell():
                dbgPrint("new_join: {} {} => {} {}\n".format(
                    self.name, self.region.get_name(), join.get_cell().get_name(),
                    join.get_cell().get_region().get_path_string()))
#     p "region: generate? #{@region.is_generate?}"

    #=== Cell.新しい逆結合
    @classmethod
    def new_reverse_join(cls, reverse_join):
        cls.current_object.new_reverse_join_inst(reverse_join)

    #=== Cell#新しい逆結合
    def new_reverse_join_inst(self, reverse_join):
        dbgPrint("new_reverse_join name={}\n".format(reverse_join.get_name()))
        b_cb = False
        if self.celltype:
            ep_name = reverse_join.get_name()
            port = self.celltype.find(ep_name)
            if port and port.get_signature():
                if port.get_signature().is_callback():
                    b_cb = True
        if not self.b_prototype and not b_cb:
            self.cdl_error("S9999 '$1': reverse join can be used in prototype cell, or with callback signature", self.name)
        if self.reverse_join_list is None:
#      @reverse_join_list = NamedList.new( reverse_join, "in cell '#{@name}'" )
            self.reverse_join_list = [reverse_join]
        else:
#      @reverse_join_list.add_item( reverse_join )
            self.reverse_join_list.append(reverse_join)

    #=== Cell#逆結合から結合を生成
    # STAGE: S
    def create_reverse_join_inst(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype
        from tecslib.core.componentobj.join import Join
        from tecslib.core.componentobj.namespace import Namespace
        from tecslib.core.componentobj.namespacepath import NamespacePath
        from tecslib.core.expression import Expression

        if self.b_checked:
            return

        if self.reverse_join_list:
#      @reverse_join_list.get_items.each{ |rj|
            for rj in self.reverse_join_list:
                # 逆結合の情報を得る
                ep_name = rj.get_name()
                ep_subscript, cp_cell_nsp, cp_name, cp_subscript = rj.get_rhs_cell_and_port()

                # 呼び口側のセルと、そのセルタイプ
                if not self.in_composite:
                    cell = Namespace.find(cp_cell_nsp)
                else:
                    cell = CompositeCelltype.find_in_current(Sym(to_s(cp_cell_nsp)))

                if type(cell) is not Cell:
                    self.cdl_error("S9999 '$1': not cell for reverse join", cp_cell_nsp.get_path_str())
                    continue
                ct = cell.get_celltype()
                if ct is None:
                    continue

                if not self.in_composite:
                    ep_cell_nsp = self.get_namespace_path()
                    ep_cell_nsp_str = ep_cell_nsp.get_path_str()
                else:
                    ep_cell_nsp = NamespacePath(self.name, False)
                    ep_cell_nsp_str = self.name
                ep_subscript_val = ep_subscript.eval_const(None) if ep_subscript else None
                rhs = Expression.create_cell_join_expression(ep_cell_nsp, ep_subscript_val, ep_name, rj.get_locale())
                join = Join(cp_name, cp_subscript, rhs, rj.get_locale())
                cell.new_join_inst(join)
                # join.set_definition( ct.find(join.get_name) )
                if cp_subscript:
                    ss_str = "[{}]".format(cp_subscript)
                else:
                    ss_str = ""
                dbgPrint("create_reverse_join: {}.{}{} => {}.{}\n".format(
                    cell.get_name(), cp_name, ss_str, ep_cell_nsp_str, ep_name))

    @classmethod
    def external_join(cls, internal_cell_elem_name, export_name, b_composite):
        cls.current_object.external_join_inst(internal_cell_elem_name, export_name, b_composite)

    #=== Cell# cell 内に記述する呼び口の外部結合
    # internal_cell_elem_name:: string : 呼び口名
    # export_name:: string: composite の外部に公開する呼び口名
    #  呼び口を外部結合する．
    #  このメソッドは、composite の中の cell でしか呼ばれない．
    def external_join_inst(self, internal_cell_elem_name, export_name, b_composite):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        # cCall => composite.cCall; ではないか？
        if b_composite is False:
            # cCall => cCall; のような場合
            if self.celltype.find(export_name):
                self.cdl_error("S1036 $1 : cannot refer to $2\'s here. Use \'composite.$3\' to refer to composite celltype\'s",
                               export_name, self.celltype.get_name(), export_name)
        # composite の旧文法における、cell 外の cCall = Cell.cCall; の構文処理に渡す
        CompositeCelltype.new_join(export_name, self.name, internal_cell_elem_name, "CALL")

    @classmethod
    def end_of_parse(cls, f_def):
        cell = cls.current_object
        cell.end_of_parse_inst(f_def)
        cls.current_object = None
        return cell

    def end_of_parse_inst(self, f_def):
        import tecsgen
        from tecslib.core.bnf import Generator

        TECSGEN = tecsgen.TECSGEN

        if self.b_prototype:  # prototype 指定子あったか?
            f_def = False       # プロトタイプ宣言とする
            self.b_prototype = False
        if f_def is False:
            # cell tCelltype Cell; の形式の場合
            # f_def == true の場合 new_def で、呼出される
            self.set_specifier_list(Generator.get_statement_specifier())
        if TECSGEN.post_coded():
            self.b_post_code_generated = True
        self.set_f_def(f_def)

        if self._generate:
            self.cell_plugin()

    #=== Cell# プロトタイプ宣言(false)か定義(true)かを設定
    #    このメソッドは構文解釈の最後に呼出される
    #f_def::     bool     false if prototype, true if definition
    def set_f_def(self, f_def):
        if not f_def:
            return

        if not self.in_composite:
            # if @celltype.instance_of? Celltype then
            if self.celltype:  # composite でも呼びだす, エラー時 nil
                self.celltype.new_cell(self)
            Cell.cell_list.append(self)

    def set_f_ref(self):
        dbgPrint("set_f_ref: {}\n".format(self.global_name))
        self.f_ref = True

        # composite の内部セルを参照されたことにする
        # 今のところ問題ないが、未参照であるべきものまで参照されたことになる
        if self.cell_list:
            for cn, cell in self.cell_list.items():
                cell.set_f_ref()

    #=== Cell# cell の指定子を設定
    # STAGE:  B
    #
    #    bnf.y.rb の statement_specifiler_list
    #spec_list::      [ :ALLOCATOR, [ [ :NORMAL_ALLOC, ep_name, subscript, func_name, param_name, expr ], ... ] ]
    #                     s[0]      s[1]   a[0]        a[1]       a[2]        a[3]     a[4]       a[5]
    #    セルに指定されたアロケータ指定子
    #    a[1] の subscript はこのメソッドの中で Expression から Integer に評価される
    #    受け口側に生成されるアロケータ呼び口の結合を内部生成する
    #    呼び口側は Port の create_allocator_join にて生成
    #    リレーアロケータの場合 create_relay_allocator_join にて生成す
    def set_specifier_list(self, spec_list):
        from tecslib.core.componentobj.join import Join
        from tecslib.core.expression import Expression
        from tecslib.core.syntaxobj.cdlstring import CDLString

        if spec_list is None:  # 空ならば何もしない
            return

        dbgPrint("set_spec_list: {}\n".format(self.name))
        b_generate = False   # generate が指定された

        for s in spec_list:
            case = s[0]             # statement_specifier
            if case == "ALLOCATOR":       # [allocator(ePort.func.param=allocCell.eA,ePort.func2.param=allocCell.eA)]
                for a in s[1]:     # alloc_list : allocator の内部の ',' で区切られた部分の配列
                    cp_name = Sym("{}_{}_{}".format(a[0 + 1], a[2 + 1], a[3 + 1]))    # アロケータ呼び口の名前：'=' の左辺を '.' に変えて '_' で連結
                    # p "#{a[0]} #{a[0+1]} #{a[2+1]} #{a[3+1]} #{cp_name}"
                    if a[1 + 1]:
                        subscript = a[1 + 1].eval_const(None)
                        a[1 + 1] = subscript
                    else:
                        subscript = None
                    # アロケータ呼び口の結合を生成
                    join = Join(cp_name, subscript, a[4 + 1])   # 構文解析段階なので locale 不要
                    dbgPrint("new allocator join {} {} {}\n".format(cp_name, subscript, a[4 + 1]))
                    Cell.current_object.new_join_inst(join)
                    self.alloc_list.append(a)
            elif case == "ID":          # [id(0)]
                if type(s[1]) is not Expression:
                    self.cdl_error("S1160 $1 must be constant for id", str(s[1]))
                else:
                    id = s[1].eval_const(None)
                    if id is None or not isinstance(id, int):
                        self.cdl_error("S1161 $1 must be constant for id", str(s[1]))
                    elif id == 0:
                        self.cdl_error("S1162 $1: id cannot be 0", str(s[1]))
                    else:
                        self.id_specified = id
            elif case == "GENERATE":      # [generate(CellPlugin,"option")]
                if self._generate:
                    self.cdl_error("S1163 generate specifier duplicate")
                self._generate = [s[1], s[2]]  # [ PluginName, "option" ]
                b_generate = True
            elif case == "PROTOTYPE":     # [prototype]
                self.b_prototype = True
            elif case == "RESTRICT":      # [restrict]
                for re in s[1]:
                    self.add_restrict(re[0], re[1], re[2])
            elif case == "THROUGH":       # [through(ThroughPlugin,"option")]
                ep_name = Sym(str(s[1]))
                pluginName = s[2]
                option = CDLString.remove_dquote(str(s[3]))
                dbgPrint("through: celltype={} ep_name={}\n".format(self.celltype.get_name(), ep_name))
                if self.celltype.find(ep_name) is None:
                    self.cdl_error("S9999 '$1' entry port not exist", ep_name)
                self.ep_through_list.append([ep_name, pluginName, option])      # [ ep_name, pluginName, "option" ]
            else:
                self.cdl_error("S1039 \'$1\': unknown specifier for cell", s[0])
        if self.b_prototype:
            if b_generate:
                self.cdl_error("S9999 '$1': generate and prototype specified simultaneously", self.name)
            if self.b_defined:
                self.cdl_error("S9999 '$1': prototype specified after definition", self.name)

    def get_allocator_list(self):

        # 意味チェック(set_definition)されていない？
        # relay アロケータの場合、セルの意味チェックが行われていないと、@alloc_list が完成しない
        if self.b_checked is False:
            self.set_definition_join()
        return self.alloc_list

    def get_specified_id(self):
        return self.id_specified

    #=== id 指定子の値を設定
    # このメソッドは、プラグインで cell の生成順序を制御したい場合のために設けた
    # 通常の id 指定子では使っていない
    def set_specified_id(self, id):
        if not isinstance(id, int) or id <= 0:
            self.cdl_error("S1164 '$1' set_specified_id: id not positive integer '$2'", self.name, id)
        elif self.id_specified:
            self.cdl_error("S1165 '$1' set_specified_id: id duplicate", self.name)
        else:
            self.id_specified = id

    #=== Cell# セルプラグイン (generate 指定子)
    def cell_plugin(self):
        plugin_name = self._generate[0]
        option = self._generate[1]
        plugin_object = self.apply_plugin(plugin_name, option)
        # Ruby の Array#[]= は長さを超えて代入できる
        if len(self._generate) <= 2:
            self._generate.append(plugin_object)
        else:
            self._generate[2] = plugin_object

    def apply_plugin(self, plugin_name, option):
        from tecslib.core.plugin_module import _import_plugin_class

        CellPlugin = _import_plugin_class("CellPlugin")

        if not self.b_defined:
            self.cdl_error("S9999 plugin cannot apply to prototype cell '$1'", self.name)

        plClass = self.load_plugin(plugin_name, CellPlugin)
        if plClass is None:
            return None
        # return if plClass == nil # 従来と仕様が変わるので、継続する
        if G.verbose:
            print("new cell plugin: plugin_object = {}.new( {}, {} )\n".format(
                plClass.__name__, self.name, option))

        plugin_object = None
        try:
            plugin_object = plClass(self, option)
            plugin_object.set_locale(self.locale)
            self.generate_and_parse(plugin_object)
        except Exception as evar:
            self.cdl_error("S1166 $1: fail to new", plugin_name)
            print_exception(evar)
        return plugin_object

    def add_compositecelltypejoin(self, join):
        self.compositecelltypejoin_list.add_item(join)

    # mikan 以下のコードが数か所ある。
    # compositecelltypejoin_list が大昔の仕様によいようになっている
    def get_compositecelltypejoin_by_cell_elem_name(self, cell_elem_name):
        for cj in self.compositecelltypejoin_list.get_items():
            if cj.get_cell_elem_name() == cell_elem_name:
                return cj
        return None

    #=== Cell# cell を composite セルタイプのセル用に clone する
    #name::        string : 親 cell の名前  (cell tComposite cell1 での cell1)
    #global_name:: string : 親 cell の global_name
    #join_array::  Join[] : composite の cell の join で、この cell に対応するもの
    #ct_name::     string : 親セルのセルタイプ名
    #region::      Region : 元のセルが属する region
    #このメソッドは CompositeCelltype の expand から呼出される
    def clone_for_composite(self, name, global_name, namespacePath, join_array, ct_name, region, plugin, locale):
        from tecslib.core.componentobj.celltype import Celltype
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        # debug
        dbgPrint("  CLONING Cell#clone_for_composite : cloning: {} {}  b_defined={} {}=>{} \n".format(
            self.name, global_name, self.b_defined, self, self.my_clone))
        dbgPrint("              my_name={} name={} owner class={}\n".format(
            self.name, name, self.owner.__class__.__name__))

        self.my_clone = copy.copy(self)

        # clone したセルの内部に持つ名前情報を調整する
        self.my_clone.set_cloned(name, global_name, namespacePath, join_array, ct_name, region, plugin, locale)

        # @celltype == nil は以前にセルタイプ未定義エラー
        if self.b_defined is True and self.celltype is not None:
            if type(self.celltype) is Celltype:
                # celltype に登録（コード生成の対象となる）
                self.celltype.new_cell(self.my_clone)

        return self.my_clone

    #=== Cell# clone されたセルの内部に持つ名前情報を調整する
    #name::        string : 親 cell の名前  (cell tComposite cell1 での cell1)
    #global_name:: string : 親 cell の global_name
    #join_array::  Join[] : composite の cell の join で、この cell に対応するもの
    #parent_ct_name:: string : 親セルのセルタイプ名（composite セルタイプ）
    #  このメソッドはすぐ上の clone_for_composite から呼出され、clone されたセルを整える
    def set_cloned(self, name, global_name, namespacePath, join_array, parent_ct_name, region, plugin, locale):

        # debug
        dbgPrint("cell.set_cloned : global_name: {}  name: {}  @name: {}\n".format(global_name, name, self.name))
        dbgPrint("set_cloned:  entry_array_max_subscript.len={}\n".format(len(self.entry_array_max_subscript)))
        self.global_name = Sym("{}_{}".format(global_name, self.name))
        self.name = Sym("{}_{}".format(name, self.name))
        self.NamespacePath = namespacePath.change_name(self.name)
        self.region = region
        self.plugin = plugin
        self.locale = locale

        self.in_composite = False
        self.b_checked = False
        self.f_cloned = True

        # Namespace.new_cell( self )  # mikan namespace 対応
        # Ruby はインスタンスメソッド region.new_cell。classmethod 経由だと
        # カレント namespace (展開時は root) に登録され region 内で重複する。
        region.new_cell_inst(self)  # mikan  namespace に cell を置けないことを仮定

        # join_list : NamedList の clone を作る
        if self.celltype:
            dbgPrint("set_cloned: celltype={} name={} global_name={} region={}\n".format(
                self.celltype.get_name(), self.name, global_name, region.get_name()))
        self.join_list = self.join_list.clone_for_composite(parent_ct_name, global_name, locale)
        self.referenced_port_list = {}

        self.alloc_list = []
        self.require_joined_list = {}
        self.entry_array_max_subscript = self.entry_array_max_subscript.copy()
        self.cell_list = {}
        self.cell_list2 = []

        # このセルのグローバル名を与える
        # C_EXP の$id$ 置換はこのセルの名前になる
        for j in join_array:
            self.join_list.change_item(j)

    #=== clone されたセルが composite の場合、内部セルを展開する
    #self:: clone されたセルでなければならない
    def expand_inner(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if not self.f_cloned:
            raise Exception("expnad_inner: not cloned cell")

        # clone しようとするセルが composit セルタイプ？
        if type(self.celltype) is CompositeCelltype:
            # composite cell を再帰的に展開
            self.cell_list, self.cell_list2 = self.celltype.expand(
                self.name, self.global_name, self.NamespacePath, self.join_list, self.region, self.plugin, self.locale)

    #=== Cell# clone された cell の join_list の右辺の変更
    #  呼び口の右辺の cell を他の clone された cell に置換え
    def change_rhs_port(self, cloned_cell_list):

        # debug
        dbgPrint("=====   Cell#change_rhs_port: name={}   =====\n".format(self.name))

        for j in self.join_list.get_items():
            j.change_rhs_port(cloned_cell_list, self.celltype)

    def get_f_def(self):
        return self.b_defined

    def get_f_ref(self):
        if self.f_ref:
            return True
        else:
            return False

    def get_name(self):
        return self.name

    def get_local_name(self):
        return self.local_name

    def get_global_name(self):
        return self.global_name

    def get_region(self):
        return self.region

    def get_domain_class_root(self):
        dr = self.region.get_domain_root()
        cr = self.region.get_class_root()
        if dr.is_sub_region_of(cr):
            return dr
        else:
            return cr

    def get_ep_through_list(self):
        dbgPrint("Cell#get_ep_through_list: name={} len={}\n".format(self.name, len(self.ep_through_list)))
        return self.ep_through_list

    @classmethod
    def get_current(cls):
        return cls.current_object

    #=== Cell# 生成されるセルか？
    # 最適化、コード生成中に、対象となる region に属する場合 true を返す
    def is_generate(self):
        if G.generating_region is None:
            # 構文解釈、意味解析段階で呼ばれると例外発生
            raise Exception("is_generate? called before optimizing")

        # print "Cell#is_generate?: #{@name} #{@region.get_name} #{$generating_region.get_name}\n"
        if G.generating_region is self.region.get_link_root():
            return True
        else:
            return False

    #=== Cell# composite 内部の複製されたセルか？
    # composite 定義の内部のセル (@in_composite = true) ではない
    def is_cloned(self):
        return self.f_cloned

    #=== Cell# composite 内部のセルか？
    def is_in_composite(self):
        return self.in_composite

    #=== Cell# composite のセルか？
    def is_of_composite(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if isinstance(self.celltype, CompositeCelltype):
            return True
        else:
            return False

    #=== Cell# tmp_plugin_post_code.cdl で生成されたセルか？
    def post_code_generated(self):
        return self.b_post_code_generated

    # composite cell の port に対応する内部の cell の port の名前（リンク時に必要な名前）
    def get_real_global_name(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if type(self.celltype) is CompositeCelltype:

            # debug
            dbgPrint("get_real_global_name: cell name: {} {} {} {}\n".format(
                self.name, self.local_name, self.global_name, port_name))
            for n, c in self.cell_list.items():
                dbgPrint("   name: {}\n".format(n))
                if c:
                    dbgPrint(" get_name: {} local_name: {}\n".format(c.get_name(), c.get_local_name()))
                dbgPrint("\n\n")

            cj = self.celltype.find_export(port_name)

            # debug
            dbgPrint(" composite join name: {}  cell: {}  cell elem: {}\n".format(
                cj.get_name(), cj.get_cell_name(), cj.get_cell_elem_name()))

            name = self.cell_list["{}".format(cj.get_cell_name())].get_real_global_name(cj.get_cell_elem_name())
            return name

        else:
            # debug
            dbgPrint("  get_real_global_name: cell name: {}\n".format(self.global_name))

            return self.global_name

    #=== Cell# セルの受け口 port_name に対する実際のセル名、受け口名を '_' で連結
    #    namespace 名 + '_' + セル名 + '_' + 受け口名   （このセルが composite ならば展開後のセル名、受け口名）
    def get_real_global_port_name(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        # composite か？
        if type(self.celltype) is CompositeCelltype:

            # debug
            dbgPrint("get_real_global_port_name: cell name: {} {} {} {}\n".format(
                self.name, self.local_name, self.global_name, port_name))
            for n, c in self.cell_list.items():
                dbgPrint("   name: {}\n".format(n))
                if c:
                    dbgPrint(" get_name: {} local_name: {}\n".format(c.get_name(), c.get_local_name()))
                dbgPrint("\n")

            # セルタイプ内で port_name の CompositeCelltypeJoin を探す（コード生成段階では必ず見つかる）
            cj = self.celltype.find_export(port_name)

            # debug
            dbgPrint("   composite join name: {}  cell: {}  cell elem: {}\n".format(
                cj.get_name(), cj.get_cell_name(), cj.get_cell_elem_name()))

            # composite の内部のセルに対し再帰的に get_real_global_port_name を適用
            name = self.cell_list["{}".format(cj.get_cell_name())].get_real_global_port_name(cj.get_cell_elem_name())
            return name

        else:
            # debug
            dbgPrint("get_real_global_port_name:  cell name: {}\n".format(self.global_name))

            return "{}_{}".format(self.global_name, port_name)

    #=== Cell# PORT (celltype の定義) を得る
    def get_real_port(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        # composite か？
        if type(self.celltype) is CompositeCelltype:

            # セルタイプ内で port_name の CompositeCelltypeJoin を探す（コード生成段階では必ず見つかる）
            cj = self.celltype.find_export(port_name)

            # composite の内部のセルに対し再帰的に get_real_port を適用
            port = self.cell_list["{}".format(cj.get_cell_name())].get_real_port(cj.get_cell_elem_name())
            return port
        else:

            return self.celltype.find(port_name)

    #=== Cell# cell を得る
    #    composite でなければ自分自身を返す
    def get_real_cell(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        # composite か？
        if type(self.celltype) is CompositeCelltype:

            # セルタイプ内で port_name の CompositeCelltypeJoin を探す（コード生成段階では必ず見つかる）
            # print "get_real_cell: cell=#{@name} port=#{port_name}\n"
            # pp @cell_list
            cj = self.celltype.find_export(port_name)

            # composite の内部のセルに対し再帰的に get_real_port を適用
            cell = self.cell_list["{}".format(cj.get_cell_name())].get_real_cell(cj.get_cell_elem_name())
            return cell
        else:

            return self

    #=== Cell#get_real_celltype
    #
    def get_real_celltype(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if type(self.celltype) is CompositeCelltype:
            return self.celltype.get_real_celltype(port_name)
        else:
            return self.celltype

    #=== Cell# 受け口のport の参照カウントをアップする
    #port_name:: Symbol  : ポート名
    def port_referenced(self, port):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if port in self.referenced_port_list:
            self.referenced_port_list[port] += 1
        else:
            self.referenced_port_list[port] = 1

        # composite か？
        if type(self.celltype) is CompositeCelltype:

            # セルタイプ内で port_name の CompositeCelltypeJoin を探す（コード生成段階では必ず見つかる）
            cj = self.celltype.find_export(port.get_name())

            dbgPrint(" port_referenced: {} {} cj={}\n".format(
                self.celltype.get_name(), self.name, (cj and cj.get_name()) or "nil"))

            if cj:  # 既にエラー
                # composite の内部のセルに対し再帰的に get_real_port を適用
                # Ruby Hash#[] は欠落時 nil。Python は KeyError になるため get を使う
                cell = self.cell_list.get("{}".format(cj.get_cell_name()))
                if cell and cell.get_celltype():
                    cell.port_referenced(cell.get_celltype().find(cj.get_cell_elem_name()))

    def get_internal_port_name(self, port_name):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if type(self.celltype) is CompositeCelltype:
            cj = self.celltype.find_export(port_name)
#      return "#{@name}_#{cj.get_cell.get_internal_port_name cj.get_cell_elem_name}"
            return cj.get_cell().get_internal_port_name(cj.get_cell_elem_name())
        else:

            # debug
            dbgPrint("  get_global_port_name: cell port: {}_{}\n".format(self.global_name, port_name))

            return "{}_{}".format(self.global_name, port_name)

    #Cell#属性の初期値を得る
    #attr_name::Symbol  必ず初期化されていないと Ruby 例外となる
    def get_attr_initializer(self, attr_name):
        val = self.join_list.get_item(attr_name)
        if val is None:
            val = (self.celltype.find(attr_name)).get_initializer()
        else:
            val = val.get_rhs()
        return val

    def get_celltype(self):
        return self.celltype

    def get_join_list(self):
        return self.join_list

    def set_id(self, id):
        self.id = id

    def get_id(self):
        return self.id

    def get_plugin(self):
        return self.plugin

    def get_cell_list2_inst(self):
        list = []
        for cell in self.cell_list2:
            list.append(cell)
            list += cell.get_cell_list2_inst()
        return list

    #=== Cell# 受け口配列の添数の最大値を設定
    def set_entry_port_max_subscript(self, port, num):
        dbgPrint("set_entry_port_max_subscript: {}.{}: {}\n".format(self.name, port.get_name(), num))
        subscript = self.entry_array_max_subscript.get(port)

        if subscript is None or num > subscript:
            self.entry_array_max_subscript[port] = num
            self.set_entry_inner_port_max_subscript(port, num)

    #=== Cell# composite の内側セルの受け口配列の添数の最大値を設定
    def set_entry_inner_port_max_subscript(self, port, num):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if self.cell_list is None:
            return    # プロトタイプ宣言しかされていなくて、内側セルが展開されていない　or composite 展開前

        # composite の内側のセルに伝播
        if type(self.celltype) is CompositeCelltype:
            dbgPrint("set_entry_inner_port_max_subscript {} {} {} cell_list.len={}\n".format(
                self.name, port, num, len(self.cell_list)))
            # @cell_list.each{ |c, p| print c, p, '\n' }

            cj = self.celltype.find_export(port.get_name())
            if cj and self.cell_list.get(to_s(cj.get_cell_name())):
                inner_cell = self.cell_list[to_s(cj.get_cell_name())]
                ct = inner_cell.get_celltype()
                if ct:
                    inner_port = ct.find(cj.get_cell_elem_name())
                    inner_cell.set_entry_port_max_subscript(inner_port, num)

    #=== Cell# 受け口配列の添数の最大値を返す
    # 長さは +1 する
    # 1つもない場合は -1 を返す
    def get_entry_port_max_subscript(self, port):
        subscript = self.entry_array_max_subscript.get(port)
        if subscript is None:
            subscript = -1
        return subscript

    #=== Cell# リレーアロケータの結合を生成
    # STAGE: S
    # 呼び口側の結合を元に受け口側の結合を生成
    def create_relay_allocator_join(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype
        from tecslib.core.componentobj.join import Join

        # celltype がなければチェックしない（既にエラー）
        if self.celltype is None:
            return

        # relay allocator を生成
        for p in self.celltype.get_port_list():
            ail = p.get_allocator_instance()
            if ail:
                dbgPrint("create_relay_allocator_join: {}, {}\n".format(self.name, p.get_name()))
                if p.get_array_size():
                    # mikan relay allocator が array に対応できてもよいのでは？
                    self.cdl_error("S1040 array not supported for relay allocator")
                    continue
                for name, ai2 in ail.items():
                    # ai2 = [ :INTERNAL_ALLOC|:RELAY_ALLOC, func_name, param_name, rhs_cp_name, rhs_func_name, rhs_param_name ]
                    if ai2[0] == "RELAY_ALLOC":
                        dbgPrint("create_relay_allocator_join: {}, {}\n".format(self.name, name))
                        # 呼び口側の結合を取り出す
                        ja = self.join_list.get_item(Sym("{}_{}_{}".format(ai2[3], ai2[4], ai2[5])))
                        if ja is None:
                            # 見つからない場合
                            found = False

                            # composite 内で外部に結合されているか
                            if self.in_composite:
                                for cj in self.compositecelltypejoin_list.get_items():
                                    dbgPrint("create relay_allocator in_composite\n")
                                    dbgPrint("    {} {} {} {}_{}_{}\n".format(
                                        cj.get_cell_name(), self.name, cj.get_cell_elem_name(),
                                        ai2[3], ai2[4], ai2[5]))
                                    if cj.get_cell_name() == self.name and \
                                            cj.get_cell_elem_name() == Sym("{}_{}_{}".format(ai2[3], ai2[4], ai2[5])):
                                        found = True
                                        dbgPrint("create_relay_allocator: found {}\n".format(cj.get_cell_elem_name()))
                                        break

                            if found is False:
                                self.cdl_error("S1041 \'$1_$2_$3\': not joined. cannot create internal join for relay allocator",
                                               ai2[3], ai2[4], ai2[5])
                                # print( "      In cell #{get_name}\n" )
                                # join が未結合であることのエラーは二度でる (S1043)
                            continue    # 打ち切る

                        b_export = False
                        # composite 内のセルでエクスポートされているかチェック
                        #  mikan エクスポート側と、こちら側で、リレー先が一致するかチェックが必要
                        if self.compositecelltypejoin_list:
                            # export されているか調べる
                            for cj in self.compositecelltypejoin_list.get_items():
                                # 属性名と composite の export する名前は一致するか
                                if p.get_name() == cj.get_cell_elem_name():
                                    # print "export : #{p.get_name}\n"
                                    b_export = True    # 属性は export されているので、とりあえず未初期化とはしない
                                    break
                            #

                        # mikan 配列
                        am = None
                        if am:
                            for ja2 in am:
                                rhs = ja2.get_rhs()
                                subscript = ja2.get_subscript()
                                if b_export is False:
                                    # CompositeCelltype の場合、内側のセルで生成させる
                                    join = Join(Sym("{}_{}_{}".format(p.get_name(), ai2[1], ai2[2])),
                                                subscript, rhs, self.loacle)
                                    # p ( "#{p.get_name}_#{ai2[1]}_#{ai2[2]}", subscript, rhs )
                                    self.new_join_inst(join)
                                    join.set_definition(self.celltype.find(join.get_name()))
                                    # mikan relay mismatch チェックができていない（下方を参照）
                                self.alloc_list.append(["NORMAL_ALLOC", p.get_name(), subscript, ai2[1], ai2[2], rhs])
                        else:
                            if b_export is False:
                                # CompositeCelltype の場合、内側のセルで生成させる
                                join = Join(Sym("{}_{}_{}".format(p.get_name(), ai2[1], ai2[2])),
                                            None, ja.get_rhs(), self.locale)
                                self.new_join_inst(join)
                                join.set_definition(self.celltype.find(join.get_name()))
                                if type(self.celltype) is CompositeCelltype:
                                    jr = self.join_list.get_item(Sym("{}_{}_{}".format(ai2[3], ai2[4], ai2[5])))
                                    if jr.get_rhs_cell2() != join.get_rhs_cell2() or jr.get_rhs_port2() != join.get_rhs_port2():
                                        self.cdl_error("S1167 \'$1\': relay mismatch \'$2\'",
                                                       "{}_{}_{}".format(p.get_name(), ai2[1], ai2[2]),
                                                       "{}_{}_{}".format(ai2[3], ai2[4], ai2[5]))
                                        # 本当は composite の呼び口と受け口の間で行うべきだが、内部で多段接続されている場合
                                    else:
                                        dbgPrint("relay success:  {}_{}_{}=>{}_{}_{} {}.{} \n".format(
                                            p.get_name(), ai2[1], ai2[2], ai2[3], ai2[4], ai2[5],
                                            jr.get_rhs_cell2().get_name(), jr.get_rhs_port2()))
                            self.alloc_list.append(["NORMAL_ALLOC", p.get_name(), None, ai2[1], ai2[2], ja.get_rhs()])
                        dbgPrint("create_relay_allocator_join: {}_{}_{} {}_{}_{}\n".format(
                            p.get_name(), ai2[1], ai2[2], ai2[3], ai2[4], ai2[5]))

    #=== Cell# @@cell_list2 を作る
    # @@cell_list2 は、出現順に composite 内を含むセルのリスト
    @classmethod
    def make_cell_list2(cls):
        for c in cls.cell_list:
            cls.cell_list2.append(c)
            cls.cell_list2 += c.get_cell_list2_inst()

    #=== Cell# @@cell_list2 を得る
    # composite 内を含む (compositeも含む)
    # 意味解析後に作成される
    @classmethod
    def get_cell_list2(cls):
        return cls.cell_list2

    #=== Cell# @@cell_list を得る
    #composite の中を含まない
    @classmethod
    def get_cell_list(cls):
        return cls.cell_list

    #=== Cell# reverse_join を生成する
    @classmethod
    def create_reverse_join(cls):
        for c in cls.cell_list:
            ct = c.get_celltype()
            # if c.is_generate? then
            if ct:
                c.create_reverse_join_inst()
            # end

    #=== Cell# reverse_require_join を生成する
    @classmethod
    def create_reverse_require_join(cls):
        for c in cls.cell_list2:
            ct = c.get_celltype()
            # if c.is_generate? then
            if ct:
                # self への呼び口側の結合を生成
                ct.create_reverse_require_join(c)
            # end

    #=== Cell# 受け口のport の参照カウントを設定する
    # self は呼び元のセル
    # 呼び先セルの受け口の参照カウントをアップする
    def set_port_reference_count(self):
        from tecslib.core.componentobj.port import Port

        for j in self.join_list.get_items():
            if type(j.get_definition()) is Port:
                am = j.get_array_member2()
                if am:             # 呼び口配列
                    for j2 in am:
                        if j2 is None:    # optional で一部が欠落しているケース
                            continue
                        cell = j2.get_rhs_cell2()
                        if cell is None:     # 右辺が見つからなかった．既にエラー
                            continue
                        port = cell.get_celltype().find(j2.get_rhs_port2())
                        dbgPrint("set_port_reference_count: {}.{} => {}.{}\n".format(
                            self.name, j2.get_name(), cell.get_name(), port.get_name()))
                        cell.port_referenced(port)
                else:
                    cell = j.get_rhs_cell2()
                    if cell is None or cell.get_celltype() is None:     # 右辺が見つからなかった．既にエラー
                        continue
                    port = cell.get_celltype().find(j.get_rhs_port2())
                    if port is None:
                        dbgPrint("set_port_ref: {}.{} = {}.{}\n".format(
                            self.name, j.get_name(), cell.get_name(), j.get_rhs_port2()))
                        # through プラグインで生成されたセルの受け口が見つからないケース (のハズ)
                        self.cdl_error("entry '$1' not found in '$2' refered from $3.$4",
                                       j.get_rhs_port2(), cell.get_name(), self.name, j.get_name())
                        continue
                    dbgPrint("set_port_reference_count: {}.{} => {}.{}\n".format(
                        self.name, j.get_name(), cell.get_name(), port.get_name()))
                    cell.port_referenced(port)

    #=== Cell# 結合(Join)のチェック
    #     Join は呼び口の結合または attribute の初期化
    #
    #  mikan このメソッドは、以下の４つのチェックからなるが、分割したほうがより適切な長さのメソッドになる
    #  ・リレーアロケータの生成 => create_relay_allocator_join
    #  ・未結合の呼び口のチェック
    #  ・ポインタ型が配列で初期化される場合のチェック
    #  ・未初期化の属性のチェック
    def check_join(self):
        from tecslib.core.componentobj.compositecelltypejoin import CompositeCelltypeJoin
        from tecslib.core.componentobj.port import Port
        from tecslib.core.expression import Expression
        from tecslib.core.syntaxobj.decl import Decl
        from tecslib.core.types import PtrType

        # celltype がなければチェックしない（既にエラー）
        if self.celltype is None:
            return
        if self.b_defined is False:
            return
        if self.f_cloned is True:    # 内部セルについては、composite の定義時にチェックされている
            return

        # debug
        # if @compositecelltypejoin_list then
        #   p "check_join"
        #   @compositecelltypejoin_list.get_items.each { |cj| p "#{cj.get_name} #{cj.get_name.object_id}" }
        # end

        # 未結合の呼び口のチェック
        for p in self.celltype.get_port_list():

            # 呼び口でなければ、チェックしない
            if p.get_port_type() != "CALL":
                continue

            # debug
            dbgPrint("check_join: {} {} {}\n".format(self.name, self.get_celltype().get_name(), p.get_name()))

            # 結合リストの中から呼び口名に一致するものを取りだす
            j = self.join_list.get_item(p.get_name())

            if j is None:
                # 未結合の呼び口

                # composite celltype の内部の場合、composite celltype が export する呼び口に結合されているか探す
                found = False
                if self.in_composite:
                    # composite celltype の export するものすべてから探す
                    # （export するものの右辺値から探すために get_item ではダメ）
                    for cj in self.compositecelltypejoin_list.get_items():
                        # 呼び口名と composite の export する名前は一致するか
                        if p.get_name() == cj.get_cell_elem_name():
                            found = True
                # 呼び口配列の場合 optional で全ての要素が初期化されない場合に、ここへ来る
                if not found and not p.is_require() and not p.is_optional():
                    if not p.is_allocator_port():
                        self.cdl_error("S1042 call port \'$1\' not initialized in cell \'$2\'", p.get_name(), self.name)
                    else:
                        self.cdl_error("S1043 call port \'$1\' not initialized in cell \'$2\'. this call port is created by tecsgen. check allocator specifier",
                                       p.get_name(), self.name)
            elif isinstance(p.get_array_size(), int):
                # 添数あり呼び口配列の場合、すべての添数要素が初期化されているかチェックする

                am = j.get_array_member2()
                if am:
                    # join は配列

                    # 呼び口配列定義での配列の大きさ
                    length = p.get_array_size()

                    # 配列の大きさが呼び口配列定義と結合定義で一致するか？
                    if len(am) != length:
                        if not p.is_optional() or len(am) >= length:
                            # optional の場合、要素数が少なすぎるのは OK
                            self.cdl_error("S1044 $1: array initializer too many or few, $2 for $3",
                                           p.get_name(), len(am), length)

                        # am の要素に nil を追加しておく (#_CPA_# のコード生成時、この配列要素数分生成)
                        i = len(am)
                        while i < length:
                            am.append(None)
                            i += 1

#          # 配列要素の抜けがないかチェック
#          if am.length < length then  # 満たない場合既にエラーだが要素のある範囲でチェック
#            length = am.length
#          end
                    i = 0
                    while i < length:
                        if am[i] is None:
                            if not p.is_optional():
                                self.cdl_error("S1045 $1[$2]: not initialized", p.get_name(), i)
                        else:
                            # 生成されないリージョンへの結合かチェック
                            if not self.in_composite:
                                am[i].check_region2()
                        i += 1

                # else
                # join が非配列であれば、既にエラー
            elif j.get_array_member():
                # 添数なし呼び口配列の場合
                am = j.get_array_member2()
                length = len(am)
                i = 0
                while i < length:
                    if am[i] is None:
                        if not p.is_optional():
                            self.cdl_error("S1046 $1[$2]: not initialized", p.get_name(), i)
                    i += 1

                # 生成されないリージョンへの結合かチェック
                if not self.in_composite:
                    for join in am:
                        if join:
                            join.check_region2()
            else:
                # 呼び口［配列」でない場合

                # 生成されないリージョンへの結合かチェック
                if not self.in_composite:
                    j.check_region2()

            # j != nil
        # ポインタ型が配列で初期化される場合のチェック
        for a in (self.celltype.get_attribute_list() + self.celltype.get_var_list()):
            if a.get_size_is():

                if type(a) is CompositeCelltypeJoin:
                    # 既にエラーになっている
                    # cdl_error( "S1047 size_is pointer cannot be exposed for composite attribute"  )
                    continue

                if not isinstance(a.get_type(), PtrType):
                    self.cdl_error("S1048 $1: size_is specified for non-pointer type", a.get_name())
                else:
                    size = a.get_size_is().eval_const(self.join_list, self.celltype.get_name_list())
                    a.get_type().set_scs(a.get_size_is(), None, None, None, False)
                    if not isinstance(size, int):               # C_EXP の可能性あり
                        # mikan 多分ここでのエラー発生は不要、eval_const の中で変数が存在しない、型が不適切などのエラーになるはず
                        self.cdl_error("S1049 $1: size_is arg not constant", a.get_name())
                    else:
                        j = self.join_list.get_item(a.get_identifier())
                        if j:
                            ini = j.get_rhs()
                            if ini:
                                if type(ini) is not list:
                                    self.cdl_error("S1050 unsuitable initializer, need array initializer")
                                elif size < len(ini):
                                    self.cdl_error("S1051 too many initializer for array, $1 for $2", len(ini), size)
                                else:
                                    # a.get_type.set_scs( a.get_size_is, nil, nil )
                                    pass
                        else:
                            # size_is 引数がセルで指定されていて、初期化子がセルタイプで指定されているケースのチェック
                            ini = a.get_initializer()
                            if type(ini) is Expression:
                                ini = ini.eval_const(self.celltype.get_name_list())
                            if type(ini) is list:
                                if len(ini) > size:
                                    self.cdl_error("S1168 too many initializer for array, $1 for $2", len(ini), size)
            else:
                if type(a) is not CompositeCelltypeJoin:
                    # composite は size_is 指定できない
                    if isinstance(a.get_type(), PtrType):
                        j = self.join_list.get_item(a.get_identifier())
                        if j and type(j.get_rhs()) is list:
                            ## size_is 指定されていないポインタが Array で初期化されていたら、エラーとする
                            self.cdl_error("S1169 $1: non-size_is pointer cannot be initialized with array initializer", a.get_identifier())

        # 未初期化の属性をチェック
        for a in self.celltype.get_attribute_list():
            b_init = False
            # self.show_tree 1
            if a.get_initializer():                               # セルタイプで初期化されている
                b_init = True
                # @in_composite で export されている場合には、この初期値は使われない
                # export されている、いないに関わらず、初期化されていることが保証される
            elif self.join_list.get_item(a.get_name()):            # セルで初期化されている
                b_init = True
            elif self.in_composite and self.compositecelltypejoin_list:
                # 属性が export されているか調べる。export されていれば未初期化とはしない
                # mikan リニアサーチ
                for cj in self.compositecelltypejoin_list.get_items():
                    # 属性名と composite の export する名前は一致するか
                    if Sym(str(a.get_name())) == Sym(str(cj.get_cell_elem_name())):
                        b_init = True    # 属性は export されているので、とりあえず未初期化とはしない
                if b_init:
                    # size_is の引数がマッチするかチェックする
                    # 内部セルの size_is をエクスポートする size_is とマッチするかチェックする
                    # 内部セルとエクスポートで名前を変えている可能性があるので、内部セルの size_is の名前を変換した上でチェックする
                    if a.get_size_is():
                        ### p "attr: get_size_is"
                        cj = self.compositecelltypejoin_list.get_item(Sym(str(a.get_name())))
                        if type(cj.get_port_decl()) is Decl:
                            ### p "attr: get_size_is 2"
                            # cj_size_is は、外部公開される attr の size_is
                            cj_size_is = cj.get_port_decl().get_size_is()
                            if cj_size_is is None:
                                self.cdl_error("S1170 \'$1\' has size_is but export attr \'$2\' doesn't have", a.get_name(), cj.get_name())
                            exprs = str(a.get_size_is())
                            ### p "exprs : ", exprs
                            remain = exprs
                            inner_to_export = {}
                            ### exprs に含まれる識別子を抜き出し、対応する export される名前を探す
                            while remain != "" and remain is not None:
                                ### p "remain ", remain
                                m = re.search(r'([^\w]*)([_A-Za-z][\w\d]*)', remain)   # 変数名文字列を取り出す
                                if m is None or m.group(2) is None:
                                    break
                                arg_name = Sym(m.group(2))
                                remain = remain[m.end():]
                                ### p exprs, $1, $2, $'
                                # size_is に含まれる変数は、composite で export されているか
                                cj2 = None
                                for cj2t in self.compositecelltypejoin_list.get_items():
                                    if cj2t.get_cell_elem_name() == arg_name:
                                        cj2 = cj2t
                                if cj2 is None:
                                    self.cdl_error("S1171 \'$1\' size_is argument of \'$2\' not exported", a.get_name(), cj.get_name())
                                    continue
                                if type(cj2.get_port_decl()) is Decl:
                                    decl2 = cj2.get_port_decl()
                                    # 内部の名前と外部の名前の対応関係を記憶
                                    inner_to_export[arg_name] = decl2.get_name()
                                # else cj2 は Port (既にエラー)
                            # 内部の名前を外部の名前で置換
                            for arg_name, exp_name in inner_to_export.items():
                                ### p "changing #{arg_name}=>#{exp_name}"
                                # exprs.gsub!( Regexp.new("#{arg_name}[^0-9A-Za-z_]"), exp_name.to_s )
                                exprs = re.sub(re.compile("{}(\\W)".format(re.escape(str(arg_name)))), str(exp_name) + "\\1", exprs)  # 文字列末尾にないケース
                                exprs = re.sub(re.compile("{}\\Z".format(re.escape(str(arg_name)))), str(exp_name), exprs)          # 文字列末尾にあるケース
                            ### p "changed: #{exprs} #{cj_size_is.to_s}"
                            if exprs != str(cj_size_is):
                                self.cdl_error("S1172 \'$1\' size_is argument mismatch with exporting one \'$2\'", a.get_name(), cj.get_name())
                        # else cj は Port (既にエラー)

            if b_init is False:
                self.cdl_error("S1052 attribute \'$1\' not initialized in cell \'$2\'", a.get_name(), self.name)

    #=== Cell# 逆 require をチェックする
    # 逆 require 指定された受け口に複数の結合がないかチェックする
    # composite の内部セル (f_cloned=true) もチェックする
    def check_reverse_require(self):
        # celltype がなければチェックしない（既にエラー）
        if self.celltype is None:
            return
        if self.b_defined is False:
            return

        # p "check reverse require   #{@name}"
        # 逆require 指定された受け口に複数の結合がないかチェック
        for port, count in self.referenced_port_list.items():
            # p port.class, count
            # p port.get_name, port.get_port_type, port.get_signature.get_name
            if port.is_reverse_required() and count > 1:
                self.cdl_warning("W1009 $1: fixed join entry port has multi join", port.get_name())

    #=== Cell# require 呼び口の結合を行う
    # STAGE: S
    #cp_name:: Symbol           : 呼び口名
    #cell_or_t:: Celltype|Cell  : celltype の require の右辺で指定されたセルタイプまたはセル
    #port::  Port               : celltype の Port オブジェクト
    def set_require_join(self, cp_name, cell_or_ct, port):
        from tecslib.core.componentobj.celltype import Celltype
        from tecslib.core.componentobj.join import Join
        from tecslib.core.componentobj.namespacepath import NamespacePath
        from tecslib.core.bnf import Token
        from tecslib.core.expression import Expression

        # set_require_join は2度呼び出される
        # 2度目は post コードを生成した後       #####  いったん見合わせ（重複エラーを見逃す）
        # if @require_joined_list[ cp_name ] then
        #   return
        # else
        #   @require_joined_list[ cp_name ] = true
        # end

        dbgPrint("set_require_join: {}.{} = {}.{}\n".format(
            self.name, cp_name, cell_or_ct.get_name(), port.get_name()))

        if type(cell_or_ct) is Celltype:
            # print "DOMAIN: not considered\n"
            cell = cell_or_ct.get_singleton_cell(self.region)
            if cell is None:
                self.cdl_error("S1025 not found reachable cell for require \'$1\' in celltype \'$2\'",
                               port.get_name(), cell_or_ct.get_name())
                return
        else:
            # require: cell で指定
            cell = cell_or_ct
            if self.region.distance(cell.get_region()) is None:
                self.cdl_error("S1026 required cell \'$1\' not reachable", cell.get_name())

        if self.join_list.get_item(cp_name):
            self.cdl_warning("W1003 $1 : require call port overridden in $2", cp_name, self.name)
        else:
            # require の join を生成(呼び口の結合)
#      rhs = Expression.new( [ :OP_DOT, [ :IDENTIFIER, Token.new( cell.get_name, nil, nil, nil ) ],
            nsp = NamespacePath(cell.get_name(), False, cell.get_namespace())
            nsp.set_locale(self.locale)
            rhs = Expression(["OP_DOT", ["IDENTIFIER", nsp],
                              Token(port.get_name(), None, None, None)], self.locale)   #1
            join = Join(cp_name, None, rhs, self.locale)
            self.new_join_inst(join)

            join.set_definition(self.celltype.find(join.get_name()))

    #=== Cell# Join の definition の設定とチェック
    # STAGE: S
    # 結合の意味チェック
    def set_definition_join(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        if self.celltype is None:    # 既にエラー：打ち切る
            return
        if self.b_defined is False:  # プロトタイプ宣言のみ
            return
        if self.b_checked is True:  # 既に設定（チェック）済み
            return

        dbgPrint("set_definition_join in {}\n".format(self.name))

        # relay allocator をたどって再入しないよう、先頭で @b_checked を true にする
        self.b_checked = True

        if not self.f_cloned:
            self.check_restrict_list()

            # compoiste セルのクローンされたものは、set_definition 不要
            # 元の join は既に definition されている
            # 元のセルにおいて、代入チェックされているので、二重にチェック(through適用)されてしまう
            for join in self.join_list.get_items():
                dbgPrint(" set_definition_join: checking {}.{}\n".format(self.name, join.get_name()))
                if join.get_array_member():
                    port = self.celltype.find(join.get_name())
                    for am in join.get_array_member2():
                        if am is None:   # 未結合の場合、エラーチェックは check_join
                            if port and not port.is_optional():
                                # テスト用にエラーメッセージ出力
                                # cdl_error( "TEMPORAL set_definition_join: uninitialized array member"  )
                                pass
                            continue
                        am.set_definition(port)
                else:
                    dbgPrint("set_definition_join: {}.{} celltype={}\n".format(
                        self.name, join.get_name(), self.celltype.get_name()))
                    join.set_definition(self.celltype.find(join.get_name()))

        # リレー join は through プラグイン生成後にしかできない
        # through 後に結合先が入れ替えられる
        self.create_relay_allocator_join()

        # composite セルの展開
        if not self.in_composite and not self.f_cloned and type(self.celltype) is CompositeCelltype:
            # composite セルタイプ内の composite は展開しない
            # compoiste セル展開中の composite は展開しない (CompositeCelltype::expand 内で再帰的に expnad)
            self.expand()

    #=== Cell# composite セルの展開
    # このセルが composite セルタイプ
    def expand(self):
        from tecslib.core.componentobj.compositecelltype import CompositeCelltype

        #debug
        dbgPrint("=====    expanding   {}     =====\n".format(self.name))

        # composite celltype の cell を展開
        self.cell_list, self.cell_list2 = self.celltype.expand(
            self.name, self.global_name, self.NamespacePath, self.join_list, self.region, self.plugin, self.locale)

        # プロトタイプが参照されている場合、子も参照されていることにする
        if self.f_ref:
            dbgPrint("expand: set_f_ref\n")
            self.set_f_ref()

    #=== Cell#内部セルの受け口添数最大値を設定
    def set_max_entry_port_inner_cell(self):
        if self.cell_list is None:
            return

        dbgPrint("set_max_entry_port_inner_cell name={} entry_array_max_subscript.len={}\n".format(
            self.name, len(self.entry_array_max_subscript)))

        # プロトタイプ宣言で設定されていたものを反映する
        for port, name in self.entry_array_max_subscript.items():
            dbgPrint("set_entry_inner_port_max_subscript( {}, {} )\n".format(port, name))
            self.set_entry_inner_port_max_subscript(port, name)

    #=== Cell#restrict を追加
    def add_restrict(self, entry_name, func_name, region_name_list):
        from tecslib.core.componentobj.namespace import Namespace
        from tecslib.core.componentobj.region import Region

        if self.restrict_list.get(entry_name) is None:
            self.restrict_list[entry_name] = {}
            self.restrict_list2[entry_name] = {}
        if self.restrict_list[entry_name].get(func_name) is None:
            self.restrict_list[entry_name][func_name] = []
            self.restrict_list2[entry_name][func_name] = []
        for rp in region_name_list:
            self.restrict_list[entry_name][func_name].append(rp)
            # p "Class: " + rp.to_s
            obj = Namespace.find(rp)
            if isinstance(obj, Region):
                self.restrict_list2[entry_name][func_name].append(obj.get_domain_root())
            else:
                self.cdl_error("S9999 $1 not found or not region", str(rp))

    #=== Cell#check_restrict_list
    def check_restrict_list(self):
        from tecslib.core.componentobj.namespace import Namespace
        from tecslib.core.componentobj.region import Region

        # p "check_restrict_list"
        for entry_name, func_hash in self.restrict_list.items():
            for func_name, region_list in func_hash.items():
                for rp in region_list:
                    obj = Namespace.find(rp)
                    if isinstance(obj, Region):
                        if obj.get_domain_root() != self.region.get_domain_root():
                            pass
                        else:
                            self.cdl_info("I9999 $1: restrict calling domain to $2, which is same domain as the cell locates",
                                          self.name, str(rp))
                            # restrict を同じドメインを指定してもよいこととする (HRP3)
                            # KernelDoamin 内のセルに対し、KernelDomain に restrict している場合、
                            # 無所属経由で結合されているが、KernelDomain から呼出すことを想定した許可
                    else:
                        self.cdl_error("S9999 $1 not region", str(rp))

    #=== Cell#callable?
    def callable(self, callee_cell, entry_name, func_name):
        # p "callable? #{@name}"
        res = callee_cell.callable_from(entry_name, func_name, self)
        dbgPrint("callable? {}.{}.{} from {} is {}\n".format(
            callee_cell.get_namespace_path(), entry_name, func_name, self.NamespacePath, res))
        return res

    #=== Cell#callable_from? (private)
    def callable_from(self, entry_name, func_name, caller_cell):
        self.b_restrict_referenced = True
        if len(self.restrict_list) == 0:
            return True

        dr = caller_cell.get_region().get_domain_root()
        if self.restrict_list.get(entry_name):
            if self.restrict_list[entry_name].get(func_name):
                for region in self.restrict_list2[entry_name][func_name]:
                    if dr is region:
                        return True
            elif self.restrict_list[entry_name].get(None):
                for region in self.restrict_list2[entry_name][None]:
                    if dr is region:
                        return True
            else:
                return False
        else:
            return False

    #=== Cell#get_callable_regions( entry_name, func_name )
    # func_name=nil の場合、entry_name の可否をチェックする
    # nil が返る場合、制限されていないことを意味する
    # 返された、受け口、受け口関数へ
    def get_restricted_regions(self, entry_name, func_name):
        # p "get_restricted_regions #{@name}"
        self.b_restrict_referenced = True
        if self.restrict_list.get(entry_name):
            if self.restrict_list[entry_name].get(func_name):
                return self.restrict_list2[entry_name][func_name]
            else:
                return self.restrict_list2[entry_name].get(None)
        return None

    #=== Cell#has_ineffective_restrict_specifier
    # restrict 指定子が指定されていて、参照されていない場合 true
    # 参照は、HRPSVCPlugin のみ
    def has_ineffective_restrict_specifier(self):
        if len(self.restrict_list) != 0 and self.b_restrict_referenced is False:
            return True
        else:
            return False

    def show_tree(self, indent):
        from tecslib.core.componentobj.port import Port
        from tecslib.rubylib import rb

        print("  " * indent, end="")
        print("Cell: name: {} in_composite: {} def: {} ref: {} cloned: {}".format(
            self.name, rb.to_s(self.in_composite), rb.to_s(self.b_defined),
            rb.to_s(self.f_ref), rb.to_s(self.f_cloned)))
        print("  " * (indent + 1), end="")
        print("Cell locale: {}@{}#{}".format(self.name, self.locale[0], self.locale[1]))
        print("  " * (indent + 1), end="")
        print("id: {}  global_name: {}  region: {} plugin: {} {}".format(
            self.id, self.global_name, self.region.get_name(),
            rb.class_name(self.plugin), rb.inspect(self)))
        print("  " * (indent + 1), end="")
        print("namespace_path: {}".format(self.NamespacePath))

        if self.celltype:
            print("  " * (indent + 1), end="")
            print("celltype: {}".format(self.celltype.get_name()))
        self.join_list.show_tree(indent + 1)
        for port, num in self.entry_array_max_subscript.items():
            print("  " * (indent + 1), end="")
            print("entry array {}: max subscript={}".format(port.get_name(), num))
        if self.cell_list is not None:   # ここで @cell_list が nil なのは Bug
            print("  " * (indent + 1), end="")
            print("cloned cell list:")
            for n, c in self.cell_list.items():
                print("  " * (indent + 2), end="")
                print("inner cell : {} = {}".format(n, c.get_name()))
        if self.compositecelltypejoin_list:
            for cj in self.compositecelltypejoin_list.get_items():
                cj.show_tree(indent + 1)
        if len(self.alloc_list) > 0:
            print("  " * (indent + 1), end="")
            print("allocator list: ")
            for a in self.alloc_list:
                cp_name = Sym("{}_{}_{}".format(a[0 + 1], a[2 + 1], a[3 + 1]))
                if a[1 + 1]:
                    # subscript = "[#{a[1+1].eval_const nil}]"
                    subscript = "[{}]".format(a[1 + 1])
                else:
                    subscript = ""
                # アロケータ呼び口の結合を生成
                print("  " * (indent + 2), end="")
                print("{}{} = {}".format(cp_name, subscript, a[4 + 1]))
        for port, count in self.referenced_port_list.items():
            print("  " * (indent + 1), end="")
            print("{} : {} times referenced".format(port.get_name(), count))

    @classmethod
    def new_join(cls, join, b_regular=False):
        cls.current_object.new_join_inst(join, b_regular)
