# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2014 by TOPPERS Project TECS-WG
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/ATK1AlarmPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: ATK1AlarmPlugin.rb 2955 2018-05-07 10:23:26Z okuma-top $
#

import re

from tecslib.core import globals as G
from tecslib.core.generate import AppFile
from tecslib.core.plugin import CFile
from tecslib.plugin.CelltypePlugin import CelltypePlugin
from tecslib.rubylib.rb import to_s
from tecslib.rubylib.symbol import Sym


def _strip_dq(s):
    return re.sub(r'^"(.*)"$', r"\1", to_s(s))


def _rhs_list(join):
    rhs = join.get_rhs()
    if isinstance(rhs, (list, tuple)):
        return rhs
    return [rhs]


class ATK1AlarmPlugin(CelltypePlugin):

    def __init__(self, celltype, option):
        super().__init__(celltype, option)

    def new_cell(self, cell):
        pass

    def gen_factory(self, file):
        file2 = CFile.open("{}/ALARM_tecsgen.oil".format(G.gen), "w")

        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue

            file2.print("\tALARM {} {{\n".format(to_s(cell.get_name())))

            join = cell.get_join_list().get_item(Sym("counter"))
            if join:
                file2.print("\t\tCOUNTER = {};\n".format(_strip_dq(join.get_rhs())))

            str_ = None
            join = cell.get_join_list().get_item(Sym("action"))
            if join:
                str_ = _strip_dq(join.get_rhs())

            if str_ == "SETEVENT":
                file2.print("\t\tACTION = {} {{\n".format(str_))
                join2 = cell.get_join_list().get_item(Sym("task"))
                if join2:
                    file2.print("\t\t\tTASK = {};\n".format(_strip_dq(join2.get_rhs())))
                join2 = cell.get_join_list().get_item(Sym("event"))
                if join2:
                    file2.print("\t\t\tEVENT = {};\n".format(_strip_dq(join2.get_rhs())))
                file2.print("\t\t};\n")
            elif str_ == "ACTIVATETASK":
                file2.print("\t\tACTION = {} {{\n".format(str_))
                join2 = cell.get_join_list().get_item(Sym("task"))
                if join2:
                    file2.print("\t\t\tTASK = {};\n".format(_strip_dq(join2.get_rhs())))
                file2.print("\t\t};\n")
            elif str_ == "ALARMCALLBACK":
                file2.print("\t\tACTION = {} {{\n".format(str_))
                join2 = cell.get_join_list().get_item(Sym("callbackName"))
                if join2:
                    file2.print(
                        "\t\t\tALARMCALLBACKNAME = {};\n".format(to_s(join2.get_rhs()))
                    )
                file2.print("\t\t};\n")

            join = cell.get_join_list().get_item(Sym("autoStart"))
            if join:
                str_ = to_s(join.get_rhs())

            if str_ == "TRUE":
                file2.print("\t\tAUTOSTART = TRUE {\n")
                join2 = cell.get_join_list().get_item(Sym("alarmTime"))
                if join2:
                    file2.print(
                        "\t\t\tALARMTIME = {};\n".format(to_s(join2.get_rhs()))
                    )
                join2 = cell.get_join_list().get_item(Sym("cycleTime"))
                if join2:
                    file2.print(
                        "\t\t\tCYCLETIME = {};\n".format(to_s(join2.get_rhs()))
                    )
                join2 = cell.get_join_list().get_item(Sym("appMode"))
                if join2:
                    for mode in _rhs_list(join2):
                        file2.print(
                            "\t\t\tAPPMODE = {};\n".format(_strip_dq(mode))
                        )
                file2.print("\t\t};\n")
            else:
                file2.print("\t\tAUTOSTART = FALSE;\n")

            file2.print("\t};\n")
            file2.print("\n")

        file2.close()

        file = AppFile.open("{}/tAlarm_tecsgen.{}".format(G.gen, G.c_suffix))
        file.print("\n/* Generated by ATK1AlarmPlugin */\n")
        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue
            name_array = self.celltype.get_name_array(cell)
            join2 = cell.get_join_list().get_item(Sym("callbackName"))
            if join2:
                str_ = _strip_dq(join2.get_rhs())
                file.print(
                    "ALARMCALLBACK( {} );\n"
                    "ALARMCALLBACK( {} )\n"
                    "{{\n"
                    "    CELLCB *p_cellcb = {};\n"
                    "    cBody_main();\n"
                    "}}\n"
                    "\n".format(str_, str_, name_array[8])
                )

        file.close()
