# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2014 by TOPPERS Project TECS-WG
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/ATK1KernelPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: ATK1KernelPlugin.rb 2955 2018-05-07 10:23:26Z okuma-top $
#

import re

from tecslib.core import globals as G
from tecslib.core.generate import AppFile
from tecslib.core.plugin import CFile
from tecslib.plugin.CelltypePlugin import CelltypePlugin
from tecslib.rubylib.rb import to_s
from tecslib.rubylib.symbol import Sym


def _strip_dq(s):
    return re.sub(r'^"(.*)"$', r"\1", to_s(s))


class ATK1KernelPlugin(CelltypePlugin):
    cell_list = []

    def __init__(self, celltype, option):
        super().__init__(celltype, option)

    def new_cell(self, cell):
        ATK1KernelPlugin.cell_list.append(cell)

    def gen_factory(self, file):
        file2 = CFile.open("{}/Kernel_tecsgen.oil".format(G.gen), "w")

        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue

            file2.print("\tOS {} {{\n".format(to_s(cell.get_name())))

            join = cell.get_join_list().get_item(Sym("status"))
            if join:
                str_ = _strip_dq(join.get_rhs())
                file2.print("\t\tSTATUS = {};\n".format(str_))

            for attr, oil in (
                ("useStartupHook", "STARTUPHOOK"),
                ("useErrorHook", "ERRORHOOK"),
                ("useShutdownHook", "SHUTDOWNHOOK"),
                ("usePreTaskHook", "PRETASKHOOK"),
                ("usePostTaskHook", "POSTTASKHOOK"),
                ("useGetServiceId", "USEGETSERVICEID"),
                ("useParameterAccess", "USEPARAMETERACCESS"),
                ("useResourceScheduler", "USERESSCHEDULER"),
            ):
                join = cell.get_join_list().get_item(Sym(attr))
                if join:
                    file2.print("\t\t{} = {};\n".format(oil, to_s(join.get_rhs())))

            file2.print("\t};\n\n")

        file2.close()

        file2 = AppFile.open("{}/tKernel_tecsgen.{}".format(G.gen, G.c_suffix))
        file2.print("\n/* Generated by ATK1KernelPlugin */\n\n")
        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue
            name_array = self.celltype.get_name_array(cell)

            join = cell.get_join_list().get_item(Sym("useStartupHook"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file2.print(
                    "#ifdef USE_STARTUPHOOK\n"
                    "void StartupHook(void)\n"
                    "{{\n"
                    "/*    CELLCB *p_cellcb = {}; */\n"
                    "    INT32 i;\n"
                    "    for(i = 0; i < N_CP_cStartupHookBody; i++){{\n"
                    "        cStartupHookBody_main(i);\n"
                    "    }}\n"
                    "}}\n"
                    "#endif /* USE_STARTUPHOOK */\n".format(name_array[8])
                )

            join = cell.get_join_list().get_item(Sym("useErrorHook"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file2.print(
                    "#ifdef USE_ERRORHOOK\n"
                    "void ErrorHook(StatusType ercd)\n"
                    "{{\n"
                    "/*    CELLCB *p_cellcb = {}; */\n"
                    "    cErrorHookBody_main( ercd );\n"
                    "}}\n"
                    "#endif /* USE_ERRORHOOK */\n"
                    "\n".format(name_array[8])
                )

            join = cell.get_join_list().get_item(Sym("useShutdownHook"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file2.print(
                    "#ifdef USE_SHUTDOWNHOOK\n"
                    "void ShutdownHook(StatusType ercd)\n"
                    "{{\n"
                    "/*    CELLCB *p_cellcb = {}; */\n"
                    "    INT32 i;\n"
                    "    for(i = 0; i < N_CP_cShutdownHookBody; i++){{\n"
                    "        cShutdownHookBody_main( i, ercd );\n"
                    "    }}\n"
                    "}}\n"
                    "#endif /* USE_SHUTDOWNHOOK */\n"
                    "\n".format(name_array[8])
                )

            join = cell.get_join_list().get_item(Sym("usePreTaskHook"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file2.print(
                    "#ifdef USE_PRETASKHOOK\n"
                    "void PreTaskHook(void)\n"
                    "{{\n"
                    "/*    CELLCB *p_cellcb = {}; */\n"
                    "    cPreTaskHookBody_main();\n"
                    "}}\n"
                    "#endif /* USE_PRETASKHOOK */\n"
                    "\n".format(name_array[8])
                )

            join = cell.get_join_list().get_item(Sym("usePostTaskHook"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file2.print(
                    "#ifdef USE_POSTTASKHOOK\n"
                    "void PostTaskHook(void)\n"
                    "{{\n"
                    "/*    CELLCB *p_cellcb = {}; */\n"
                    "    cPostTaskHookBody_main();\n"
                    "}}\n"
                    "#endif /* USE_POSTTASKHOOK */\n"
                    "\n".format(name_array[8])
                )

        file2.close()

    @classmethod
    def gen_post_code(cls, file):
        for cell in cls.cell_list:
            join = cell.get_join_list().get_item(Sym("useResourceScheduler"))
            if join and to_s(join.get_rhs()) == "TRUE":
                file.print(
                    'cell tResource RES_SCHEDULER {\n'
                    '\tproperty = "STANDARD";\n'
                    "};\n"
                )
