# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2014 by TOPPERS Project TECS-WG
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/ATK1TaskPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: ATK1TaskPlugin.rb 2955 2018-05-07 10:23:26Z okuma-top $
#

import re

from tecslib.core import globals as G
from tecslib.core.generate import AppFile
from tecslib.core.plugin import CFile
from tecslib.plugin.CelltypePlugin import CelltypePlugin
from tecslib.rubylib.rb import to_s
from tecslib.rubylib.symbol import Sym


def _strip_dq(s):
    return re.sub(r'^"(.*)"$', r"\1", to_s(s))


def _rhs_list(join):
    rhs = join.get_rhs()
    if isinstance(rhs, (list, tuple)):
        return rhs
    return [rhs]


class ATK1TaskPlugin(CelltypePlugin):

    def __init__(self, celltype, option):
        super().__init__(celltype, option)

    def new_cell(self, cell):
        pass

    def gen_factory(self, file):
        file2 = CFile.open("{}/TASK_tecsgen.oil".format(G.gen), "w")

        extended_task_count = 1

        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue

            file2.print("\tTASK {} {{\n".format(to_s(cell.get_name())))

            join = cell.get_join_list().get_item(Sym("autoStart"))
            if join:
                str_ = to_s(join.get_rhs())
                if str_ == "TRUE":
                    join2 = cell.get_join_list().get_item(Sym("appMode"))
                    if join2:
                        file2.print("\t\tAUTOSTART = TRUE {\n")
                        for mode in _rhs_list(join2):
                            file2.print("\t\t\tAPPMODE = {};\n".format(_strip_dq(mode)))
                        file2.print("\t\t};\n")
                    else:
                        file2.print("\t\tAUTOSTART = TRUE;\n")
                elif str_ == "FALSE":
                    file2.print("\t\tAUTOSTART = FALSE;\n")

            join = cell.get_join_list().get_item(Sym("priority"))
            if join:
                file2.print("\t\tPRIORITY = {};\n".format(to_s(join.get_rhs())))

            join = cell.get_join_list().get_item(Sym("activation"))
            if join:
                file2.print("\t\tACTIVATION = {};\n".format(to_s(join.get_rhs())))

            join = cell.get_join_list().get_item(Sym("schedule"))
            if join:
                file2.print("\t\tSCHEDULE = {};\n".format(_strip_dq(join.get_rhs())))

            join = cell.get_join_list().get_item(Sym("event"))
            if join:
                for evt in _rhs_list(join):
                    str_ = _strip_dq(evt)
                    if str_ != "OMISSIBLE":
                        file2.print("\t\tEVENT = {};\n".format(str_))
                for evt in _rhs_list(join):
                    str_ = _strip_dq(evt)
                    if str_ != "OMISSIBLE":
                        cell.set_specified_id(extended_task_count)
                        extended_task_count += 1
                        break

            join = cell.get_join_list().get_item(Sym("resource"))
            if join:
                for res in _rhs_list(join):
                    str_ = _strip_dq(res)
                    if str_ != "OMISSIBLE":
                        file2.print("\t\tRESOURCE = {};\n".format(str_))

            join = cell.get_join_list().get_item(Sym("message"))
            if join:
                for msg in _rhs_list(join):
                    str_ = _strip_dq(msg)
                    if str_ != "OMISSIBLE":
                        file2.print("\t\tMESSAGE = {};\n".format(str_))

            join = cell.get_join_list().get_item(Sym("stackSize"))
            if join:
                file2.print("\t\tSTACKSIZE = {};\n".format(to_s(join.get_rhs())))

            file2.print("\t};\n")
            file2.print("\n")

        file2.close()

        file = AppFile.open("{}/tTask_tecsgen.{}".format(G.gen, G.c_suffix))
        file.print("\n/* Generated by ATK1TaskPlugin */\n")
        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue
            name_array = self.celltype.get_name_array(cell)
            file.print(
                "TASK({})\n"
                "{{\n"
                "    CELLCB *p_cellcb = {};\n"
                "    cBody_main();\n"
                "    terminate();\n"
                "}}\n"
                "\n".format(to_s(cell.get_name()), name_array[8])
            )

        file.close()
