# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2014 by TOPPERS Project TECS-WG
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/ATK1ISRPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: ATK1ISRPlugin.rb 2955 2018-05-07 10:23:26Z okuma-top $
#

import re

from tecslib.core import globals as G
from tecslib.core.generate import AppFile
from tecslib.core.plugin import CFile
from tecslib.plugin.CelltypePlugin import CelltypePlugin
from tecslib.rubylib.rb import to_s
from tecslib.rubylib.symbol import Sym


def _strip_dq(s):
    return re.sub(r'^"(.*)"$', r"\1", to_s(s))


def _rhs_list(join):
    rhs = join.get_rhs()
    if isinstance(rhs, (list, tuple)):
        return rhs
    return [rhs]


class ATK1ISRPlugin(CelltypePlugin):

    def __init__(self, celltype, option):
        super().__init__(celltype, option)

    def new_cell(self, cell):
        pass

    def gen_factory(self, file):
        file2 = CFile.open("{}/ISR_tecsgen.oil".format(G.gen), "w")

        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue

            file2.print("\tISR {} {{\n".format(to_s(cell.get_name())))

            join = cell.get_join_list().get_item(Sym("category"))
            if join:
                file2.print("\t\tCATEGORY = {};\n".format(to_s(join.get_rhs())))

            join = cell.get_join_list().get_item(Sym("priority"))
            if join:
                file2.print("\t\tPRIORITY = {};\n".format(to_s(join.get_rhs())))

            join = cell.get_join_list().get_item(Sym("entryNumber"))
            if join:
                file2.print("\t\tENTRY = {};\n".format(to_s(join.get_rhs())))

            join2 = cell.get_join_list().get_item(Sym("resource"))
            if join2:
                for res in _rhs_list(join2):
                    file2.print("\t\tRESOURCE = {};\n".format(_strip_dq(res)))

            join2 = cell.get_join_list().get_item(Sym("message"))
            if join2:
                for msg in _rhs_list(join2):
                    file2.print("\t\tMESSAGE = {};\n".format(_strip_dq(msg)))

            file2.print("\t};\n")
            file2.print("\n")

        file2.close()

        file = AppFile.open("{}/tISR_tecsgen.{}".format(G.gen, G.c_suffix))
        file.print("\n/* Generated by ATK1ISRPlugin */\n")
        for cell in self.celltype.get_cell_list():
            if not cell.is_generate():
                continue
            name_array = self.celltype.get_name_array(cell)
            join2 = cell.get_join_list().get_item(Sym("category"))
            if join2:
                str_ = to_s(join2.get_rhs())
                if str_ == "1":
                    file.print("#if defined( OMIT_ISR1_ENTRY )\n")
                    file.print(
                        "/* ISR1入り口未生成時は本関数を割込み関数指定する  */\n"
                    )
                    file.print(
                        "#pragma INTERRUPT  {}\n"
                        "#endif  /* OMIT_ISR1_ENTRY  */\n"
                        "void  RxHwSerialInt( void );\n"
                        "void\n"
                        "RxHwSerialInt( void )\n".format(to_s(cell.get_name()))
                    )
                else:
                    file.print("ISR({})\n".format(to_s(cell.get_name())))

            file.print(
                "{{\n"
                "    CELLCB *p_cellcb = {};\n"
                "    cBody_main();\n"
                "}}\n"
                "\n".format(name_array[8])
            )

        file.close()
