# -*- coding: utf-8 -*-
#
#  C2TECSBridgePlugin.rb の Python 移植

from tecslib.core import globals as G
from tecslib.core.plugin import CFile
from tecslib.plugin.SignaturePlugin import SignaturePlugin
from tecslib.rubylib.symbol import Sym


def _set_prefix(obj, rhs):
    obj.set_prefix(rhs)


def _set_suffix(obj, rhs):
    obj.set_suffix(rhs)


def _set_header_name(obj, rhs):
    obj.set_header_name(rhs)


class C2TECSBridgePlugin(SignaturePlugin):

    C2TECSBridgePluginArgProc = {
        "prefix": _set_prefix,
        "suffix": _set_suffix,
        "header_name": _set_header_name,
    }

    signature_list = {}

    def __init__(self, signature, option):
        super().__init__(signature, option)
        self.signature = signature
        self.header_name = "{}/C2TECS_{}.h".format(G.gen, self.signature.get_global_name())
        self.prefix = ""
        self.suffix = ""
        self.celltype_name = Sym("t{}".format(self.signature.get_global_name()))
        self.plugin_arg_check_proc_tab = C2TECSBridgePlugin.C2TECSBridgePluginArgProc
        self.parse_plugin_arg()

    def gen_cdl_file(self, file):
        gname = self.signature.get_global_name()
        if C2TECSBridgePlugin.signature_list.get(gname):
            C2TECSBridgePlugin.signature_list[gname].append(self)
            self.cdl_warning("C2TW001 signature '$1' duplicate. ignored current one", self.signature.get_namespace_path())
            return
        C2TECSBridgePlugin.signature_list[gname] = [self]
        print("  C2TECSBridgePlugin: [celltype] C2TECS::{}. Create cell then join the call port 'cCall' to the target cell".format(
            self.celltype_name))
        file.print("namespace nC2TECS{\n  [singleton, active]\n  celltype %s {\n    call %s cCall;\n  };\n};\n" % (
            self.celltype_name, self.signature.get_namespace_path()))

    @classmethod
    def gen_post_code(cls, file):
        pass

    def gen_ep_func_body(self, file, b_singleton, ct_name, global_ct_name, sig_name, ep_name, func_name, func_global_name, func_type, params):
        pass

    def gen_postamble(self, file, b_singleton, ct_name, global_name):
        header_file = CFile.open(self.header_name, "w")
        header_comment = """/*
 * This file was generated by C2TECSBridgePlugin and has prototype
 * decalarations of functions in signature '{}'
 */

""".format(self.signature.get_namespace_path())
        file.print(header_comment)
        header_file.print(header_comment)
        header_file.print("""#ifndef {}__h
#define {}__h

/*
 * function prototype declarations
 *    signature: '{}'
 *
 * These functions can be called from C sources directly.
 * If function name collides, please consider to specify 'prefix' option for C2TECSBridgePlugin.
 */
""".format(self.signature.get_global_name(), self.signature.get_global_name(), self.signature.get_namespace_path()))

        for func_head in self.signature.get_function_head_array():
            func_name = func_head.get_name()
            ret_type = func_head.get_return_type()
            params = func_head.get_paramlist().get_items()
            rts = ret_type.get_type_str()
            file.print(rts + "\n")
            header_file.print("%-16s" % rts)
            sig = self.prefix + str(func_name) + self.suffix
            file.print(sig + "(")
            header_file.print(sig + "(")
            delim = ""
            for param in params:
                chunk = delim + param.get_type().get_type_str() + " " + str(param.get_name()) + param.get_type().get_type_str_post()
                file.print(chunk)
                header_file.print(chunk)
                delim = ","
            file.print(" )\n{\n")
            header_file.print(" );\n")
            if not ret_type.is_void():
                file.print("  " + rts + "  retval;\n")
                file.print("  retval = ")
            else:
                file.print("  ")
            file.print("cCall_" + str(func_name) + "(")
            delim = ""
            for param in params:
                file.print(delim + str(param.get_name()))
                delim = ","
            file.print(" );\n")
            if not ret_type.is_void():
                file.print("  return retval;\n")
            file.print("}\n\n")

        header_file.print("\n#endif /* {}__h */\n\n".format(self.signature.get_global_name()))
        header_file.close()

    def set_prefix(self, rhs):
        self.prefix = str(rhs)

    def set_suffix(self, rhs):
        self.suffix = str(rhs)

    def set_header_name(self, rhs):
        self.header_name = "{}/{}".format(G.gen, rhs)
        if not self.header_name.endswith(".h"):
            self.header_name += ".h"
