# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2024-2026 by TOPPERS Project
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/DataPumpHolderPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: DataPumpHolderPlugin.rb 3300 2026-01-04 12:29:45Z okuma-top $
#

import re
import sys

from tecslib.core import globals as G
from tecslib.core.plugin import CFile
from tecslib.core.syntaxobj.cdlstring import CDLString
from tecslib.core.types import PtrType
from tecslib.plugin.CelltypePlugin import CelltypePlugin


class DataPumpHolderPlugin(CelltypePlugin):

    count = 0

    def __init__(self, celltype, option):
        super().__init__(celltype, option)
        self.celltype = celltype
        self.plugin_arg_str = CDLString.remove_dquote(option)
        self.plugin_arg_list = {}
        self.cell_list = []

        self.namespace_pre = celltype.get_namespace().get_global_name()
        self.signature_pre = re.sub(r'^t', 's', str(celltype.get_name()))
        self.signature_prefix = "{}_{}".format(self.namespace_pre, self.signature_pre)
        self.celltype_prefix = celltype.get_global_name()
        self.celltype_cdl_name = "{}_celltype.cdl".format(celltype.get_global_name())
        self.signature_cdl_name = "{}_signature.cdl".format(celltype.get_global_name())

        self.attr_list = celltype.get_attribute_list()
        self.var_list = celltype.get_var_list()

        signame = re.sub(r'^t', 's', str(celltype.get_name()))
        self.get_signature = "{}GetSignature".format(signame)
        self.set_signature = "{}SetSignature".format(signame)
        self.datapump_celltype = "{}DataPump".format(celltype.get_name())
        self.dataholder_celltype = "{}DataHolder".format(celltype.get_name())
        self.datapumpholder_celltype = "{}DataPumpHolder".format(celltype.get_name())
        self.set_signature_async = "{}SetSignatureAsync".format(signame)
        self.sync_adaptor_celltype = "{}SyncAdaptor".format(celltype.get_name())
        self.async_adaptor_celltype = "{}AsyncAdaptor".format(celltype.get_name())
        self.gen_get_set_signature()
        self.gen_pump_holder_celltype()

    def new_cell(self, cell):
        self.cell_list.append(cell)

    @classmethod
    def gen_post_code(cls, file):
        pass

    def gen_factory(self, file):
        pass

    def gen_cdl_file(self, file):
        file.print(
            "/*\n"
            "* This file is generated by DataPumpHolderPlugin from {}\n"
            "*/\n"
            "\n"
            "// import DataPumpHolder.cdl which imports rpc.cdl and kernel.cdl\n"
            "import( <DataPumpHolder.cdl> );\n"
            "\n"
            "// signature definition for data set & get in {}\n".format(
                self.celltype.get_namespace_path(),
                self.celltype.get_namespace_path()))
        file.print('import( "{}" );\n'.format(self.signature_cdl_name))
        file.print('import( "{}" );\n'.format(self.celltype_cdl_name))

    def gen_get_set_signature(self):
        sys.stdout.write(
            "[DataPumpHolderPlugin] for DATA {}\n"
            "      signatures in      {}/{}\n"
            "                for  GET {}\n"
            "                for  SET {}\n"
            "      celltypes  in      {}/{}\n"
            "                for PUMP {}\n"
            "              for HOLDER {}\n"
            "          for PUMPHOLDER {}\n".format(
                self.celltype.get_name(),
                G.gen, self.signature_cdl_name,
                self.get_signature, self.set_signature,
                G.gen, self.celltype_cdl_name,
                self.datapump_celltype,
                self.dataholder_celltype,
                self.datapumpholder_celltype))

        f = CFile.open("{}/{}_signature.cdl".format(G.gen, self.celltype.get_global_name()), "w")
        f.print(
            "/*\n"
            "* This file is generated by DataPumpHolderPlugin from {}\n"
            "*/\n"
            "\n"
            "// Get signature for {}\n"
            "//   Get signature is used for\n"
            "//      DataPump        cPubSide\n"
            "//      DataHolder      eSubSide\n"
            "//      DataPumpHolder  cPubSide, eSubSide\n"
            "signature {}{{\n"
            "    // Sync Control functions\n"
            "    ER  waitForNewData(void);    // This function may block.\n"
            "    ER  dataReadDone(void);\n"
            "\n"
            "    // Data Access functions\n".format(
                self.celltype.get_namespace_path(),
                self.celltype.get_namespace_path(),
                self.get_signature))
        for decl in list(self.attr_list) + list(self.var_list):
            ptr = "*" if decl.get_ptr_level() == 0 else ""
            if decl.get_size_is():
                spec = "[out, size_is({})]".format(decl.get_size_is())
            else:
                spec = "[out]"
            f.print(
                "    ER get_{0}( {1}{2}\t{3}{0}{4} );\n".format(
                    decl.get_identifier(),
                    spec,
                    decl.get_type().get_type_str(),
                    ptr,
                    decl.get_type().get_type_str_post()))
        f.print("};\n")

        f.print(
            "\n"
            "// Set signature for {}\n"
            "//   Set signature is used for\n"
            "//      DataPump        cSubSide\n"
            "//      DataHolder      ePubSide\n"
            "signature {}{{\n"
            "    // Sync Control functions\n"
            "    ER  waitForReadDone(void);    // This function may block.\n"
            "    [oneway]\n"
            "      ER  newDataReady(void);\n"
            "\n"
            "    // Data Set functions\n".format(
                self.celltype.get_namespace_path(), self.set_signature))
        for decl in list(self.attr_list) + list(self.var_list):
            if decl.get_size_is():
                spec = "[in, size_is({})]".format(decl.get_size_is())
            else:
                spec = "[in]"
            f.print(
                "    [oneway]\n"
                "      ER set_{0}( {1}const {2}\t{0}{3} );\n".format(
                    decl.get_identifier(),
                    spec,
                    decl.get_type().get_type_str(),
                    decl.get_type().get_type_str_post()))
        f.print("};\n")

        f.print(
            "\n"
            "// Set signature for {}\n"
            "//   This Set signature is used for buffer asynchronous buffer communication.\n"
            "//   waitForReadDone is to notify new data arraival and\n"
            "//         executed asynchronously in client side and synchronously in server side.\n"
            "signature {}{{\n"
            "    // Sync Control functions (async for RPC buffer)\n"
            "    [oneway]\n"
            "      ER  waitForReadDone(void);    // This function may block.\n"
            "    [oneway]\n"
            "      ER  newDataReady(void);\n"
            "\n"
            "    // Data Set functions\n".format(
                self.celltype.get_namespace_path(), self.set_signature_async))
        for decl in list(self.attr_list) + list(self.var_list):
            if decl.get_size_is():
                spec = "[in, size_is({})]".format(decl.get_size_is())
            else:
                spec = "[in]"
            f.print(
                "    [oneway]\n"
                "      ER set_{0}( {1}const {2}\t{0}{3} );\n".format(
                    decl.get_identifier(),
                    spec,
                    decl.get_type().get_type_str(),
                    decl.get_type().get_type_str_post()))
        f.print("};\n")
        f.close()

    def gen_pump_holder_celltype(self):
        f = CFile.open("{}/{}_celltype.cdl".format(G.gen, self.celltype.get_global_name()), "w")
        f.print(
            "/*\n"
            " * generated by DataPumpHolderPlugin\n"
            " * for celltype {0}\n"
            " * This includes celltypes {1}, {2} & {3}\n"
            " */\n"
            " \n"
            "//---------  Data Pump Celltype ---------\n"
            "celltype {1} {{\n"
            "  entry sPumpMain ePumpMain;\n"
            "  call {4} cPubSide;\n"
            "  call {5} cSubSide;\n"
            "}};\n"
            "\n"
            "//---------  Data Holder Celltype ---------\n"
            "celltype {2} {{\n"
            "  entry {4} eSubSide;\n"
            "  entry {5} ePubSide;\n"
            "  [optional]\n"
            "     call sEventflag    cEventflag;\n"
            "  var {{\n".format(
                self.celltype.get_namespace_path(),
                self.datapump_celltype,
                self.dataholder_celltype,
                self.datapumpholder_celltype,
                self.get_signature,
                self.set_signature))

        for decl in list(self.attr_list) + list(self.var_list):
            if decl.get_size_is():
                spec = "[size_is({})]\n        ".format(decl.get_size_is())
            else:
                spec = ""
            f.print("     {}{}\t{}{};\n".format(
                spec,
                decl.get_type().get_type_str(),
                decl.get_name(),
                decl.get_type().get_type_str_post()))
        f.print(
            "    int_t  status;\n"
            "  }};\n"
            "}};\n"
            "\n"
            "//---------  Data Holder Celltype ---------\n"
            "celltype {0} {{\n"
            "  [inline]\n"
            "    entry {1}     eIn;\n"
            "  call  {2} cOut;\n"
            "}};\n"
            "\n"
            "celltype {3} {{\n"
            "  [inline]\n"
            "    entry {2} eIn;\n"
            "  call  {1}         cOut;\n"
            "}};\n"
            "\n"
            "//---  Data Pump & Holder Celltype (composite) ---\n"
            "composite {4} {{\n"
            "  call  {5} cPubSide;\n"
            "  entry {5} eSubSide;\n"
            "  entry sPumpMain ePumpMain;\n"
            "\n"
            "  cell {6} Holder {{\n"
            "  }};\n"
            "  cell {7}   Pump {{\n"
            "    cSubSide =  Holder.ePubSide;\n"
            "    cPubSide => composite.cPubSide;\n"
            "  }};\n"
            "  composite.eSubSide => Holder.eSubSide;\n"
            "  composite.ePumpMain => Pump.ePumpMain;\n"
            "}};\n"
            "\n"
            "//---------  Data Holder Celltype Sync (composite) ---------\n"
            "composite {6}Sync {{\n"
            "  entry {1} ePubSide;\n"
            "  entry {5} eSubSide;\n"
            "\n"
            "  cell {6} Holder {{\n"
            "    cEventflag = Eventflag.eEventflag;\n"
            "  }};\n"
            "  cell tEventflag Eventflag{{\n"
            "    flagPattern = DATAHOLDER_EVFLAG_READ_DONE;  // Data Read Done status at beginning\n"
            "  }};\n"
            "  composite.eSubSide => Holder.eSubSide;\n"
            "  composite.ePubSide => Holder.ePubSide;\n"
            "}};\n"
            "\n"
            "//---------  Data Pump & Holder Celltype  Sync (composite) ---------\n"
            "composite {4}Sync {{\n"
            "  call  {5} cPubSide;\n"
            "  entry {5} eSubSide;\n"
            "  entry sPumpMain ePumpMain;\n"
            "\n"
            "  cell {6} Holder {{\n"
            "    cEventflag = Eventflag.eEventflag;\n"
            "  }};\n"
            "  cell {7}   Pump {{\n"
            "    cSubSide =  Holder.ePubSide;\n"
            "    cPubSide => composite.cPubSide;\n"
            "  }};\n"
            "  cell tEventflag Eventflag{{\n"
            "    flagPattern = 0;\n"
            "  }};\n"
            "  composite.eSubSide => Holder.eSubSide;\n"
            "  composite.ePumpMain => Pump.ePumpMain;\n"
            "}};\n"
            "\n"
            "//---------  Trasnparent RPC Marshaler Channel celltypes  --------\n"
            'generate(TransparentRPCSignaturePlugin, {2}, "PPAllocatorSize=128,DataPumpHolder=true");\n'
            "\n"
            "//---------  DataPumpBuffered ----------\n"
            "[active]\n"
            "composite {7}Buffered {{\n"
            "  attr {{\n"
            "    PRI     taskPriority;\n"
            "    size_t  stackSize = 4096;\n"
            '    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning\n'
            "  }};\n"
            "  call {1} cSubSide;\n"
            "  call {5} cPubSide;\n"
            "  entry sPumpMain ePumpMain;\n"
            "\n"
            "  cell {7} DataPump {{\n"
            "    cSubSide = SyncAdaptor.eIn;\n"
            "    cPubSide => composite.cPubSide;\n"
            "  }};\n"
            "  cell {0} SyncAdaptor{{\n"
            "    cOut = SetRPCChannel.eThroughEntry;\n"
            "  }};\n"
            "  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_{2}  SetRPCChannel{{\n"
            "    cCall = AsyncAdaptor.eIn;\n"
            "    taskPriority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  cell {3} AsyncAdaptor{{\n"
            "    cOut => composite.cSubSide;\n"
            "  }};\n"
            "  cell tPumpMainConverter PumpMain {{\n"
            "    cMain = DataPump.ePumpMain;\n"
            "  }};\n"
            "  cell tTask Task {{\n"
            "    cTaskBody = PumpMain.eTaskBody;\n"
            "    priority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  composite.ePumpMain => DataPump.ePumpMain;\n"
            "}};\n"
            "\n"
            "//---------  DataHolderBuffered ----------\n"
            "[active]\n"
            "composite {6}Buffered {{\n"
            "  attr {{\n"
            "    PRI     taskPriority;\n"
            "    size_t  stackSize = 4096;\n"
            '    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning\n'
            "  }};\n"
            "  entry {1} ePubSide;\n"
            "  entry {5} eSubSide;\n"
            "\n"
            "  cell {0} SyncAdaptor{{\n"
            "    cOut = SetRPCChannel.eThroughEntry;\n"
            "  }};\n"
            "  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_{2}  SetRPCChannel{{\n"
            "    cCall = AsyncAdaptor.eIn;\n"
            "    taskPriority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  cell {3} AsyncAdaptor{{\n"
            "    cOut = DataHolder.ePubSide;\n"
            "  }};\n"
            "  cell {6} DataHolder {{\n"
            "  }};\n"
            "  composite.ePubSide => SyncAdaptor.eIn;\n"
            "  composite.eSubSide => DataHolder.eSubSide;\n"
            "}};\n"
            "\n"
            "//---------  DataPumpHolderBuffered ----------\n"
            "[active]\n"
            "composite {4}Buffered {{\n"
            "  attr {{\n"
            "    PRI     taskPriority;\n"
            "    size_t  stackSize = 4096;\n"
            '    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning\n'
            "  }};\n"
            "  entry {5} eSubSide;\n"
            "  call  {5} cPubSide;\n"
            "  entry sPumpMain ePumpMain;\n"
            "  cell {6} DataHolder {{\n"
            "  }};\n"
            "  cell {0} SyncAdaptor{{\n"
            "    cOut = SetRPCChannel.eThroughEntry;\n"
            "  }};\n"
            "  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_{2}  SetRPCChannel{{\n"
            "    cCall    = AsyncAdaptor.eIn;\n"
            "    taskPriority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  cell {3} AsyncAdaptor{{\n"
            "    cOut = DataHolder.ePubSide;\n"
            "  }};\n"
            "  cell {7} DataPump {{\n"
            "    cSubSide = SyncAdaptor.eIn;\n"
            "    cPubSide => composite.cPubSide;\n"
            "  }};\n"
            "  cell tPumpMainConverter PumpMain {{\n"
            "    cMain = DataPump.ePumpMain;\n"
            "  }};\n"
            "  cell tTask Task {{\n"
            "    cTaskBody = PumpMain.eTaskBody;\n"
            "    priority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  composite.ePumpMain => DataPump.ePumpMain;\n"
            "  composite.eSubSide  => DataHolder.eSubSide;\n"
            "}};\n"
            "\n"
            "//---------  DataHolderBufferedSync ----------\n"
            "[active]\n"
            "composite {6}BufferedSync {{\n"
            "  attr {{\n"
            "    PRI     taskPriority;\n"
            "    size_t  stackSize = 4096;\n"
            '    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning\n'
            "  }};\n"
            "  entry {1} ePubSide;\n"
            "  entry {5} eSubSide;\n"
            "\n"
            "  cell {0} SyncAdaptor{{\n"
            "    cOut = SetRPCChannel.eThroughEntry;\n"
            "  }};\n"
            "  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_{2}  SetRPCChannel{{\n"
            "    cCall = AsyncAdaptor.eIn;\n"
            "    taskPriority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  cell {3} AsyncAdaptor{{\n"
            "    cOut = DataHolder.ePubSide;\n"
            "  }};\n"
            "  cell {6} DataHolder {{\n"
            "      cEventflag = Eventflag.eEventflag;\n"
            "  }};\n"
            "  cell tEventflag Eventflag{{\n"
            "    flagPattern = 0;\n"
            "  }};\n"
            "  composite.ePubSide => SyncAdaptor.eIn;\n"
            "  composite.eSubSide => DataHolder.eSubSide;\n"
            "}};\n"
            "\n"
            "//---------  DataPumpHolderBufferedSync ----------\n"
            "[active]\n"
            "composite {4}BufferedSync {{\n"
            "  attr {{\n"
            "    PRI     taskPriority;\n"
            "    size_t  stackSize = 4096;\n"
            '    ATR     attribute = C_EXP( "TA_ACT" );  // marshaler starts at the beginning\n'
            "  }};\n"
            "  entry {5} eSubSide;\n"
            "  call  {5} cPubSide;\n"
            "  entry sPumpMain ePumpMain;\n"
            "\n"
            "  cell {6} DataHolder {{\n"
            "    cEventflag = Eventflag.eEventflag;\n"
            "  }};\n"
            "  cell tEventflag Eventflag{{\n"
            "    flagPattern = 0;\n"
            "  }};\n"
            "  cell {0} SyncAdaptor{{\n"
            "    cOut = SetRPCChannel.eThroughEntry;\n"
            "  }};\n"
            "  cell tRPCPluginDPH_tTDR_tDataqueueOWChannel_{2}  SetRPCChannel{{\n"
            "    cCall    = AsyncAdaptor.eIn;\n"
            "    taskPriority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  cell {3} AsyncAdaptor{{\n"
            "    cOut = DataHolder.ePubSide;\n"
            "  }};\n"
            "  cell {7} DataPump {{\n"
            "    cSubSide = SyncAdaptor.eIn;\n"
            "    cPubSide => composite.cPubSide;\n"
            "  }};\n"
            "  cell tPumpMainConverter PumpMain {{\n"
            "    cMain = DataPump.ePumpMain;\n"
            "  }};\n"
            "  cell tTask Task {{\n"
            "    cTaskBody = PumpMain.eTaskBody;\n"
            "    priority  = composite.taskPriority;\n"
            "    attribute = composite.attribute;\n"
            "    stackSize = composite.stackSize;\n"
            "  }};\n"
            "  composite.ePumpMain => DataPump.ePumpMain;\n"
            "  composite.eSubSide  => DataHolder.eSubSide;\n"
            "}};\n"
            "\n".format(
                self.sync_adaptor_celltype,      # 0
                self.set_signature,              # 1
                self.set_signature_async,        # 2
                self.async_adaptor_celltype,     # 3
                self.datapumpholder_celltype,    # 4
                self.get_signature,              # 5
                self.dataholder_celltype,        # 6
                self.datapump_celltype))         # 7
        f.close()

    def gen_ep_func_body(self, file, b_singleton, ct_name, global_ct_name, sig_name,
                         ep_name, func_name, func_global_name, func_type, params):
        ct = str(ct_name)
        ep = str(ep_name)
        fn = str(func_name)

        if ct == self.datapump_celltype:
            file.print(
                "    ER      ercd = E_OK;                      // DataPumpHolderPlugin 0\n"
                "    CELLCB  *p_cellcb = GET_CELLCB(idx);\n"
                "    //  variables from data definition in celltype {}\n"
                "#ifdef DATAPUMPHOLDER_DEBUG\n"
                '    syslog( LOG_INFO, "DataPumpHolderPlugin {}.{}.{}" );\n'
                "#endif\n".format(self.celltype.get_name(), ct, ep, fn))

            for decl in list(self.attr_list) + list(self.var_list):
                type_ = decl.get_type().get_original_type()
                if isinstance(type_, PtrType):
                    type_ = type_.get_type()
                if decl.get_size_is():
                    size = "[{}]".format(decl.get_size_is())
                    size_note = "    // note: if size of array is too large, stack overflow might happen here or later"
                else:
                    size = ""
                    size_note = ""
                file.print("    {}\t{}{}{};{}\n".format(
                    type_.get_type_str(),
                    decl.get_identifier(),
                    type_.get_type_str_post(),
                    size,
                    size_note))

            file.print(
                "\n"
                "    // mikan: need error check\n"
                "    cPubSide_waitForNewData();    // wait for PubSide\n"
                "    cSubSide_waitForReadDone();   // wait for SubSuide\n")
            for decl in list(self.attr_list) + list(self.var_list):
                ref = "&" if decl.get_ptr_level() == 0 else ""
                file.print(
                    "\n"
                    "    // data: {0} get & set\n"
                    "    cPubSide_get_{0}( {1}{0} );\n"
                    "    cSubSide_set_{0}( {0} );\n".format(
                        decl.get_identifier(), ref))
            file.print(
                "\n"
                "    /// mikan: need error check\n"
                "    cPubSide_dataReadDone();\n"
                "    cSubSide_newDataReady();\n"
                "\n"
                "    return ercd;\n")

        elif ct == self.dataholder_celltype:
            if ep == "eSubSide":
                if fn == "waitForNewData":
                    file.print(
                        "    // wait For PubSide New Data\n"
                        "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                        "    ER       ercd = E_OK;\n"
                        "    FLGPTN   flgptn;\n"
                        "\n"
                        "#ifdef DATAPUMPHOLDER_DEBUG\n"
                        '    syslog( LOG_INFO, "DataPumpHolderPlugin {}.{}.{}" );\n'
                        "#endif\n"
                        "    if( is_cEventflag_joined() ){{\n"
                        "      if( VAR_status != DATAHOLDER_STAT_READING ){{\n"
                        "        ercd = cEventflag_wait( DATAHOLDER_EVFLAG_NEW_DATA, TWF_ANDW, &flgptn );\n"
                        "        (void)flgptn;\n"
                        "        if( ercd == E_OK ){{\n"
                        "          VAR_status = DATAHOLDER_STAT_READING;\n"
                        "        }}\n"
                        "      }} else{{\n"
                        "       ercd = E_PAR;\n"
                        "      }}\n"
                        "    }}\n"
                        "    return ercd;\n".format(ct, ep, fn))
                elif fn == "dataReadDone":
                    file.print(
                        "    // data Read Done\n"
                        "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                        "    ER       ercd = E_OK;\n"
                        "\n"
                        "#ifdef DATAPUMPHOLDER_DEBUG\n"
                        '    syslog( LOG_INFO, "DataPumpHolderPlugin {}.{}.{}" );\n'
                        "#endif\n"
                        "    if( is_cEventflag_joined() ){{\n"
                        "      if( VAR_status == DATAHOLDER_STAT_READING ){{\n"
                        "        VAR_status = DATAHOLDER_STAT_READ_DONE;  // フラグを操作する前に変更\n"
                        "        ercd = cEventflag_clear( ~DATAHOLDER_EVFLAG_NEW_DATA );\n"
                        "        ercd = cEventflag_set( DATAHOLDER_EVFLAG_READ_DONE ); // ここで PubSide 動作開始可能\n"
                        "      }} else {{\n"
                        "        ercd = E_PAR;\n"
                        "      }}\n"
                        "    }}\n"
                        "    return ercd;\n".format(ct, ep, fn))
                else:
                    file.print("/* {}.{} */\n".format(ep, fn))
                    dat_name = re.sub(r'^get_', '', fn)
                    file.print("/* {}.{} var_name: {}*/\n".format(ep, fn, dat_name))
                    decla = self.find_decl(dat_name)
                    if decla.get_ptr_level() == 0:
                        file.print(
                            "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                            "    *{0} = VAR_{0};\n"
                            "    return E_OK;\n".format(dat_name))
                    elif decla.get_ptr_level() == 1:
                        if decla.get_size_is():
                            spec = "*{}".format(decla.get_size_is())
                        else:
                            spec = ""
                        file.print(
                            "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                            "    memcpy( {0}, VAR_{0}, sizeof(*{0}){1} );\n"
                            "    return E_OK;\n".format(dat_name, spec))
            elif ep == "ePubSide":
                if fn == "waitForReadDone":
                    file.print(
                        "    // Wait For SubSide Read-Done\n"
                        "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                        "    ER       ercd = E_OK;\n"
                        "    FLGPTN   flgptn;\n"
                        "\n"
                        "#ifdef DATAPUMPHOLDER_DEBUG\n"
                        '    syslog( LOG_INFO, "DataPumpHolderPlugin {}.{}.{}" );\n'
                        "#endif\n"
                        "    if( is_cEventflag_joined() ){{\n"
                        "      // cygwin_kernel.cdl の環境では、Eventflag の初期値が設定されないため\n"
                        "      // ここで設定する (この設定は、正規の環境で残っても問題ない)\n"
                        "      if( VAR_status == DATAHOLDER_STAT_NONE ){{\n"
                        "        VAR_status= DATAHOLDER_STAT_READ_DONE;\n"
                        "        cEventflag_set( DATAHOLDER_EVFLAG_READ_DONE );\n"
                        "      }}\n"
                        "      if( VAR_status != DATAHOLDER_STAT_WRITING ){{\n"
                        "        ercd = cEventflag_wait( DATAHOLDER_EVFLAG_READ_DONE, TWF_ANDW, &flgptn );\n"
                        "        (void)flgptn;\n"
                        "        if( ercd == E_OK ){{\n"
                        "          VAR_status = DATAHOLDER_STAT_WRITING;\n"
                        "        }}\n"
                        "      }} else{{\n"
                        "        ercd = E_PAR;\n"
                        "      }}\n"
                        "    }}\n"
                        "    return ercd;\n".format(ct, ep, fn))
                elif fn == "newDataReady":
                    file.print(
                        "    // New Data Ready\n"
                        "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                        "    ER       ercd = E_OK;\n"
                        "\n"
                        "#ifdef DATAPUMPHOLDER_DEBUG\n"
                        '    syslog( LOG_INFO, "DataPumpHolderPlugin {}.{}.{}" );\n'
                        "#endif\n"
                        "    if( is_cEventflag_joined() ){{\n"
                        "      if( VAR_status == DATAHOLDER_STAT_WRITING ){{\n"
                        "        VAR_status = DATAHOLDER_STAT_WRITE_DONE;  // フラグを操作する前に変更\n"
                        "        ercd = cEventflag_clear( ~DATAHOLDER_EVFLAG_READ_DONE );\n"
                        "        ercd = cEventflag_set( DATAHOLDER_EVFLAG_NEW_DATA ); // ここで SubSide 動作開始可能\n"
                        "      }} else{{\n"
                        "       ercd = E_PAR;\n"
                        "      }}\n"
                        "    }}\n"
                        "    return ercd;\n".format(ct, ep, fn))
                else:
                    dat_name = re.sub(r'^set_', '', fn)
                    file.print("/* {}.{} var_name: {}*/\n".format(ep, fn, dat_name))
                    decla = self.find_decl(dat_name)
                    if decla.get_ptr_level() == 0:
                        file.print(
                            "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                            "    VAR_{0} = {0};\n"
                            "    return E_OK;\n".format(dat_name))
                    elif decla.get_ptr_level() == 1:
                        if decla.get_size_is():
                            spec = "*{}".format(decla.get_size_is())
                        else:
                            spec = ""
                        file.print(
                            "    CELLCB   *p_cellcb = GET_CELLCB(idx);\n"
                            "    memcpy( VAR_{0}, {0}, sizeof(*{0}){1} );\n"
                            "    return E_OK;\n".format(dat_name, spec))
            else:
                raise Exception(
                    "DataPumpHolderPlugin: Unknown celentryltype {}.{}".format(ct, ep))

        elif ct in (self.sync_adaptor_celltype, self.async_adaptor_celltype):
            file.print("    CELLCB  *p_cellcb = GET_CELLCB(idx);\n")
            if not func_type.get_type().is_void():
                file.print("    return ")
            else:
                file.print("  ")
            file.print("cOut_{}(".format(fn))
            delim = ""
            for param in params:
                file.print("{}{}".format(delim, param.get_name()))
                delim = ", "
            file.print(");\n")
        else:
            if not G.generate_all_template:
                raise Exception("DataPumpHolderPlugin: Unknown celltyep {}".format(ct))

    def gen_preamble(self, file, b_singleton, ct_name, global_ct_name):
        ct = str(ct_name)
        if ct == self.sync_adaptor_celltype:
            file.print(
                "    /* このセルタイプは、waitForReadDone 関数を非 oneway 化するためのもの */\n")
        elif ct == self.async_adaptor_celltype:
            file.print(
                "    /* このセルタイプは、waitForReadDone 関数を oneway 化するためのもの */\n")

    def find_decl(self, var_attr_name):
        name = str(var_attr_name)
        for decl in self.attr_list:
            if str(decl.get_name()) == name:
                return decl
        for decl in self.var_list:
            if str(decl.get_name()) == name:
                return decl
        raise Exception(
            "DataPumpHolderPlugin: Unknown data name {} data:{}".format(
                self.celltype.get_name(), var_attr_name))
