# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#      Generator for TOPPERS Embedded Component System
#
#   Copyright (C) 2008-2020 by TOPPERS Project
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/RPCPlugin.rb を
#   Python へ移植したものである．ライセンスは tecsgen.py の冒頭を参照のこと．
#
#   $Id: RPCPlugin.rb 3302 2026-06-07 06:01:02Z okuma-top $
#++

from tecslib.core import globals as G
from tecslib.core.componentobj.celltype import Celltype
from tecslib.core.componentobj.compositecelltype import CompositeCelltype
from tecslib.core.componentobj.namespace import Namespace
from tecslib.core.componentobj.namespacepath import NamespacePath
from tecslib.plugin.ThroughPlugin import ThroughPlugin
from tecslib.plugin.lib.GenTransparentMarshaler import GenTransparentMarshaler, RPCPluginArgProc
from tecslib.plugin.lib.GenParamCopy import GenParamCopy
from tecslib.rubylib.symbol import Sym


def _set_noClientSemaphore(obj, rhs):
    obj.set_noClientSemaphore(rhs)


def _set_semaphoreCelltype(obj, rhs):
    obj.set_semaphoreCelltype(rhs)


#= Transparent RPC プラグイン
# Transparent RPC チャンネルを生成する
# プラグイン引数は以下の RPCPluginArgProc を参照

# mikan through plugin: namespace が考慮されていない
# これを利用する場合、以下のように toppers_jsp.cdl sChannel.cdl を指定する必要がある
# tecsgen toppers_jsp.cdl sChannel.cdl your_description.cdl

# 以下を仮定（制限事項）
#  呼び元、呼び先のエンディアン、char, short, int_t, long_t, intptr_t のサイズが同じ
#  有符号、無符号でサイズが同じ

class RPCPlugin(GenParamCopy, GenTransparentMarshaler, ThroughPlugin):

    # RPCPlugin 専用のオプション
    TransparentRPCPluginArgProc = dict(RPCPluginArgProc)  # 複製を作って元を変更しないようにする
    TransparentRPCPluginArgProc["noClientSemaphore"] = _set_noClientSemaphore
    TransparentRPCPluginArgProc["semaphoreCelltype"] = _set_semaphoreCelltype

    #=== RPCPlugin の initialize
    #  説明は ThroughPlugin (plugin.rb) を参照
    def __init__(self, cell_name, plugin_arg, next_cell, next_cell_port_name, next_cell_port_subscript, signature, celltype, caller_cell):
        super().__init__(cell_name, plugin_arg, next_cell, next_cell_port_name, next_cell_port_subscript, signature, celltype, caller_cell)
        self.b_noClientSemaphore = False
        self.semaphoreCelltype = "tSemaphore"
        self.initialize_transparent_marshaler(cell_name)

        # オプション：GenTransparentMarshaler 参照
        self.plugin_arg_check_proc_tab = RPCPlugin.TransparentRPCPluginArgProc
        self.parse_plugin_arg()

        self.rpc_channel_celltype_name = "tRPCPlugin_{}_{}".format(self.TDRCelltype, self.signature.get_global_name())
        self.rpc_channel_celltype_name_full = "tRPCPlugin_{}_{}_{}".format(
            self.TDRCelltype, self.channelCelltype, self.signature.get_global_name())
        self.rpc_channel_celltype_file_name = "{}/{}.cdl".format(G.gen, self.rpc_channel_celltype_name)

        if self.signature.need_PPAllocator():
            if self.PPAllocatorSize is None:
                self.cdl_error("RPC9999 PPAllocatorSize must be speicified for oneway [in] array")
                # @PPAllocatorSize = 0   # 仮に 0 としておく (cdl の構文エラーを避けるため)

#    @signature.each_param{ |func_decl, param_decl|
#      if func_decl.get_type.is_oneway? then
#        if ( param_decl.get_size || param_decl.get_count ) && param_decl.get_string then
#          cdl_error( "array of string not supported for oneway function in Transparent RPC" )  # mikan 文字列の配列
#        elsif param_decl.get_string == -1 then
#          cdl_error( "length unspecified string is not permited for oneway function in Transparent RPC" )  # mikan 長さ未指定文字列
#        end
#      end
#    }

    #=== plugin の宣言コード (celltype の定義) 生成
    def gen_plugin_decl_code(self, file):

        ct_name = "{}_{}".format(self.ct_name, self.channelCelltype)

        # このセルタイプ（同じシグニチャ）は既に生成されているか？
        if ThroughPlugin.generated_celltype.get(ct_name) is None:
            ThroughPlugin.generated_celltype[ct_name] = [self]
        else:
            ThroughPlugin.generated_celltype[ct_name].append(self)
            return

        self.gen_marshaler_celltype_(file)

    #===  through cell コードを生成
    #
    #
    def gen_through_cell_code(self, file):

        self.gen_plugin_decl_code(file)

        # セルを探す
        # path =["::",@next_cell.get_global_name]
        # cell = Namespace.find( path )
        cell = Namespace.find(self.next_cell.get_namespace_path())

        if self.next_cell_port_subscript:
            subsc = "[{}]".format(self.next_cell_port_subscript)
        else:
            subsc = ""
        file.print(
            "/*\n"
            " * generated by RPCPlugin\n"
            " *   start_region={}\n"
            " *   end_region  ={}\n"
            " *   next_cell.entry={}.{}{}\n"
            "/ */\n"
            "import( \"{}\" );\n"
            "\n".format(
                self.start_region.get_namespace_path(),
                self.end_region.get_namespace_path(),
                self.next_cell.get_namespace_path(), self.next_cell_port_name, subsc,
                self.rpc_channel_celltype_file_name)
        )

        nest = self.region.gen_region_str_pre(file)
        indent_str = "  " * nest
        if self.next_cell_port_subscript:
            subscript = '[' + str(self.next_cell_port_subscript) + ']'
        else:
            subscript = ""

        file.print(
            "{}// 一方向チャンネルセル\n"
            "{}cell {} {} {{\n"
            "{}}};\n"
            "\n"
            "{}// RPC チャンネルセル\n".format(
                indent_str,
                indent_str, self.channelCelltype, self.channelCellName,
                indent_str,
                indent_str)
        )

        # #473 が解決された場合、composite リレーアロケータに変更すべき
        # アロケータの指定があるか？
        if cell is not None and len(cell.get_allocator_list()) > 0:

            file.print("{}[allocator(".format(indent_str))

            delim = ""
            for type_, eport, subsc, func, buf, alloc in cell.get_allocator_list():

                file.print(delim)
                delim = ",\n{}           ".format(indent_str)        # 最終行には出さない

                if subsc:        # 配列添数
                    subsc_str = "[{}]".format(subsc)
                else:
                    subsc_str = ""

                eport = "eThroughEntry"  # RPCの受け口名に変更
                file.print("{}{}.{}.{} = {}".format(eport, subsc_str, func, buf, alloc))

            file.print(")]\n")

        file.print(
            "{}cell {} {} {{\n"
            "{}  {} = {}.{}{};\n"
            "{}  cTDR         = {}.eTDR;\n"
            "{}  cEventflag   = {}.eEventflag;\n"
            "{}  taskPriority = {};\n"
            "{}}};\n".format(
                indent_str, self.rpc_channel_celltype_name, self.cell_name,
                indent_str, self.call_port_name, self.next_cell.get_namespace_path(),
                self.next_cell_port_name, subscript,
                indent_str, self.channelCellName,
                indent_str, self.channelCellName,
                indent_str, self.task_priority,
                indent_str)
        )
        self.region.gen_region_str_post(file)

    def gen_marshaler_celltype_(self, file):
        file.print(
            "/* generated by RPCPlugin / */\n"
            "generate( TransparentRPCSignaturePlugin, {}, \"{}\");\n"
            "import( \"{}\" );\n".format(
                self.signature.get_namespace_path(),
                self.plugin_arg_str,
                self.marshaler_celltype_file_name)
        )

    #=== プラグイン引数 noClientSemaphore のチェック
    def set_noClientSemaphore(self, rhs):
        rhs = Sym(str(rhs))
        if rhs == Sym("true"):
            self.b_noClientSemaphore = True
        elif rhs == Sym("false"):
            self.b_noClientSemaphore = False
        else:
            self.cdl_error("RPC9999 specify true or false for noClientSemaphore")

    #=== プラグイン引数 semaphoreCelltype のチェック
    def set_semaphoreCelltype(self, rhs):
        self.semaphoreCelltype = Sym(str(rhs))
        nsp = NamespacePath.analyze(str(self.semaphoreCelltype))
        obj = Namespace.find(nsp)
        if not isinstance(obj, Celltype) and not isinstance(obj, CompositeCelltype):
            self.cdl_error("RPC9999 semaphoreCelltype '{}' not celltype or not defined".format(rhs))
