# -*- coding: utf-8 -*-
#
#  TECS Generator (Python port)
#
#   このファイルは tecsgen (Ruby 版) の tecslib/plugin/SignaturePlugin.rb を
#   Python へ移植したものである．
#
#   $Id: SignaturePlugin.rb 3225 2021-09-26 05:08:38Z okuma-top $
#

import re

from tecslib.rubylib.symbol import Sym
from tecslib.core.plugin import Plugin
from tecslib.core.syntaxobj.cdlstring import CDLString


def _sig_set_celltypeName(obj, rhs):
    obj.set_celltypeName(rhs)


def _sig_set_callName(obj, rhs):
    obj.set_callName(rhs)


def _sig_set_entryName(obj, rhs):
    obj.set_entryName(rhs)


SignaturePluginArgProc = {
    "celltypeName": _sig_set_celltypeName,
    "callName":     _sig_set_callName,
    "entryName":    _sig_set_entryName,
}


class SignaturePlugin(Plugin):

    def __init__(self, signature, option):
        super().__init__()
        self.signature = signature
        self.plugin_arg_str = CDLString.remove_dquote(option)
        self.plugin_arg_list = {}
        self.celltype_name = Sym("t{}_{}".format(self.__class__.__name__, self.signature.get_global_name()))

        port_name = re.sub(r'\As(.*)', r'\1', str(self.signature.get_name()))
        self.entry_port_name = Sym("e{}".format(port_name))
        self.call_port_name = Sym("c{}".format(port_name))

        if self.__class__.__name__ == "SignaturePlugin":
            self.plugin_arg_check_proc_tab = SignaturePluginArgProc
            self.parse_plugin_arg()

    @classmethod
    def gen_post_code(cls, file):
        pass

    def gen_cdl_file(self, file):
        send_receive = []
        if self.signature is not None:
            def _each_param(fd, param):
                dir_ = param.get_direction()
                if dir_ in ("SEND", "RECEIVE"):
                    send_receive.append([dir_, fd, param])
            self.signature.each_param(_each_param)

        file.print("""\
/*
 * generated by SignaturePlugin 
 *   signature: {}
 *   celltype:  {} (identity celltype)
 */
celltype {} {{
""".format(
            self.signature.get_namespace_path(),
            self.celltype_name,
            self.celltype_name))

        if len(send_receive) > 0:
            file.print("  [allocator(             /* relay allocator */\n")
            delim = ""
            for a in send_receive:
                file.print("{}\t{}.{}<={}.{}.{}".format(
                    delim, a[1].get_name(), a[2].get_name(),
                    self.call_port_name, a[1].get_name(), a[2].get_name()))
                delim = ",\n"
            file.print("), inline]\n")
        else:
            file.print("  [inline]\n")

        file.print("  entry {} {};\n".format(
            self.signature.get_namespace_path(), self.entry_port_name))
        file.print("  call  {} {};\n".format(
            self.signature.get_namespace_path(), self.call_port_name))
        file.print("};\n")

    def gen_ep_func_body(self, file, b_singleton, ct_name, global_ct_name, sig_name, ep_name,
                         func_name, func_global_name, func_type, params):
        ret_type = func_type.get_type()
        b_ret_void = ret_type.is_void()

        if not b_ret_void:
            file.print("  {}  retval;\n".format(ret_type.get_type_str()))

        if not b_singleton:
            file.print("  CELLCB *p_cellcb = {}_GET_CELLCB(idx);\n\n".format(global_ct_name))

        if not b_ret_void:
            file.print("  retval = ")
        else:
            file.print("  ")

        file.print("{}_{}(".format(self.call_port_name, func_name))

        delim = ""
        for param in params:
            file.print("{}{} {}".format(delim, "", param.get_name()))
            delim = ","

        file.print(" );\n")

        if not b_ret_void:
            file.print("  return retval;\n")

    def set_celltypeName(self, rhs):
        self.celltype_name = Sym(str(rhs))
        if not re.match(r'\A[A-Za-z_][0-9A-Za-z_]*\Z', str(self.celltype_name)):
            self.cdl_error("SignaturePlugin: '$1' celltype_name using unsuitable character",
                           self.celltype_name)

    def set_callName(self, rhs):
        self.call_port_name = Sym(str(rhs))
        if not re.match(r'\A[A-Za-z_][0-9A-Za-z_]*\Z', str(self.call_port_name)):
            self.cdl_error("SignaturePlugin: '$1' callName using unsuitable character",
                           self.call_port_name)

    def set_entryName(self, rhs):
        self.entry_port_name = Sym(str(rhs))
        if not re.match(r'\A[A-Za-z_][0-9A-Za-z_]*\Z', str(self.entry_port_name)):
            self.cdl_error("SignaturePlugin: '$1' entryName using unsuitable character",
                           self.entry_port_name)
